### ISSUE TITLE
Chrome crashes when using PaymentRequestButtonElement (browsing as Guest)

### ISSUE THREAD

**Issue by h8rry** [stripe/react-stripe-elements#103]
- Using Chrome (Version 61.0.3163.100 (Official Build) (64-bit)) on Mac OS 10.13 High Sierra
- Browsing as a "Guest"
- Browser crashes when calling the `props.stripe.paymentRequest` method  for the `PaymentRequestButtonElement` element.

**Comment by jez** [comment]
Wow, that's a failure mode I wouldn't expect. It sounds like maybe it's a bug with Chrome itself, not anything Stripe-related.

Does it still crash when you try to test the Payment Request API on this page: <https://rsolomakhin.github.io/pr/> ?

**Comment by h8rry** [comment]
Yes. It crashes on https://rsolomakhin.github.io/pr/. Using Chrome `Version 61.0.3163.100 (Official Build) (64-bit)` on Mac OS X 10.13 High Sierra

**Comment by h8rry** [comment]
@jez Seems like you are right. It's a bug with Chrome itself. Even https://stripe.com/elements/examples will crash the browser using Guest.

**Comment by h8rry** [comment]
This has been fixed in Chrome 63 https://bugs.chromium.org/p/chromium/issues/detail?id=772706#c9

**Comment by michelle** [comment]
Thanks for the update! That's great to hear :).
-- 
Sent from Gmail Mobile
