### ISSUE TITLE
Card Element: backspace in card number input 

### ISSUE THREAD

**Issue by sgarg17** [stripe/react-stripe-elements#105]
I am not able to backspace in the card number input on android between sections of 4 numbers.

Example: 4242 4242 
in this case I am not able to backspace to delete a number without holding down the backspace key which then removes the whole set of 4 numbers (resulting in 4242)

**Comment by jez** [comment]
Hey @sgarg17! Thanks for reporting this. I'm trying to reproduce it now, but backspacing on Android seems to work for me. Can you give some more information about which browser and Android version you're using?

**Comment by sgarg17** [comment]
Yea, I'm using Android 6.0 on a Huawei phone and the issue is coming up in an android webview

**Comment by cbaltatescu** [comment]
I can confirm this happens at least with Samsung S7 & S8 and Android 7.
Cannot reproduce on Android 6 on Nexus 5 or Android 8 on Nexus 6P.

**Comment by atty-stripe** [comment]
@sgarg17 @cbaltatescu this should now be fixed! Sorry it took us so long to reproduce. Could you try it out and confirm please?
