### ISSUE TITLE
Is it possible to translate placeholders for CardElement

### ISSUE THREAD

**Issue by githubdoramon** [stripe/react-stripe-elements#106]
I would like to translate the placeholders of the card element (car number, expiry, CVC and ZIP) to portuguese, which is not available for stripe elements. Is it possible?

**Comment by cweiss-stripe** [comment]
Unlike for the separate `cardNumber`, `cardCvc`, `cardExpiry`, `postalCode` elements (with the [`placeholder`](https://stripe.com/docs/stripe.js#element-options) option), it is not possible to set your own placeholders for the `card` element.
However, we are always looking into adding more translations, and I'll pass along the request for Portuguese. 
I'll close this issue for now, but will update it once I have news regarding the Portuguese localization.

**Comment by githubdoramon** [comment]
If any help is needed on the translation let me know

Regards
