### ISSUE TITLE
How to style react-stripe-elements with bootstrap

### ISSUE THREAD

**Issue by kanwar-saad** [stripe/react-stripe-elements#116]
Can someone give a working example for how to style react stripe elements with bootstrap styles? I am having difficulty grasping the idea of it. A similar question is asked before but it was without react elements. https://stackoverflow.com/questions/46039315/how-can-i-style-a-stripe-elements-input-with-bootstrap.
How do we perform similar steps using react stripe elements?

Thanks for any pointers.

**Comment by atty-stripe** [comment]
Hi there! Stripe Elements are rendered inside an iframe, and as such don't inherit your website's CSS by default. To apply Bootstrap styles to the Elements form inputs, you'll have to pass the styles through JavaScript.

To do so, you can pass in either the `classes` or `style` props to the Elements
React component that you're using. The documentation for both options can be found here: https://stripe.com/docs/stripe.js#element-options.

You can also take a look at some open-source examples of styling Elements here: https://stripe.github.io/elements-examples/. (Note the "View source on GitHub" links beneath each example.)

Hope that helps!

**Comment by jez** [comment]
Hey @kanwar-saad! I put together this JSFiddle to give you an idea of how this might work

https://jsfiddle.net/x88p2scL/1/

In the future, please only open issues to this repository which are bugs or features requests for react-stripe-elements. You can read our [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md) for more information on how to get help, specifically:

> If you're having general trouble with Stripe.js or your Stripe integration, please reach out to us using the form at https://support.stripe.com/email or come chat with us at #stripe on freenode. We're very proud of our level of service, and we're more than happy to help you out with your integration.
