### ISSUE TITLE
Customization form

### ISSUE THREAD

**Issue by kotchuprik** [stripe/react-stripe-elements#118]
### Summary

Hey, guys, I need to create payment form with my design.

![image](https://user-images.githubusercontent.com/802946/31999913-9b7e609a-b99d-11e7-8f08-60a51be702e9.png)

I tried to do this many times but it's going hard! How can I customize Elements by the simple way?

**Comment by jenan-stripe** [comment]
Hi @kotchuprik! We don't currently offer dropdown-based expiration date.

In the future, for questions like these, please write in to [support](https://support.stripe.com/)! This repository is specifically for the React bindings to Stripe Elements.
