### ISSUE TITLE
Can't create Animated form from examples

### ISSUE THREAD

**Issue by kotchuprik** [stripe/react-stripe-elements#119]
### Summary

Hey, guys. How can I create an animated form [from examples](https://stripe.com/docs/elements/examples#example-2) with react-stripe-elements? Sorry for this issue but I have no ideas right now :)

**Comment by jenan-stripe** [comment]
Hi @kotchuprik -- that link is actually to older examples. We recommend looking at https://stripe.com/elements/examples right now.

As far as helping with animations -- that's beyond the scope of this library. If there's something specific that doesn't work in react-stripe-elements, please let us know!

**Comment by kotchuprik** [comment]
well, the main problem is I can't set classes and handling functions (focus, blur, key press) via props :) I guess react-elements does not allow setup these params.
