### ISSUE TITLE
Unmounting CardElement loses context

### ISSUE THREAD

**Issue by leebenson** [stripe/react-stripe-elements#122]
When a `<CardElement />` unmounts and then re-appears on the page, `props.stripe.createToken()` yields:

> submit.js:58 Error! Error: You did not specify the type of Source or Token to create.
        We could not infer which Element you want to use for this operation.

In my use-case, I have a tab design that allows a user to select credit card or PayPal. Flicking between the two causes the error above.

When the component isn't unmounted/re-mounted, `props.stripe.createToken()` works fine.

**Comment by cweiss-stripe** [comment]
Hi @leebenson 

Thank you for reporting this!

I set up a quick jsfiddle with a makeshift "tab-switcher" that unmounts/remounts the card element, but was unable to recreate that issue: https://jsfiddle.net/y5wzu6dx/1/ (I also tried unmounting/remounting the whole `StripeProvider` or `Elements` subtree, but also did not see that error.)
Does my approach reflect your use case? Can you have a look and see where our implementations are different?

**Comment by asolove-stripe** [comment]
We recently identified one possible issue when un/re-mounting an element that would cause this kind of tokenization failure. We pushed a fix for it last week and have seen at least one case fixed as a result. Between that and not hearing back on a way to reproduce, I think I'm going to close this issue. If anyone runs into this again, very happy to reopen and investigate.
