### ISSUE TITLE
IBANElement, NameElement, and createSource for SEPA transactions?

### ISSUE THREAD

**Issue by Pomax** [stripe/react-stripe-elements#125]
There are no predefined Elements for IBAN and Name at the moment, which means in order to use Stripe Elements for SEPA payments in React we need to roll our own fields (with validation) and figure out a way to call Stripe.createSource for further payment handling.

**Comment by jenan-stripe** [comment]
Hi @Pomax. Thanks for the feature suggestion! We'll take this to the team, but no plans to announce for the moment.

**Comment by alvarormoya** [comment]
Hi @Pomax, were you able to do it? We have created components for SEPA but still don't know how to call createSource

**Comment by Pomax** [comment]
I gave up not long after.

**Comment by alvarormoya** [comment]
How did you manage to integrate sepa transactions?

**Comment by atty-stripe** [comment]
To build your own SEPA IBAN input, you can just create a normal input in React (just as you would for name, or email), and ask the user type in their IBAN. 

Upon form submission, retrieve the value from that input, and call the `stripe.createSource` function with the value. You'll get a `sepa_debit` Source in return, which you can pass to your server to complete the charge.

Here's an example: https://codesandbox.io/s/zx5350wkx3. You can see more docs here: https://stripe.com/docs/sources/sepa-debit.

**Comment by suberg** [comment]
> To build your own SEPA IBAN input, you can create a normal input in React (just as you would for name, or email), and ask the user type in their IBAN.
> 
> Upon form submission, retrieve the value from that input, and call the `stripe.createSource` function with the value. You'll get a `sepa_debit` Source in return, which you can pass to your server to complete the charge.
> 
> Here's an example: https://codesandbox.io/s/zx5350wkx3. You can see more docs here: https://stripe.com/docs/sources/sepa-debit.

Hi @atty-stripe, this doesn't work for me, because of an error: "The type `sepa_debit` is not a valid source type". Is there any other way to create custom IBAN field?

**Comment by atty-stripe** [comment]
Hi @suberg, what specifically does not work for you? The codesandbox example I linked still works to create `sepa_debit` Sources. The jsfiddle you linked seems to be for creating `bank_account` tokens, which also works.

Can you create a minimal reproduction of your issue using codesandbox or jsfiddle and share here?
