### ISSUE TITLE
Pasting in card numbers may result in card number being (wrongly) truncated

### ISSUE THREAD

**Issue by AaronO** [stripe/react-stripe-elements#127]
## Summary

Pasting in a valid card number over a previously valid card number may result in a truncated (and invalid) card number.

## Steps to reproduce

1. Run this project's demo (`yarn demo`)
2. Open the demo (http://localhost:8080/)
3. Copy the Diners Club test card number (`38520000023237`)
4. Paste it into an the (empty) card number field
5. Copy the American Express test card number (`378282246310005`)
6. Paste it into the card number field (`CMD+A` then `CMD+V`)
7. Observe that the American Express card number is truncated (and thus invalid)

## GIF

![](http://g.recordit.co/KyQ08KPTMN.gif)

**Comment by asolove-stripe** [comment]
Hi @AaronO, thanks for reporting this! That's definitely an unfortunate bug. I'm looking into it and will post an update here when I have one.

**Comment by michelle-stripe** [comment]
Thanks for the detailed report! This has now been fixed :).
