### ISSUE TITLE
Feature Idea: Stripe connect button/component

### ISSUE THREAD

**Issue by acomito** [stripe/react-stripe-elements#129]
#### Summary

> A Stripe connect button fro https://stripe.com/docs/connect/standard-accounts

#### Motivation

> Save a little time, match stripe branding standards out of the box

#### Similar APIs

> Uses existing stripe connect oauth for standard accounts

#### Alternatives

> A "Connect Stripe" react button for oauth/connecting a merchant. 

#### Scope

> Essentially a bare bones component for doing this https://stripe.com/docs/connect/standard-accounts . 

#### Risks

> Seems relatively simple and low risk. It's just to save people a little time.

**Comment by jenan-stripe** [comment]
Hi @acomito. Thanks for feature request! We've no plans to announce on Connect-based Elements for now, so I'm going to close this. I'll take your request to the team though. Thank you!
