### ISSUE TITLE
Generalized way of displaying error messages on *Element items

### ISSUE THREAD

**Issue by michael-reeves** [stripe/react-stripe-elements#13]
Maybe it's just a documentation issue, but there doesn't seem to be a generalized way of adding and error messages on the page when using multiple *Element components.  Errors are definitely coming back to onChange, but there doesn't seem to be a good way of determining which field on the page generated the error.

Generally I like to display the error message with the associated field, instead of just having a block of error messages at the top of the form.  I would like a relatively straightforward to determine which field to attach an error to.

**Comment by michelle** [comment]
If you are using `CardElement`, it functions as a single input, so the error should just be placed next to that Element. 

It sounds like you're using `CardNumberElement`, `CardExpiryElement`, etc, though. Each of them should call their `onChange` handlers for their specific errors only. Are you seeing something different? Perhaps something like this could work for you:

```jsx
// in your component:
handleChangeFor = (type) => ({error}) => { /* handle error */ }
render() {
  return (
    <CardNumberElement onChange={this.handleChangeFor('cardNumber')} />
    <CardExpiryElement onChange={this.handleChangeFor('cardExpiry')} />
    ...
  );
}

```

If that makes sense, we should definitely document this flow better. :)

**Comment by michael-reeves** [comment]
thanks. that looks pretty similar to what I came up with, but it's better because I was implementing a separate handler for each.

That solution will work

**Comment by michelle** [comment]
Awesome! If you have any recommendations for how we can document this, we 💜 PRs :).

**Comment by michael-reeves** [comment]
Does the onSubmit automatically fire onChange for each field?  I was really not expecting the onSubmit to render error messages correctly, due to the error messages I was seeing within onSubmit.  Was rather shocked when everything that worked for onChange worked with onSubmit.

What would be the best way to show my example for Bootstrap?  I can add an example file, or add to the Readme.

**Comment by michelle** [comment]
Yes, the onSubmit will fire onChange because if there's an error, the field
has "changed" state to its error state.

Adding to the demo or adding another demo would be amazing!

Michelle

**Comment by michael-reeves** [comment]
Ok, I’ll see what I can do to clean out my react-bootstrap stuff and get something posted.


On May 17, 2017, at 3:34 PM, michelle <notifications@github.com> wrote:

Yes, the onSubmit will fire onChange because if there's an error, the field
has "changed" state to its error state.

Adding to the demo or adding another demo would be amazing!

Michelle

**Comment by swrobel** [comment]
@michael-reeves did you ever come up w/ anything demo-wise?

**Comment by michael-reeves** [comment]
I have been head down on this project. 

I can show you what I came up with, and it seems to work, but I don’t have anything generic to post yet

**Comment by swrobel** [comment]
No worries, I can figure it out on my own based on what's been discussed here.
