### ISSUE TITLE
Im currently unable to import PaymentRequestButtonElement in VSCode

### ISSUE THREAD

**Issue by sonnysangha** [stripe/react-stripe-elements#133]
### Summary

Im currently unable to import PaymentRequestButtonElement in VSCode #133
As you can see, when I attempt to import the Element, the option is not present in the list of available imports. As a result, the PaymentRequestButtonElement cannot be used which I urgently need for my web app! This may be a silly mistake however any help would be greatly appreciated!

### Other information

<img width="744" alt="screenshot 2017-11-23 14 48 45" src="https://user-images.githubusercontent.com/24712956/33178244-6b84e900-d05d-11e7-849b-666e364cc674.png">

**Comment by sonnysangha** [comment]
<img width="744" alt="screenshot 2017-11-23 14 48 45" src="https://user-images.githubusercontent.com/24712956/33178244-6b84e900-d05d-11e7-849b-666e364cc674.png">

**Comment by sonnysangha** [comment]
<img width="744" alt="screenshot 2017-11-23 14 48 45" src="https://user-images.githubusercontent.com/24712956/33178244-6b84e900-d05d-11e7-849b-666e364cc674.png">

**Comment by sonnysangha** [comment]
As a result, the PaymentRequestButtonElement cannot be used which I urgently need for my web app!

**Comment by jez** [comment]
Hey @sonnysangha! Can you confirm that this is not an issue with VSCode? I'd suspect that it's just a matter of the code completion being broken, not that the import actually doesn't work.

If you type `PaymentRequestButtonElement` yourself and load the page, do you get an error in the console that says something like "identifier not found."

**Comment by sonnysangha** [comment]
Hey @jez, when typed manually, I received an error stating there was no type definition in node_modules/@types/... (I am using a Typescript React setup, sorry should have mentioned that) 
As a result I manually added the type definition and the error has now gone. I do however receive this error when manually changing the canMakePayment boolean value to true in chrome 'React developer tools'.

main.a960b39f.js:1 Error: The paymentRequestButton Element is not available in the current environment

Any suggestions as to why I may be receiving such an error?

**Comment by sonnysangha** [comment]
I was able to fix these issues however realised the Type definitions need to be updated and PaymentRequestButtonElement needs to be added as well as PaymentRequest 'object' parameter!

**Comment by jez** [comment]
> when manually changing the canMakePayment boolean value

I'm worried when you say "manually changing." This value is something that Stripe.js gets from the browser to determine whether the current browser supports the Payment Request API or Apple Pay.

I'm guessing you're on a browser that doesn't support or isn't set up for payment requests:

- These are the supported browsers:
  - https://stripe.com/docs/stripe-js/elements/payment-request-button#testing
- These are the prereqs to set up your device to able to use payment requests:
  - https://stripe.com/docs/stripe-js/elements/payment-request-button#prerequisites

**Comment by sonnysangha** [comment]
I think my explanation wasn't the best, in order for typescript to successful work alongside react-stripe-elements I had to edit the @types/react-stripe-elements in two areas, this does not in any way change the payment request API, I am simply adding two type definitions to the declarations file 'index.d.ts'

![screenshot 2017-11-29 12 01 14](https://user-images.githubusercontent.com/24712956/33374197-045f0888-d4fd-11e7-8181-72806b8cd4ed.png)

Here I have added the following lines:
Line 47: The PaymentRequestButtonElement parameter type definition which is passed through to the `PaymentRequestButtonElement` (else TS throws an error for no type definition)

Lines 86-87: The `PaymentRequestButtonElement` type definition, this is why the import was not working as type definitions had been added to all elements except for the `PaymentRequestButtonElement`

**Comment by cweiss-stripe** [comment]
Thank you for the explanation! 
And also thank you for submitting a [PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21830) to the DefinitelyTyped project. 👍
