### ISSUE TITLE
Zip code doesn't allow letters

### ISSUE THREAD

**Issue by ayroblu** [stripe/react-stripe-elements#135]
### Summary

Zip/postal codes in the UK have letters in them, I couldn't enter a postal code using the CardElement component

**Comment by ayroblu** [comment]
Auto detects based on card (cause cards are grouped by regions? seems a bit weird, but cool)
I don't think there's a test card for it, so you'll have to enter a valid UK credit card to test it

**Comment by jez** [comment]
Glad that you managed to rubber duck this one out! Also:

> I don't think there's a test card for it, so you'll have to enter a valid UK credit card to test it

Maybe you've already found https://stripe.com/docs/testing#cards, but maybe what you *didn't* notice was that there are separate tabs for different regions of international test cards.

If you click on the "Europe, Middle East, and Africa" tab, you'll find this GB test card:

```
4000008260000000
```

which you can use to test postal codes in the UK.

**Comment by justhamade** [comment]
I ran into this issue too, is this documented somewhere?

**Comment by ajford** [comment]
Just ran into this issue, with a customer who has a US card but is living abroad with a non-US address. We are currently unable to process their payment due to this "smart" behavior. Is there any way to fully disable it, or prompt a validation step?
