### ISSUE TITLE
IE10 and below: babel config

### ISSUE THREAD

**Issue by mikiest** [stripe/react-stripe-elements#140]
### Summary

This module doesn't work on **IE10 and below**, the `<StripeProvider` component cannot be instantiated:
`Unable to get property 'apiKey' of undefined or null reference`

### Other information

Probably due to the way `this.props` is accessed within some of the component constructors - `Provider` is not the only component that cannot be instantiated but is the first to throw an error.

### Possible resolution (PR coming)

Use [babel-plugin-transform-es2015-classes](https://babeljs.io/docs/plugins/transform-es2015-classes/) with:

```json
plugins: [
    [ "transform-es2015-classes", { "loose": true } ]
]
```

See [babel caveats](https://babeljs.io/docs/usage/caveats/#internet-explorer-classes-10-and-below-)

**Comment by cweiss-stripe** [comment]
@mikiest Thank you for reporting this and thank you for the referenced PR.

Before merging the fix, I'd like to reproduce the issue, which I so far have been unable to do.

Could you let me know which `react` version and which `react-stripe-elements` version you have been using? Or do you maybe even have a minimal example to reproduce the issue somewhere?

**Comment by cweiss-stripe** [comment]
I was able to reproduce this with React 16. (React 15 seemed to work fine for me).
Looking at your fix now.

**Comment by mikiest** [comment]
@cweiss-stripe The issue we are having is actually with React 15 (haven't tried with React 16 yet).

Did you test those with the same project config (babel, webpack, etc..)?

**Comment by cweiss-stripe** [comment]
@mikiest Thank you for the additional info.
I tested React 15.6.2 and React 16.2.0 in the same project using react-stripe-elements and only saw the error with React 16.
With your proposed fix, does everything work for you, or do you still see more errors besides the `Unable to get property 'apiKey' of undefined or null reference` Error?

**Comment by mikiest** [comment]
`Unable to get property 'apiKey' of undefined or null reference` is just the only visible error without this fix, but similar issues would actually be thrown from the other component constructors.

With this fix, no error is thrown and I can get a payment through.

**Comment by cweiss-stripe** [comment]
@mikiest I merged your PR and released a new version.
Please let us know if this fixed your original issue.

**Comment by danphamus304** [comment]
https://github.com/mikiest/react-stripe-elements/commit/cf2c89629f3658d5facf1f3fbead90cf7523619d
