### ISSUE TITLE
Error with Card Split-field Form

### ISSUE THREAD

**Issue by MathieuAllegorithmic** [stripe/react-stripe-elements#146]
I've got an error when I'm using the card split-field form on the JSFiddle demo.

`
error:
{type: "invalid_request_error", message: "Missing required param: card[exp_month].",…}
message: "Missing required param: card[exp_month]."
param: "card[exp_month]"
type:"invalid_request_error"
`

**Comment by sauldhernandez** [comment]
Getting the same error here.

**Comment by yegortokmakov** [comment]
rolling back to 1.2.x might solve the issue. 

in release 1.3 there is a change allowing to provide a custom instance of Stripe to Stripe provider: 
https://github.com/stripe/react-stripe-elements/tree/v1.3.0#using-an-existing-stripe-instance

which leads to `Unrecognized Stripe() parameter: stripe is not a recognized parameter. This may cause issues with your integration in the future.`

**Comment by yegortokmakov** [comment]
we are using `injectStripe` to get initialized an instance of Stripe if it helps.

can it be related to a new prop `stripe = null` which ends up in options here? https://github.com/stripe/react-stripe-elements/compare/v1.2.1...v1.3.0#diff-ac604848eeadb1baa24313a33b809514R93

**Comment by michelle** [comment]
Hi! Sorry for the confusion. We’re rolling back 1.3.0 right now, and will investigate these issues.

**Comment by michelle** [comment]
@yegortokmakov your issue sounds different from the expiry issue. What properties are you passing to StripeProvider? Does your integration work in 1.2.X?

**Comment by sauldhernandez** [comment]
Rolling back to 1.2.0 fixed this issue for me.

**Comment by michelle** [comment]
1.3.0 is now unpublished, and a fresh install should get you 1.2.1. We’re working on rolling 1.3.1 with the bug fixes ASAP. Sorry for the inconvenience.

**Comment by jez** [comment]
This should be fixed now in v1.3.1. Again, sorry for the inconvenience.
