### ISSUE TITLE
Error with Card Split-field Form in 1.3.1 when following Advanced Integrations

### ISSUE THREAD

**Issue by kavsingh** [stripe/react-stripe-elements#148]
Similar to https://github.com/stripe/react-stripe-elements/issues/146

Issue was resolved in 1.3.1 (thanks for the quick work!) except when using steps described in the Advanced Integrations section of the readme, in particular the [Loading Stripe.js asynchronously section](https://github.com/stripe/react-stripe-elements#loading-stripejs-asynchronously), in which case the issue persists.

Have made a repo which reproduces the issue here: https://github.com/kavsingh/rse131-issue-demo

Thanks!

**Comment by michelle** [comment]
Thanks for the reproduction. We'll take a look now.

**Comment by michelle** [comment]
We've identified the issue and will push a fix soon!

**Comment by michelle** [comment]
@kavsingh 1.3.2 is now released with the fix!

**Comment by kavsingh** [comment]
@michelle works great now, thanks!
