### ISSUE TITLE
`We could not retrieve data from the specified Element` on Mobile Safari

### ISSUE THREAD

**Issue by tinovyatkin** [stripe/react-stripe-elements#152]
We are experiencing intermittent errors on Mobile Safari using Stripe Elements v3 integration.

Our integration (https://transfers.do/book/) creates Stripe Card (and PaymentRequest) elements only after `onload` fire for Stripe script, so, it's loaded successfully for sure.

Sentry error:
`
<img width="1226" alt="screenshot 2018-01-12 08 08 45" src="https://user-images.githubusercontent.com/5350898/34860614-d5dcd856-f76f-11e7-82b8-502e132c286a.png">

Sentry statistics on this error:

<img width="327" alt="screenshot 2018-01-12 08 05 03" src="https://user-images.githubusercontent.com/5350898/34860618-e288efa4-f76f-11e7-94e3-aef76dec50f6.png">

**Comment by jez** [comment]
What version of react-stripe-elements are you using?

**Comment by tinovyatkin** [comment]
Oops, sorry, wrong repo. We are using Stripe elements directly.
