### ISSUE TITLE
Card Element: reveal sub field onFocus 

### ISSUE THREAD

**Issue by lanefelker** [stripe/react-stripe-elements#153]
Feature request or idea? Consider opening an [API review](.github/API_REVIEW.md)!

### Summary
I want to know what subfield in the CardElement a user is entering, Card Number, Expiration Date, or CVC, in order to do a visual change associated with the input a user is currently giving. The onFocus event only fires when the entire card element gets focused and the onChange event doesn't reveal what field the user is on. Is there currently a way to gain this information? If not, I think it would be a great feature :)

Thanks!

**Comment by cweiss-stripe** [comment]
@lanefelker 
Thank you for the feature suggestion.
There is currently no way to find distinguish which part of the `card` Element was focused.
We currently have no plans to implement the ability to do so, but we will consider your suggestion for the future.
