### ISSUE TITLE
CardElements sends the postalCode onChange even if it's not visible in the form

### ISSUE THREAD

**Issue by emilecantin** [stripe/react-stripe-elements#158]
### Summary

If we've entered a postal code in the CardElement component, it'll continue to send it to the onChange handler, even if it's now hidden in the form

### Other information

Steps to reproduce:

1 - Enter a US or Canadian card in CardElement (the all-in-one version)
2 - Fill out all details, including the postal / zip code
3- Change the card number for e.g. a French one -> the postal / zip code field disappears
4- Check the value sent in the onChange event

Expected result: The value dones't have a postal / zip code
Actual result: The old postal / zip code is still there

Given that the postal code is pretty much the only value we get in the event, it'd be nice if it reflected what's actually displayed in the form.

**Comment by jez** [comment]
Hey @emilecantin! Thanks for the report. I've confirmed that this is an issue.
In fact, it's an issue in Stripe.js itself, not react-stripe-elements.

Its progress is being tracked in our internal bug tracker, but I'll update this issue when the fix goes live (probably sometime next week).

Sorry for any trouble this is causing!

**Comment by michelle** [comment]
This has been fixed!

Please let us know if you see any other issues :)
