### ISSUE TITLE
Passing options to the stripe createToken

### ISSUE THREAD

**Issue by binarymee** [stripe/react-stripe-elements#16]
I am trying to pass additional information of the card like name , address as mentioned here, https://stripe.com/docs/stripe.js#stripe-create-token

```
this.props.stripe.createToken({
	name: 'Name',
	address_line1: 'Address 1',
	address_line2: 'Address 2'
	address_city: 'Address C'
	address_state: 'Address S'
	address_zip: 'Address Z'
	address_country: 'Address C',

}).then(({token}) => {
    console.log('Received Stripe token:', token);
});
```

When I try to retrieve the card information with the token generated, the extra options weren't set. What could be the issue?

**Comment by michelle** [comment]
Hi! Are you sure they're not set? I just tried with your exact code snippet:

```js
  handleSubmit = ev => {
    ev.preventDefault();
    this.props.stripe
      .createToken({
        name: 'Name',
        address_line1: 'Address 1',
        address_line2: 'Address 2',
        address_city: 'Address C',
        address_state: 'Address S',
        address_zip: 'Address Z',
        address_country: 'Address C',
      })
      .then(payload => console.log(payload));
  };
```

I got this, which has all the right address / name fields:
<img width="684" alt="screen shot 2017-06-01 at 8 53 52 pm" src="https://cloud.githubusercontent.com/assets/928757/26710139/ac03d368-470c-11e7-9c05-8a55e4875e63.png">

I'm going to close this, but feel free to reopen if you're still having issues or if I'm misunderstanding your problem!
