### ISSUE TITLE
Tab Index of Card Element

### ISSUE THREAD

**Issue by twils0** [stripe/react-stripe-elements#162]
What's the best way to set the tab index of the various inputs included in the card element?

I need to set the tab index of these inputs to '-1', for a form that's mounted but not shown, and then change the tab index of these inputs to '0', when the form is shown.

**Comment by atty-stripe** [comment]
Hi @twils0! Unfortunately there isn't a way to set the `tabindex` of inputs within the Card Element right now. Is it possible to unmount the Card Element, and remount it when needed? You could also try setting `display: none` on the container of the Card Element, and this should remove it from the tab order.

**Comment by twils0** [comment]
Sure - no problem. `display: none` works pretty well. Thanks for the quick response!
