### ISSUE TITLE
Can't input more than 16 digits for credit card number

### ISSUE THREAD

**Issue by BertLo** [stripe/react-stripe-elements#166]
Does the CardElement supports inputting credit card number that has more than 16 digits? I tried all of the examples and all of them didn't allow me to input more than 16 digits.

**Comment by michelle** [comment]
Hi @BertLo! We don't support 19-digit card numbers in the API.

**Comment by maxcuttins** [comment]
Hello,

do Stripe plan to add support to 16digits cards or is this something that will never be added?
