### ISSUE TITLE
Possible to create more than one token with different API Keys?

### ISSUE THREAD

**Issue by pudgereyem** [stripe/react-stripe-elements#168]
## Issue
I have to create two tokens:

1. One that I will use (our API Key)
2. One that our partner will use (Partner API Key)

I'd like the user only to input their information once. **Is it possible to create two tokens using different API Keys?** Have you came across this use case before? And if so; what's the most common solution to the problem?

**Comment by asolove-stripe** [comment]
We would recommend using Stripe Elements to tokenize the card information once, and then using backend Stripe APIs to extend access to that card to other accounts. Please feel free to reach out to [Stripe Support](https://support.stripe.com/email) if you need help with the details!

**Comment by pudgereyem** [comment]
Thanks for the swift reponse @asolove-stripe.
