### ISSUE TITLE
Is it possible to capture coupon?

### ISSUE THREAD

**Issue by kongakong** [stripe/react-stripe-elements#171]
### Summary

Does this library supports capturing of coupon code? If not, what is the best way to handle coupon?

**Comment by asolove-stripe** [comment]
This repository is for the React wrapper of Stripe Elements. For questions about Stripe products in general, please [search our docs](https://stripe.com/docs/recipes/coupons-for-charges#managing-coupons-on-the-server) or [contact support](https://support.stripe.com).

**Comment by kongakong** [comment]
I am not asking about the coupon functionality. I want to know if this wrapper supports entering a coupon code by a user. If not, what is the best practice to do so. 

Purely a UI question.

**Comment by BrodaNoel** [comment]
@asolove-stripe I have the same question as @kongakong.
I have to implement the coupons/discounts that Strip already provide (https://stripe.com/docs/billing/subscriptions/discounts) and I see there is no UI component related

**Comment by asolove-stripe** [comment]
Hi @BrodaNoel! Sorry, but this library does not currently contain any UI for collecting coupon codes. We [recommend](https://stripe.com/docs/recipes/coupons-for-charges#improving-the-user-experience) building a UI that collects the code in a text input and use ajax to see if the code is valid and to update the prices shown on your checkout UI.
