### ISSUE TITLE
Is it possible to create Account Form using this pacakge?

### ISSUE THREAD

**Issue by santhi-nyros** [stripe/react-stripe-elements#172]
Hi,
I have used card element form provided in react-stripe-elements.
I need to add bank account details. So I need to show account form with account holder name, account number and Routing number Fields.

Is it possible to do with react-stripe-elements?

Thank you.

**Comment by asolove-stripe** [comment]
Unfortunately, Stripe Elements currently does not have a way to gather bank account information.

**Comment by santhi-nyros** [comment]
Thanks for reply..
