### ISSUE TITLE
this.props.stripe.createToken returning null instead of actual error.

### ISSUE THREAD

**Issue by tannerhallman** [stripe/react-stripe-elements#175]
As title suggests, I have injected the `Stripe context` successfully into my React project. When I call the `createToken()` with params that are valid, I get a token back successfully so I know it's all been setup correctly. The issue arrises when I end up passing params that don't satisfy Stripe's requirements for 'valid data.' If, for instance, while validating a `bank_account` I pass a short routing_number, instead of hitting the error block of my promise, I get a null token. It is only by analyzing the network request using chrome debug tools do I get the error. 

What I'm asking is, how do I call the `createToken()` method to receive the response when it's not a token?

For reference, I've included a sample call.

Parent
```
this.child.validateBank(this, {
        country: this.state.country,
        currency: this.state.currency,
        routing_number: this.state.routingNumber,
        account_number: this.state.accountNumber,
        account_holder_name: this.state.accountHolderName,
        account_holder_type: this.state.accountHolderType,
      }).then(token => {
        if (token) {
          params.bank_token = token.id;
          this.props.stripe_actions.updateAccount(params)
            .then(() => {
              this.props.toggleTab('1');
            });
        } else {
          console.log('token was null so not proceeding with update call.');
        }
      }).catch(err => {
        console.log('error', err);
      });
```
Child
```
validateBank = (parentContext, bankData) => {
    return new Promise((resolve, reject) => {
      this.props.stripe.createToken('bank_account', bankData)
        .then(({ token }) => {
          resolve(token, parentContext);
        })
        .catch(err => {
          reject(err);
        });
    });
  };
```

In my `validateBank()` method, I always hit the `.then()` instead of the `.catch()` when there is a validation error on Stripe's part.

![screen shot 2018-02-22 at 11 08 00 am](https://user-images.githubusercontent.com/10327491/36549427-c86d85be-17c0-11e8-9fd5-4ef6d1baf06e.png)

 
![screen shot 2018-02-22 at 11 08 08 am](https://user-images.githubusercontent.com/10327491/36549444-d250200a-17c0-11e8-89a4-0739ea35b1cf.png)

**Comment by michelle** [comment]
Hi there! Sorry for the delayed response.

From our docs, you can see that the resolution value (i.e. the value that the function supplied to `.then(...)` is called with) has the shape: `{token: Token} | {error: APIError}`. If there is a 400, you can access the error like this:
```
stripe.createToken('bank_account', bankData).then(({token, error}) => {
  if (error) {
    // handle error
  } else {
    // handle token
  }
});
```

We do not reject the Promise for validation errors, because oftentimes 40Xs happen in the normal control flow (e.g. when your user types in a bad bank account number). We don't want folks using async/await to have to catch an error in order to handled these validation errors:
```
// This is what we DON'T want, because it's awkward:
try {
  const bankAccount = await stripe.notARealCreateToken('bank_account', bankData);
} catch (e) {
  // handle validation error
}
```
