### ISSUE TITLE
Allow setting of id on mount container

### ISSUE THREAD

**Issue by thchia** [stripe/react-stripe-elements#177]
#### Summary

Allow the `id` attribute to be set on the mount container of an Element:
> A brief of the new API, including a code sample.
```javascript
<CardNumberElement
  id="my-card"
  {...props}
/>
```
> Consider where this feature would fit into our documentation,
> and what the updated documentation would look like.
```javascript
type ElementProps = {
  className?: string,
  elementRef?: (StripeElement) => void,
  id?: string,

  // For full documentation on the events and payloads below, see:
  // https://stripe.com/docs/elements/reference#element-on
  onBlur?: () => void,
  onChange?: (changeObject: Object) => void,
  onFocus?: () => void,
  onReady?: () => void,
};
```

#### Motivation

> Describe the problem you are trying to solve with this API change.

Currently the only attributes a user can set on the mount container are the classes. This is inconsistent with non-React Elements: [element.mount accepts either a CSS selector or a DOM element.](https://stripe.com/docs/stripe-js/reference#element-mount)
> What does this API enable that was previously not possible?

Allows user to define a label for the Element and correctly reference the Element with the label's `htmlFor` attribute. This is required for custom label implementations such as the floating label example shown [here in Example 2](https://github.com/stripe/elements-examples). Specifically when positioning the label over the input field, without referencing the input in the `htmlFor`, the input cannot receive focus when clicking on the label.
#### Scope

> Which interfaces will this apply to? For example, is this specific
> to one component, or does it affect all Element components?
> Does this set a precedent for future interfaces we'll add?

I propose to add this to the `Element` component:
```javascript
// Now
componentDidMount() {
  this.context.addElementsLoadListener((elements: ElementsShape) => {
    /* snip */

    element.mount(this._ref);
    /* snip */
  });
}
// ...
render() {
  return <div className={this.props.className} ref={this.handleRef} />;
}

// Proposed
componentDidMount() {
  this.context.addElementsLoadListener((elements: ElementsShape) => {
    /* snip */

    element.mount(this.props.id ? `#${this.props.id}` : this._ref);
    /* snip */
  });
}
// ...
render() {
  return <div
    id={this.props.id || undefined} // if undefined the attribute won't be present
    className={this.props.className}
    ref={this.handleRef}
  />;
}
```

#### Risks

> What are some ways users might get confused or misuse this feature?

I don't think this is any more confusing than having the `elementRef` prop.

 Happy to submit PR (#178 ).

**Comment by thchia** [comment]
Gentle ping to the maintainers - is it possible to get an indication if this proposed change will be accepted. I would prefer that over having to use a fork for my project :)

@jez @atty-stripe

**Comment by jez** [comment]
Hey @thchia!

Sorry for not acknowledging this earlier. Initial feedback: this looks good! I can't see an obvious way to work around this with the current react-stripe-elements API. The next step is that we're going to put your proposal through our normal, internal API review. Since it's a small proposal it shouldn't take longer than till the end of the week (but I can't predict the future so don't quote me!)

Our primary goals will be to determine whether this new API surface area is sufficiently orthogonal to the rest of RSE, whether it's easy to maintain going forward, and whether we'd want to support your use case like this or with some sort of alternative.

Thanks again for doing this! Your issue is easy to follow, and had really strong underlying motivations.

**Comment by thchia** [comment]
@jez thanks! No worries on the timeline, I fully support a thorough review procedure.

**Comment by jez** [comment]
Heads up that we took a look at this, and the API review looks good!

I'm going to switch the conversation over to #178 for code review.
