### ISSUE TITLE
Change Object in Card Element has only zipcode prop

### ISSUE THREAD

**Issue by mmarinm** [stripe/react-stripe-elements#18]
I tried to extract data from the form by accessing the change object inside a handleChange function but only value that is available is the zip code. 

Am I doing something wrong? how should I extract Card number and other inputs from CardElement?

**Comment by jenan-stripe** [comment]
Hi @mmarinm! You can't access the card information directly for security reasons. Instead, you can use `createToken` to securely transmit the card information to Stripe's servers in exchange for a token.

**Comment by LeoAref** [comment]
@jenan-stripe what's the security concern about accessing the card information?

It's HTML input element anyway, so we can access the value simply using:

```js
document.querySelector('[name="cardnumber"]').value
```

**Comment by jenan-stripe** [comment]
Hi @LeoAref -- that won't work (intentionally) because the inputs are hosted in an iframe served by Stripe. Please see https://stripe.com/docs/security#pci-dss-guidelines for details.

**Comment by mmarinm** [comment]
How about if I don't use stripe elements, I just want to store a card number in the state before I request token, card number still never touches my server.
Is there any security concerns about that approach?

**Comment by jenan-stripe** [comment]
@mmarinm You'll need to use either Elements or Checkout to be eligible for the simplest version of PCI compliance. Please see the linked docs for more details!
