### ISSUE TITLE
Uncaught Error: Cannot create an Element of type cardNumber after an Element of type card has already been created.

### ISSUE THREAD

**Issue by albert-olive** [stripe/react-stripe-elements#183]
Hi All,

Thanks for this great library you provided. I'm trying to create my own form but I'm having issues building it.

I'm getting this error:

`(index):1 Uncaught Error: Cannot create an Element of type cardNumber after an Element of type card has already been created.`

when building the form. This is the code:

```const PaymentComponent = () => {
  const handleSubmit = e => {
    e.preventDefault();
    ....
  };

  return (
    <form onSubmit={handleSubmit}>
      <PaymentContainer>
        <CardElement />
        <CardNumberElement />
        <CardExpiryElement />
      </PaymentContainer>
    </form>
  );
};

export default injectStripe(PaymentComponent);
```
CardElement.js

```import React from "react";
import { CardElement } from "react-stripe-elements";

const CardSection = () => {
  return (
    <label>
      Card details
      <CardElement style={{ base: { fontSize: "18px" } }} />
    </label>
  );
};

export default CardSection;
```

If I remove CardElement it works with the other two. 

Thanks in advance!

**Comment by atty-stripe** [comment]
Hi @albert-olive! The error is caused because you're trying to render two Elements that render a card number input: `card` and `cardNumber`. Did you mean to only use one of them?

**Comment by albert-olive** [comment]
Hi Atty, yes, sorry about that. Now I see that logic. Close the issue
