### ISSUE TITLE
Network request flood - opt-out from tracking?

### ISSUE THREAD

**Issue by Grsmto** [stripe/react-stripe-elements#184]
Hi,

First, I know this is related to Stripe.js and you say to not report issues about it in your issues template but as far as I know, Stripe.js is not open source so there is no way to report issues there.

So I finally finished implementing `react-stripe-elements` and I figured out that my app is now slow to load. I checked the network tab and I understood why: 
On your [example page](https://stripe.github.io/elements-examples/), there is an insane number of network requests, about **176 requests** only on page load.

Why is this happening? Is there a way to opt-out from this tracking? Is this tracking "feature" documented anywhere?

Thanks for your help.

**Comment by atty-stripe** [comment]
Hi @Grsmto! 

Our examples page contains many Elements loaded together, each of which makes a number of network requests to load various resources (HTML, JavaScript, icons, etc.) All of these should be cached, and the Chrome DevTools reports them as `(from disk cache)`. Thus, even though the total number may appear large, the true number of over-the-wire requests is small. We also make a few requests for metrics purposes, but these are plain outbound requests, and should not affect your app loading.

I would recommend looking into loading Stripe.js and Elements asynchronously and see if that resolves your issue: https://github.com/stripe/react-stripe-elements#loading-stripejs-asynchronously.

**Comment by jez** [comment]
> Stripe.js is not open source so there is no way to report issues there

In addition to what @atty-stripe mentioned about loading asynchronously, while Stripe.js is not open source, we have a whole support team who love helping people work through their integration questions! You can reach out to them at support.stripe.com or by going to `#stripe` on Freenode.
