### ISSUE TITLE
Confusion using createSource

### ISSUE THREAD

**Issue by Knaackee** [stripe/react-stripe-elements#187]
I want to implement a payment form with credit card payment or SEPA payments. 

I have successfully created a form with `<StripeProvider>`, `<Elements/>` and the `<CardElement/>`.
`this.props.stripe` is available and the card component shows up and works as expected.

Now I am confused by the docs and examples how to go on. 
Here is what I think.

IF Payment is CreditCard I `createSource` and pass in the `elementRef` from the <CardElement/>.
This throws an error `Converting circular structure to JSON`.

IF Payment is Sepa I `createSource` and pass in manually the data since there are no components yet (right?).

1. How to pass in the <CardElement/> to createSource correctly?
2. Is my workflow correct?

Thanks in advance!

**Comment by atty-stripe** [comment]
Hi @Knaackee!

For the card Element, you do not need to pass in the `elementRef` when creating a source. Within the context of Elements, we already know which Element you're trying to use. See the example here (https://github.com/stripe/react-stripe-elements#setting-up-your-payment-form-injectstripe). Just replace `createToken` with `createSource`.

For SEPA, your workflow is correct! Here's an example I posted in another issue recently: https://codesandbox.io/s/zx5350wkx3.

I would recommend taking a look at the demos and docs in this repo for reference as well. And our support team is available on #stripe on Freenode and at support@stripe.com for similar issues.
