### ISSUE TITLE
CardElement content clears after moving container

### ISSUE THREAD

**Issue by alexallenprime** [stripe/react-stripe-elements#188]
I have a tabbed checkout form, and to support a responsive design, the parent container for the CardElement may need to reposition in the DOM hierarchy when switching tabs. After doing so, all the input is cleared from the Element, which would cause frustration for the user and, in some cases, prevent checkout completion entirely. I'm not sure whether this behavior is intended or required for security reasons, but at the moment I am stuck using v2. Here is a simple JSFiddle example: https://jsfiddle.net/2snunun9/

**Comment by atty-stripe** [comment]
Hi @alexallenprime! 

The card Element is rendered within an iframe, so moving the iframe effectively removes the node and adds it again, triggering the internal page to reload. As a result the data is cleared. For your use case, we recommend showing / hiding a container of the Element if you need to toggle visibility.

Rendering and storing sensitive information within a secure iframe (in this case hosted on js.stripe.com) is required for PCI SAQ A compliance. Using Stripe.js v2 means you need to go through a higher level of PCI compliance, so we highly recommend you use Elements and Stripe.js v3. See [here](https://stripe.com/docs/security#validating-pci-compliance) for more details.
