### ISSUE TITLE
Feature request : Get CardElement in other languages

### ISSUE THREAD

**Issue by grean** [stripe/react-stripe-elements#189]
Have you plan to do this soon ?
I'd love to have the CardElement in french :) because all my site is in french and it's surprising to see "card number" when customer will pay...
I didn't saw any language options in the doc.

**Comment by grean** [comment]
Ok, i saw that in firefox the text is in french but in chrome and edge it's in english..
Bug ?

**Comment by athyuttamre** [comment]
Hey @grean! 

You can set the desired locale when creating Elements. See the locale option here: https://stripe.com/docs/stripe-js/reference#elements-create. In this case you can set it to `fr`.

In the future, please reach out to our helpful support team (https://stripe.com/contact) for integration questions. This repo is for bugs in react-stripe-elements specifically.

**Comment by athyuttamre** [comment]
As for the other browsers, Elements automatically infers the locale from the browser settings. It’s possible your Chrome locale is set to English.

**Comment by grean** [comment]
Ok i thought that all the docs was in github but in a comment inside a code exemple there is a link to the stripe doc.
Thanks for the reply :)

**Comment by atty-stripe** [comment]
Ah sorry about that! The locale option is frequently used, and is indeed mentioned in the README for this repo (https://github.com/stripe/react-stripe-elements#props-shape-1). Please let us know if there are ways we can improve the documentation in the future!

**Comment by liamtarpey** [comment]
Hi there, 

Could you please advise on how to change placeholder text for languages that are not supported? We offer our site in a number of languages, including TR, ID, KO, VI that are all missing from your supported languages list.

We don't want to show `Card number` placeholder in English for these customers but want to pass our own translations - can't find this in your documentation. Could you please help?

Thanks
