### ISSUE TITLE
<*Element> should support "required" attribute

### ISSUE THREAD

**Issue by tim-montague** [stripe/react-stripe-elements#190]
```
<form>
  <*Element required />
  <button>submit</button>
</form>
```

Stripe `<*Element>` element should support `required`,
as this is a standard attribute used in forms.

**Comment by atty-stripe** [comment]
Hi @tim-montague! Thank you for the feature request. We don't currently have this feature (and it is a little tricky to implement.) We're discussing this internally, and will share any updates here. Closing now as this issue tracker is intended for bugs / feature requests in react-stripe-elements specifically.
