### ISSUE TITLE
Feature request: Expose whether card number uses postcode

### ISSUE THREAD

**Issue by klase** [stripe/react-stripe-elements#200]
When using individual elements, it would be really useful if the "cardNumber" change event would include a property to flag whether or not the card uses postcode entry, so we can selectively hide/show it for a better user experience. If this should be directed to the core elements library feel free to move it.

Thanks

**Comment by cweiss-stripe** [comment]
Hi @klase! 

Thank you for the feedback! We currently have no plans to add this feature to the `cardNumber` Element, but I'll track your suggestion and will let you know if anything changes.
In the meantime, you can look into using the `card` Element, which automatically shows and hides the postal code field when necessary.

If you need further help, our support team is happy to help! You can reach them by email or IRC here: https://stripe.com/contact.

**Comment by klase** [comment]
We can't use the card element due to design constraints which is why it would be useful to have this exposed.
