### ISSUE TITLE
Disable PaymentRequestButtonElement

### ISSUE THREAD

**Issue by klase** [stripe/react-stripe-elements#203]
Is there a way to disable the PaymentRequestButtonElement like disabled=true on a DOM button? On my checkout screen I have both a payment request button and a stripe card form so I'd like to disable the payment request button when the user submits the standard stripe form to avoid potentially double charging if the users clicks both.

**Comment by atty-stripe** [comment]
Hi @klase!

Apple's Human Interface Guidelines for Apple Pay disallow disabling the button. [0]

Our recommendation is to use the `.on('click')` handler and call `event.preventDefault()` to prevent the payment interface from showing up. If you do this, we recommend showing an appropriate error message to the user communicating that a payment is already in progress.

Hope that helps!

[0] https://developer.apple.com/apple-pay/web-human-interface-guidelines/#presenting-apple-pay-as-a-payment-option
