### ISSUE TITLE
Server Side Rendering

### ISSUE THREAD

**Issue by theashguy** [stripe/react-stripe-elements#204]
When included in a project that uses react-dom-server (or presumably any kind of server side rendering) the lib explodes because it explicitly requires a window object to look up if Stripe has been loaded or not. This should be relatively simple to fix-- only run this code if window objects exist:

```
  68 |       throw new Error("Please pass either 'apiKey' or 'stripe' to StripeProvider, not both.");
  69 |     } else if (_this.props.apiKey) {
> 70 |       if (!window.Stripe) {
     | ^
  71 |         throw new Error("Please load Stripe.js (https://js.stripe.com/v3/) on this page to use react-stripe-elements. If Stripe.js isn't available yet (it's loading asynchronously, or you're using server-side rendering), see https://github.com/stripe/react-stripe-elements#advanced-integrations");
  72 |       } else {
  73 |         var _this$props = _this.props,
```

**WebpackError: window is not defined**

**Comment by atty-stripe** [comment]
@theashguy thanks for the report!

This is intended. Our library is designed to accommodate advanced use cases such as async loading and server side rendering, and you should handle the Stripe object manually in these cases as described in the error message. [0]

https://github.com/stripe/react-stripe-elements#advanced-integrations
