### ISSUE TITLE
3D Secure flow with react/stripe

### ISSUE THREAD

**Issue by BorisBresciani** [stripe/react-stripe-elements#215]
Hello,

In the case where the user enters a card whose 3DSecure is obligatory, I redirect the user but how do I manage the return to know if the source has passed into "chargeable" status?

My code:
```js
this.props.stripe.createSource({type: 'card',
                currency: CURRENCY,
                amount: this.props.amount * 100,
                owner: {
                    name: user.username,
                    email: user.email
                }
            }).then(response => {
                if (response.error) {
                    this.setState({messageError: response.error.message});
                } else {
                    let source = response.source;
                    if (source.card.three_d_secure === 'not_supported' &&
                        source.status === 'chargeable') {
                        // SEND TO SERVER -> CHARGE
                    } else if (source.card.three_d_secure === 'required' ||
                        source.card.three_d_secure === 'recommended' ||
                        source.card.three_d_secure === 'optional') {
                        this.props.stripe.createSource({type: 'three_d_secure',
                            currency: CURRENCY,
                            amount: this.props.amount * 100,
                            three_d_secure: {
                                card: source.id
                            },
                            redirect: {
                                return_url: window.location.href
                            },
                            owner: {
                                name: user.username,
                                email: user.email
                            }
                        }).then(response => {
                            if (response.error) {
                                this.setState({messageError: response.error.message});
                            } else {
                                let redirect = response.source.redirect;
                                // REDIRECT USER TO redirect.url
                                // CALLBACK ??
                                console.log(redirect);
                            }
                        });

                    }
                }
            });
```

Boris

**Comment by asolove-stripe** [comment]
Hi @BorisBresciani! 

(BTW, this Github repo is specifically for the React wrapper for stripe.js. Questions like this about the behavior of Stripe APIs will get answered faster if they go to [Stripe Support](https://support.stripe.com/)).

The [3DS Source integration guide](https://stripe.com/docs/sources/three-d-secure#customer-action) describes how to ensure the user is redirected back to your site after being redirect to 3DS and how to use webhooks to find out when the source becomes chargeable.

**Comment by saucey** [comment]
Hi Guy 

Did any of you figure out how to redirect back, and also were do we render the below to know whether the payment had been success or a failure:

`stripe.retrieveSource({
  id: '{SOURCE_ID}'
  client_secret: '{SOURCE_CLIENT_SECRET}',
}).then(function(result) {
  // Handle result.error or result.source
});`

**Comment by akoidan** [comment]
Any links to documentation on how to deal with stripe-3d with react-stripe-elements? This is official stripe repo, right?

**Comment by asolove-stripe** [comment]
Hi @akoidan! If you're trying to use 3DS with Stripe today, I'd recommend starting at our [3DS docs page](https://stripe.com/docs/payments/3d-secure) which links to things like our [PaymentIntent Quickstart guide](https://stripe.com/docs/payments/payment-intents/quickstart#automatic-confirmation-flow). When you get to the steps that require using Stripe.js, you can use React Stripe Elements for those bits instead of the raw Stripe.js code. We have an example of what that code might look like in our [PaymentIntent demo](https://github.com/stripe/react-stripe-elements/blob/8b5d1ffb2eaf5235193597b7d4f57349163a12ef/demo/intents/index.js).
