### ISSUE TITLE
Passing fonts to <Elements> breaks within a shadow DOM in Chrome

### ISSUE THREAD

**Issue by bcanseco** [stripe/react-stripe-elements#216]
### Environment

* Chrome v67.0.3396.87 (64bit)
* react-stripe-elements@2.0.0

### Summary

When using stripe elements within a shadow root, passing external fonts to the `<Elements>` component will result in the iframe form getting an inline `visibility: hidden` style.

![chrome_2018-06-23_14-24-42](https://user-images.githubusercontent.com/18430599/41813529-53acd4e0-76fd-11e8-85be-11971d7c3cad.png)

Even if this style is overriden, creating tokens will later throw the following error:
```
We could not retrieve data from the specified Element.
Please make sure the Element you are attempting to use is still mounted.
```

### Other information

The repro above may take a few moments to load. Notice that the fourth box will stay empty.
I'm aware that the fonts are not actually applied to the inner `<CardElement>` in the repro above.

**Comment by matt-stripe** [comment]
@bcanseco Hi! Thanks for writing in. I'm Matt and I work at Stripe. You are totally right here--Elements is currently not compatible with shadow DOM. We have this on our backlog and are looking forward to addressing it in the future (no concrete timeline at the moment unfortunately). I will be sure to let you know when the fix does roll out!

**Comment by bennypowers** [comment]
Not just Chrome, shadow dom is supported in a number of browsers. For example, firefox support is about to land.

https://caniuse.com/#feat=shadowdomv1

**Comment by bennypowers** [comment]
FYI, the way we solve this in [stripe-elements](https://github.com/bennypowers/stripe-elements/) custom element is to [walk the dom tree](https://github.com/bennypowers/stripe-elements/blob/master/stripe-elements.html#L518-L529) until we find the document.

**Comment by kaufmann42** [comment]
+1 we also really need this for our solution. As web pages become more plugin focused this is going to be important.

**Comment by redaben** [comment]
+1

**Comment by bcanseco** [comment]
For anyone considering workarounds like [tokenizing cards](https://stripe.com/docs/api/tokens/create_card) using your own CC forms on the frontend and then [capturing charges](https://stripe.com/docs/api/charges/create) from your backend:

Keep in mind that you eventually need to validate PCI compliance. **Yes, your backend never sees credit card information with this approach. HOWEVER**, since you're not using the Elements library - you will have to fill in 40 pages of PCI forms every year.

![image](https://user-images.githubusercontent.com/18430599/48867283-b3fdb180-eda3-11e8-9bd5-c510d6043deb.png)

More info on that [here](https://stripe.com/docs/security#validating-pci-compliance).

**Comment by bennypowers** [comment]
@bcanseco Thanks for that, that's more reason for stripe to support the full DOM and HTML spec, including shadow DOM. Anyone building a payment app that uses shadow DOM would LOVE to not have to fill out those forms, but unless Stripe decides to support the full DOM spec, we have to use weird workarounds like walking the whole tree.

**Comment by threeaccents** [comment]
@matt-stripe Are there any updates on the progress for shadow dom support?

**Comment by wayne-o** [comment]
Would love to know if this has been fixed - also why is it closed if it's not?

**Comment by bennypowers** [comment]
It's worth mentioning that the workaround we use in `<stripe-elements>` breaks the tab order, as well.

**Comment by wayne-o** [comment]
@bennypowers  - does it also break the PCI compliance side of things or is that ok?

**Comment by wayne-o** [comment]
@bennypowers  Mind if i port that component to svelte?

**Comment by bennypowers** [comment]
Won't break PCI, since even with my component, your users are still entering their numbers into an iframe to stripe.com.

but without proper tab order, it is inaccessible. You'll probably need some vile tabindex hacking, either that or very careful dom placement to get it to work the way you'd expect.

But i'd be happily proven wrong. all of ☝️ is based on my experience using `<stripe-elements>` inside an animated multi-step form.

**Comment by atty-stripe** [comment]
Hi folks, we don't have any updates regarding shadow DOM support yet. It should still be possible to use Elements without the shadow DOM, so hopefully you're not blocked from integrating Stripe altogether (or forced to fall back to higher levels of PCI).

We'll post here if/when we have updates on shadow DOM support.

**Comment by bathos** [comment]
There are 8 (pretty minor, fairly repetitive) things in stripe.js which I know of that prevent it from working. There may be more which just happen not to occur in the features we’re using, but still, it’s not a super big diff. I have a patched version which does work, but it will be awkward trying to maintain keeping it in sync with the stripe-hosted script. Any news here?

**Comment by hofman-stripe** [comment]
Shadow DOM causes some issues with the iframes that Stripe.js uses internally for PCI compliance. It may be possible to change Stripe.js to be compatible with Shadow DOM while preserving PCI compliance, but it's definitely more involved than 8 minor patches.

In the meantime, the only workaround is to keep all elements in the main document, doing something like @bennypowers's clever trick in [stripe-elements](https://github.com/bennypowers/stripe-elements/).

**Comment by bathos** [comment]
There’s nothing which could be considered PCI-related that I’ve encountered. The iframes are still secure (nothing can change that, really, they are controlled by stripe’s origin exclusively). It’s only a handful of incorrect assumptions about three things:

1. how to determine if an element is connected (use isConnected, not document.body.contains);
2. how to determine if an element is focused (getRootNode().activeElement, not document.activeElement)
2. how to choose the next sequentially focusable element in the tab order on blur (the most complex thing, but this is a UX level issue)

Shadow DOM does not change how iframes behave.

**Comment by hofman-stripe** [comment]
> Shadow DOM does not change how iframes behave.

It does. This is the main blocker: https://github.com/whatwg/html/pull/1625/commits/7b567729ac3cc66b074b0df53138c353ec540bb9

That means unless all iframes are in the root document, they cannot discover each other to communicate directly.

**Comment by bathos** [comment]
Apologies, I framed that wrong. I should have said it does not change their security characteristics.

I’m a bit confused now though because the script creates all of these elements and can hold references to them, and is not obviously failing anywhere.

**Comment by hofman-stripe** [comment]
While I'm not sure what your patches exactly do, you might end up creating the element iframes but they wouldn't be functioning properly. In particular I don't believe you'd be able to create a Token or PaymentMethod from a card element.

Also, a reminder that self hosting Stripe.js (especially a modified versions) is in itself not PCI compliant.

**Comment by bathos** [comment]
Why is that exactly? I should hope that _no_ script I run in my origin could compromise Stripe’s security — is that not the case?

(To be clear — I believe you of course, just looking to understand what’s going on better. This has all been a pretty frustrating experience so far.)

**Comment by danperkins** [comment]
@bathos I ran into this same problem as well.  I put together a working solution where I have an <iframe> within the shadow DOM that handles loading the Stripe script and rendering `react-stripe-element` components.  Not sure what your exact requirements are, but it seems to work reasonable well for us to get style encapsulation from the Shadow DOM and keep Stripe happy by having all of the content inside the iframe document (which does not have Shadow DOM nodes inside it)

**Comment by silenceisgolden** [comment]
@hofman-stripe @matt-stripe Would it be possible (at least in the `createToken(Element)` use case) to patch the library and the loader to maintain that state? So when a Stripe Elements iframe is loaded in the doc it could be added to a collection of iframes that is bootstrapped by the Stripe.js loader?

My thought is that this collection would replace `window.frames`, assuming that is what is being used by the Element iframes. This new collection could also, by necessity, be added to the window as well.

**Comment by hofman-stripe** [comment]
For security we cannot rely on the Stripe.js script loaded in your page to establish a communication channel between our iframes. They have to discover each other directly. Currently this is done through naming and `window.frames`, a special property of `WindowProxy` which cannot be stubbed in any way.

There are other ways to get references to other frames's `WindowProxy` objects, but these would require a fundamental refactor, not a simple patch.

Interesting read on the topic: https://medium.com/@bluepnume/every-known-way-to-get-references-to-windows-in-javascript-223778bede2d

**Comment by jonahbron** [comment]
:+1: for supporting shadow dom.  I got this working by using a slot to pull in a container from outside the shadow dom, but that was easy to do because my component sits directly inside the root DOM.
