### ISSUE TITLE
Unable to enter card information(In stripe elements) in ios mobile app.

### ISSUE THREAD

**Issue by SuryaAcube** [stripe/react-stripe-elements#217]
Feature request or idea? Consider opening an
[API review](https://github.com/stripe/react-stripe-elements/tree/master/.github/API_REVIEW.md)!

### Summary
We developed our web-application in react.We developed mobile application using Phonegap(software development framework which uses web application code).In that IOS app react-stripe-elements are not working.I am not able to enter card number,ccv,expiry and postal code.Is any one else facing same issue?

**Comment by anttikon** [comment]
@SuryaAcube I got it to work by adding `<allow-navigation href="*://js.stripe.com/*" />` to `config.xml` 🌞✌️

**Comment by SuryaAcube** [comment]
@anttikon Thank you so much.

**Comment by noufal-ark** [comment]
Thank you so much

**Comment by snblackout** [comment]
`<allow-navigation href="*://js.stripe.com/*" />`

When I do this and build the app, when opening the app on iOS, right at the splash screen, the app kicks out and opens my apps webview URL within Safari new tab.

Removing the allow-navigation, the app loads just fine but the mounting of the card doesn't seem to work as the form is blank and I cannot focus in it to type.  Working fine on dev machine on Firefox.

Any ideas?

**Comment by snblackout** [comment]
FYI after some inspection, I did not have `<allow-navigation href="*://localhost/*" />` in my config initially, so adding in `<allow-navigation href="*://js.stripe.com/*" />` to config immediately blacklisted everything else, including localhost, so it would kick it out to Safari browser.

Also, Stripe elements load just fine now after this too.
