### ISSUE TITLE
Ids containing invalid chars cause error

### ISSUE THREAD

**Issue by rubencosta** [stripe/react-stripe-elements#218]
### Summary

https://codesandbox.io/s/5x080mo714

Passing an `id` prop with a `.` causes Elements to make a querySelector using that id without escaping it. According to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector#Notes) some chars have to be escaped when used as selectors. 

### Other information

I raised this issue first in the IRC and it was recommended to me by karlleko that I should open the issue here. 

For now I can work around this issue by escaping the id in my code but as a user I didn't expect having to do this since what I am passing is an `id` and ids should accept `.` without escaping.

**Comment by cweiss-stripe** [comment]
Hi @rubencosta 

This seems to have been an issue that was fixed recently.
Your provided example seems to work fine.

Please reopen this issue if you still see unexpected behavior.
