### ISSUE TITLE
Form submission after token creation

### ISSUE THREAD

**Issue by hundsim** [stripe/react-stripe-elements#22]
We're preventing form submission with `ev.preventDefault();` to not refresh the page before we get the token from Stripe.

I'm stumbling a bit on how to subsequently (programmatically?) submit the form to our server with all values (including the token) after the Stripe response?

**Comment by michelle** [comment]
You can select the form element and manually trigger a submit on it after you get the token: https://stripe.com/docs/elements#submit-token

Feel free to reopen if this does not answer your question.
