### ISSUE TITLE
Stripe js v3 doesn't load with AdBlock

### ISSUE THREAD

**Issue by trip16661** [stripe/react-stripe-elements#222]
I am developing a simple React app with SSR, and have found that Stripe.js doesn't load while AdBlock is enabled. Please have a look at the below:

**Console when AdBlock is turned off**
<img width="484" alt="screen shot 2018-07-13 at 2 58 10 am" src="https://user-images.githubusercontent.com/17633551/42675261-a2b9dc62-8649-11e8-92cc-9133ba2cc32c.png">

**Console when AdBlock is turned on**
<img width="484" alt="screen shot 2018-07-13 at 2 58 35 am" src="https://user-images.githubusercontent.com/17633551/42675275-afd98ece-8649-11e8-900c-55a9c369972f.png">

**Request headers when AdBlock is turned on**
<img width="657" alt="screen shot 2018-07-13 at 2 59 00 am" src="https://user-images.githubusercontent.com/17633551/42675289-bdb2240c-8649-11e8-90ed-24fe31cd7ee9.png">

I'm currently using AdBlock with Chrome.

Not sure if this is the best place to raise this issue or if I should actually be raising it with AdBlock. In any case it's such a common extension that I can't imagine this not being an issue for a large group of users. I haven't tried this out in live mode yet, but I assume the issue may be there still.

I will carry on with development with AdBlock turned off but it would be great to hear back on this. I searched everywhere and didn't come up with anything, hard to believe I'm the only one coming against this but if I'm doing something wrong please let me know!

**Comment by asolove-stripe** [comment]
Hey @trip16661, thanks for reporting this!

I have AdBlock turned on in Chrome for Mac, and stripe.js seems to work on several sites that I tried, for example our [elements examples page](https://stripe.github.io/elements-examples/). And when I went to a site with ads blocked by AdBlock, I saw the console error listed as `Failed to load resource: net::ERR_BLOCKED_BY_CLIENT` which looks different from the one you're seeing.

That said, obviously something is going on with AdBlock and I'd love to fix it. Can you help me figure out how to reproduce?
- Is there a public url I can go to where it breaks for you?
- Or could you go to the elements examples page and see if it's also broken for you?
- Have you changed any of the AdBlock options from their defaults?

**Comment by trip16661** [comment]
@asolove-stripe 

Ummm now that you link that site, I tried to use adblock and check it and the same error appears. 

<img width="453" alt="screen shot 2018-07-17 at 1 30 16 pm" src="https://user-images.githubusercontent.com/17633551/42832022-5284d622-89c6-11e8-8d6b-707ebbedda43.png">

I don't have additional config in adblock but mine looks like: 

 
<img width="842" alt="screen shot 2018-07-17 at 1 34 34 pm" src="https://user-images.githubusercontent.com/17633551/42832121-9f4cf228-89c6-11e8-91e0-273cf4f71916.png">

**Comment by trip16661** [comment]
@asolove-stripe Version 3.32.0

Now that I review the site again, I discovered that the bug occurs only when it's your first time on the page. Once you reload again it just works normally.

For example, go to the stripe elements demo page, hard reload, the errors happen.
Now do a normal reload, the error doesn't happen anymore. 

I tried this repro on my local environment as well and it was exactly the same.

**Comment by asolove-stripe** [comment]
Hmm, I tried this on a couple computers and did not see the problem even with a hard reload.

The hunt continues...

**Comment by susannepeng** [comment]
Hey guys, just jumping in, I'm seeing the same results as described by @trip16661 on the Stripe Elements example page.

My version of AdBlock: 3.31.2
My version of Chrome: 67.0.3396.99

**Comment by michelle** [comment]
I just installed Adblock@3.32 on Chrome@67.0.3396.99 with these options and am not seeing the issue:

<img width="826" alt="screen shot 2018-07-26 at 1 39 43 pm" src="https://user-images.githubusercontent.com/928757/43287263-64a3dde8-90d9-11e8-970b-023c07113032.png">

I'm going to go ahead and submit a bug report to AdBlock to see what they say.

**Comment by michelle** [comment]
Here it is: https://help.getadblock.com/public/tickets/ae70e2a777101a58482af726979c89fae2c80ea497b33055397aab2a875213a5

**Comment by atty-stripe** [comment]
With the latest versions of Chrome and Adblock Plus, we're unable to reproduce this error. It also doesn't seem to impede functionality of Elements.

Please let us know if you see this again in newer versions, and we can reopen.

**Comment by michelle** [comment]
Just to close the loop here, Adblock folks got back to us on the ticket: https://help.getadblock.com/public/tickets/ae70e2a777101a58482af726979c89fae2c80ea497b33055397aab2a875213a5

>The error you were seeing wasn't related to Stripe.js. It was a minor bug in an unrelated process that, while annoying, didn't cause any actual trouble. And good news, it's been fixed.

**Comment by 4sh3** [comment]
Hi, Adblock is blocking stripe right now...

  <script src="https://js.stripe.com/v3/"></script>

**Comment by atty-stripe** [comment]
Hi @4sh3, I cannot reproduce myself on latest Chrome with the latest version of AdBlock. Can you share your Chrome / AdBlock versions and a screenshot of which requests you see getting blocked? Is core payments functionality affected?

**Comment by MaffooBristol** [comment]
Just as a sidenote, I'm using uBlock Origin and I get a load of these errors, but the functionality still seems to work fine

**Comment by JohnnyLin-a** [comment]
I'm running Nano defender for adblocking and that is the culprit. Once I disabled it, the stripe elements were visible again. I know the last comment is almost 1 year old but it's still something that still happens.

**Comment by daprezjer** [comment]
@JohnnyLin-a , any luck? I'm having the same problem w/ my Laravel project, but with AdBlockPlus.

![image](https://user-images.githubusercontent.com/1242929/88619925-89bcc680-d051-11ea-96aa-faac9e99fc49.png)

**Comment by asolove-stripe** [comment]
@daprezjer could you maybe share logs from earlier in the session? All the things being blocked in that screenshot are logging, which should not block Stripe.js from working. I assume something is blocking a previous part of Stripe.js if it actually isn't working.

**Comment by daprezjer** [comment]
Appreciate it @asolove-stripe .  I was in mid-development and just assumed all the blocked resources mean that Stripe wouldn't work.  But you're correct, it does work fine even with the errors.  If it isn't too difficult, can you explain what's being logged, aka what folks who have this turned on are missing out on?

**Comment by asolove-stripe** [comment]
@daprezjer you're not missing out on anything, other than being counted in our telemetry to detect if anything is broken. We get enough non-Adblock users that this isn't a problem.
