### ISSUE TITLE
createToken method returns token as undefined if 'pk_test_XXX' is invalid key.

### ISSUE THREAD

**Issue by vishalkharat** [stripe/react-stripe-elements#223]
Feature request or idea? Consider opening an
[API review](https://github.com/stripe/react-stripe-elements/tree/master/.github/API_REVIEW.md)!

When we tried to generate the Token using wrong key, createToken method returns result set as `undefined`.

### Summary

createToken should return an error code along with error message so that application can track it and handle it.
Otherwise for all error conditions it needs to be handled based on `undefined` check.

### Other information
```
this.props.stripe
          .createToken()
          .then(({ token }) => {
            console.log('Received Stripe token:', token);
            dispatch(resetLoading());
            if (token) {
              // Do something with token.
            } else {
              showWarning(dispatch, 'Stripe Token Error', 'Error in generating stripe token. Please contact administrator.');
            }
          });
```
[Errors mentioned as ](https://stripe.com/docs/api#errors)

**Comment by asolove-stripe** [comment]
Hi @vishalkharat! The [`createToken` method](https://stripe.com/docs/stripe-js/reference#stripe-create-token) returns a promise that will be resolved with either a `token` property or an `error` property. You will probably want to change your code to also look for the `error` property and branch based on whether or not it is set.
