### ISSUE TITLE
Using unescaped '#' characters in a data URI body is deprecated

### ISSUE THREAD

**Issue by 0xd5** [stripe/react-stripe-elements#229]
### Summary

As far as I can tell using the Stripe provider inserts 3 iframes into the DOM for a React app. Calling the following paths (full path excluded for berevity):

- js.stripe.com/v3/controller-...
- js.stripe.com/v2/m/outer.html...
- m.stripe.network/inner.html...

These paths are currently triggering the following warning in Chrome:

[Deprecation] Using unescaped '#' characters in a data URI body is deprecated and will be removed in M68, around July 2018. Please use '%23' instead. See https://www.chromestatus.com/features/5656049583390720 for more details.

### Other information

This seems to be a Chrome specific issue. Exact platform: chrome 67.0.3396 Windows 10

**Comment by atty-stripe** [comment]
Thanks for the issue, @0xd5! I'll take a look today.

**Comment by 0xd5** [comment]
Looks like a simple fix, but I'm not familiar with the project. Happy to contribute with some guidance.

**Comment by jez** [comment]
This is unfortunately not a simple fix; the issue originates deep within Stripe.js, which is the closed-source library wrapped by react-stripe-elements.

Thanks for the enthusiasm, though! We love to see people eager to make react-stripe-elements better.

**Comment by asolove-stripe** [comment]
Quick update: this change was pushed back to Chrome M71, in December. But we should still fix asap, looking now.

**Comment by asolove-stripe** [comment]
Hey @0xd5, are you still seeing this? I went through several demos and live integrations and was unable to find any cases where we used a data URI with a literal `#` in it. If you have a way to reproduce, would love to take a look.

**Comment by 0xd5** [comment]
Hi Adam,

Will check this out tomorrow and report back to you either way

**Comment by 0xd5** [comment]
I can confirm I no longer see this issue. These are the two instances of the iframe I could find rendered in my latest build.

```html
<iframe frameborder="0" allowtransparency="true" scrolling="no" name="__privateStripeController0" allowpaymentrequest="true" src="https://js.stripe.com/v3/controller-1dfabed22ec73a1dc5d8834f381d776e.html#apiKey=xxxxxxxxxx&amp;stripeJsId=ecc8362e-0503-4a3a-84d7-b69e7c5226b4&amp;origin=xxxxxxxxxx&amp;referrer=xxxxxxxxxx&amp;controllerId=__privateStripeController0" aria-hidden="true" tabindex="-1" style="border: none !important; margin: 0px !important; padding: 0px !important; width: 1px !important; min-width: 100% !important; overflow: hidden !important; display: block !important; visibility: hidden !important; position: fixed !important; height: 1px !important; pointer-events: none !important;"></iframe>
```

```html

<iframe frameborder="0" allowtransparency="true" scrolling="no" name="__privateStripeMetricsController1" allowpaymentrequest="true" src="https://js.stripe.com/v2/m/outer.html#url=xxxxxxxxxx&amp;title=upUgo%20SEO&amp;referrer=&amp;muid=31c5f7a7-9518-40b5-acd3-815bdb2a7c77&amp;sid=708969d3-8d16-49c5-ac06-7804a16ce193&amp;preview=false" aria-hidden="true" tabindex="-1" style="border: none !important; margin: 0px !important; padding: 0px !important; width: 1px !important; min-width: 100% !important; overflow: hidden !important; display: block !important; visibility: hidden !important; position: fixed !important; height: 1px !important; pointer-events: none !important;"></iframe>
```

Thanks for looking into this, not sure what happened to fix it. I'll re-open if it appears.
