### ISSUE TITLE
Restore elementRef

### ISSUE THREAD

**Issue by schemata-nick** [stripe/react-stripe-elements#230]
In the last push my integration stopped working. After checking the code/release it's because the elementRef property was removed in this commit:

https://github.com/stripe/react-stripe-elements/pull/210

My use case is that I'm passing my own stripe instance into the StripeProvider, and generating a token using createToken

Not looking for a fancy forms library, merely a secure credit card input, and Elements seems to be the only pathway to that with Stripe. I have my own 'Pay' button so that it can be styled, debounced, hidden with 'processing' message, etc

It's ok to use onReady (or onChange) to validate when the user is ready to pay, but when they click the pay button I need to be able to use Stripe.createToken(cardRef). It needs to be done on click as the tokens quickly go stale, so it's best to generate one the moment the user decides to pay rather than earlier

The onReady function isn't actually a duplicate on elementRef, it's a duplicate of onChange, as the ready information is already found in the change.complete boolean attribute. Could onReady be removed instead if one is going to?

Appreciate the work of creating this clean wrapper which is why I migrated over to it. I'll revert to 1.* release and will have to migrate back to the raw stripe elements library if this isn't where you're going with it

Thanks

**Comment by jez** [comment]
> It's ok to use onReady (or onChange) to validate when the user is ready to pay

This is not what `onReady` means in the context of Elements.
If you look at the original diff where we deprecated `elementRef`:

https://github.com/stripe/react-stripe-elements/pull/181/files#diff-e15bc710cb3c63ba986143c9ecbe354bL107

You can see that in that entire file, there was only one `elementRef` callsite and one `onReady` callsite, and the latter was always called immediately after the former.

The `onChange` fires when it's possible that their payment information is complete, but it does not fire when you should actually create the token.

For all intents and purposes, `elementRef` and `onReady` are exactly the same; you can fix your integration after upgrading by replacing the first with the second unconditionally.

If you need further help with your integration, you should reach out to our support team! Head over to support.stripe.com or visit us on IRC in #stripe on Freenode, and we'll be happy to walk through any problems that come up.
