### ISSUE TITLE
Fonts are pixelated

### ISSUE THREAD

**Issue by nuthinking** [stripe/react-stripe-elements#240]
I am trying to add a custom element to the form, since such element is not provided, and I am struggling to match the style.

![screen shot 2018-09-03 at 22 21 37](https://user-images.githubusercontent.com/163635/45000753-e29b9580-afc7-11e8-839c-1ec30d3d0906.png)

The input above is clearly a CardElement, the one below is a simple input with the same font assigned.

As you can see the font results pixelated. Consequentially also the font weight looks different.

**Comment by atty-stripe** [comment]
Hi @nuthinking! Thanks for reporting this issue.

Do you have a link to a minimal reproduction of your implementation (perhaps using a code-sharing site like jsfiddle)? Can you also share:

- Your browser and OS versions
- Your exact config that you're using to set up Elements (what fonts and CSS you're passing)

Happy to help debug here. For future reference, this issue tracker is limited to issues with the React wrapper for Elements alone. For Elements bugs / support, please feel free to get in touch with our support team at https://support.stripe.com/.

**Comment by nuthinking** [comment]
On my latest MacOS and Chrome the problem happens also with your JSFiddle example. Just less noticeable. I reported it via email. Thanks!
