### ISSUE TITLE
Throw a clearer error if multiple Elements components are nested

### ISSUE THREAD

**Issue by johnstonmatt** [stripe/react-stripe-elements#241]
### Summary

I am using Next.js (SSR framework), and through separate source files, I was wrapping my CardElement in multiple Element tags. This threw 'token cannot be inferred' or 'you did not declare token type'. I think that it should be more clear that what is passes into createToken is arbitrary. Also, an error message about encapsulation of Elements would be a nice touch.

**Comment by atty-stripe** [comment]
Hi @johnstonmatt, thanks for reporting this issue.

Do you have a minimal reproduction of your setup (in particular the way you're nesting the components)?

The error you're seeing is an internal react-stripe-elements error being thrown, and is ideally never shown to integrators. We would want to wrap it in a nicer error about encapsulation as you suggest.

**Comment by asolove-stripe** [comment]
Hey @johnstonmatt, can you tell us more about why you were nesting `Elements` components? That's not something that we expect, but would love to hear more about what you wanted to do and how we can clear up docs or provide better errors to deal with this.

**Comment by johnstonmatt** [comment]
It was a complete accident, I had used the component in a parent component and the child, the only problem here is the error message did not reflect what I had done and instead threw errors provided in the summary at the top of this thread.

**Comment by asolove-stripe** [comment]
Ok great, that makes total sense, and we should definitely throw a clearer error there.

**Comment by sashko-stripe** [comment]
Closing this as it's a relatively old issue and this project has migrated to [React Stripe.js](https://github.com/stripe/react-stripe-js). If you believe this is still important, please re-open it there.
