### ISSUE TITLE
American express CVC

### ISSUE THREAD

**Issue by dalefrancis88** [stripe/react-stripe-elements#242]
**Summary**
American express is only meant to have a 4 char cvc, this allows a 3 char cvc to be entered

**Steps to reproduce**

1. Run this project's demo (yarn demo)
2. Open the demo (http://localhost:8080/)
3. Copy the American Express test card number (378282246310005)
4. Paste it into the card number field (CTRL+C then CTRL+V)
5. Observe that the American Express CVC allows for a 3 digit cvc

This is invalid

**Comment by atty-stripe** [comment]
Hey @dalefrancis88! While Amex cards generally have 4 digit CVCs, we've seen cases where 3 digits are accepted or expected as well. For this reason, we allow both 3 or 4 digit CVCs for Amex cards.

Hope that helps!

**Comment by dalefrancis88** [comment]
Yeah it does, thanks for letting me know.
