### ISSUE TITLE
Apple Pay Button

### ISSUE THREAD

**Issue by maksimtarhunakau** [stripe/react-stripe-elements#243]
Hello! Could you please help me? How I can full customize apple pay button, for example change border color?

**Comment by fred-stripe** [comment]
Hi there, great question! [Apple's official branding guidance](https://developer.apple.com/design/human-interface-guidelines/apple-pay/buttons-and-marks/buttons/) on Apple Pay buttons allows for only a couple areas of customization:

- theme: light or dark
- button text: "pay" or "donate"

As such, the paymentRequestButton element only allows [customization along those lines](https://stripe.com/docs/stripe-js/reference#element-options). As an example, here's a light-themed donation button element with a light-colored outline:

```js
  var paymentRequestElement = elements.create("paymentRequestButton", {
    paymentRequest: paymentRequest,
    style: {
      paymentRequestButton: {
        type: "donate",
        theme: "light-outline",
      }
    }
  });
```

Hopefully that will help you find a button appearance that harmonizes with the rest of your page! You may also be able to customize the element further by applying styles to the element on your page where you mount the paymentRequestButton element.
