### ISSUE TITLE
Stripe fields allow infinite input when clearing the field by highlighting all contents

### ISSUE THREAD

**Issue by msweett** [stripe/react-stripe-elements#252]
### Reproduction
Input values into a Stripe field, highlight all values then press backspace to clear. The user will now be able to enter infinite values with the cursor staying at the beginning of the field.

### Summary
This issue applies to all Stripe fields. It is triggered by clearing the field by highlighting all field contents and either inputting new values or pressing backspace/delete. Once the fields maximum character input is reached, the new values overwrite the existing.

Focusing on another element will fix this issue.

Can be reproduced in the demo jfiddle: https://jsfiddle.net/attystripe/xux7qzch/

**Comment by fred-stripe** [comment]
Hi @msweett, sorry to hear this isn't working as expected. I just tried to reproduce this behavior in two different browsers (Desktop Chrome and Safari) and I'm not seeing the contents get overwritten as you described. Could you share your specific platform and browser version, and also let me know the results of testing in an incognito or private browsing window in that browser?

**Comment by msweett** [comment]
Hi @fred-stripe, I am using a mac (OS v. 10.13.5) and have been seeing this issue on Chrome (Version 69.0.3497.100 Official Build 64-bit) in both in normal and incognito mode.

This doesn't seem to be an issue on FireFox or Safari.

**Comment by fred-stripe** [comment]
Thanks for the details @msweett! It seems that I'm on a slightly different version of Chrome (69.0.3497.92), but my colleague was able to reproduce on the version you mentioned. Interestingly this does *not* happen with Chrome Canary. Will test further and let you know what we find!

**Comment by fred-stripe** [comment]
Hey @msweett, sorry to keep you waiting on a reply! We did some extensive testing and we could _sometimes_ reproduce this issue in Chrome 69.0.3497.100. Based on our testing this issue doesn't happen at all in Chrome Canary so we believe this has already been addressed by the Chrome team. If you have further concerns please let us know!
