### ISSUE TITLE
createSource not working without passing element

### ISSUE THREAD

**Issue by nonken** [stripe/react-stripe-elements#253]
### Summary

Since `2.0.0` a call to `createSource` without passing the element within the HOC component fails with `Invalid Source type passed to createSource. Expected string, got undefined.`

Looking at the source of the wrapper I see the following

```
var options = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : {};

          if (options && (typeof options === 'undefined' ? 'undefined' : _typeof(options)) === 'object') {
            if (typeof options.type !== 'string') {
              throw new Error('Invalid Source type passed to createSource. Expected string, got ' + _typeof(options.type) + '.');
            }
```
When the function is called without args, options defaults to `{}`. `options.type` therefor is `undefined` so the call throws.

**Comment by atty-stripe** [comment]
Hi @nonken, thanks for the issue! This is expected behavior, and is explicitly a breaking change in 2.0. You must pass in a `type` when calling `createSource` unless an Element is specified.

See our release notes for reference: https://github.com/stripe/react-stripe-elements/releases/tag/v2.0.0

**Comment by nonken** [comment]
Thanks a lot, I think the docs thew me off:

```
onCompleteCheckout() {
    this.props.stripe.createSource().then(/* ... */);
  }
```

**Comment by atty-stripe** [comment]
Sorry about that! We've updated the docs.
