### ISSUE TITLE
Ghostery adblocker seems to block Stripe API

### ISSUE THREAD

**Issue by Nguma** [stripe/react-stripe-elements#256]
With Ghostery Chrome adblocker enabled, I was not able to trigger the Stripe API. 

Here is what the console showed:
![screen shot 2018-10-08 at 10 11 57 am](https://user-images.githubusercontent.com/12621/46617498-e2247c00-caea-11e8-88e5-543cbfa11474.png)

**Comment by asolove-stripe** [comment]
Hi @Nguma! This appears to be an issue with Stripe.js, the closed-source library, rather than with this open source react-stripe-elements wrapper library. I would recommend contacting [Stripe Support](https://support.stripe.com/).

**Comment by sambokai** [comment]
It seems like these guys (https://github.com/stripe/react-stripe-elements/issues/222) contacted the AdBlock team, which in turn removed the block. 

We should do the same for uBlock Origin and Ghostery (https://github.com/stripe/react-stripe-elements/issues/256).

_Originally posted by @sambokai in https://github.com/richnologies/ngx-stripe/issues/53#issuecomment-458514409_

**Comment by atty-stripe** [comment]
@sambokai please feel free to open a new issue if you're seeing problems with a different adblocker. I just downloaded uBlock Origin in latest Chrome, and was not able to reproduce the issue on https://stripe.github.io/elements-examples/.

**Comment by sambokai** [comment]
I just verified this by doing a fresh install of chrome without any extensions and then with uBlock Origin and got the same result:

<img width="1672" alt="bildschirmfoto 2019-01-29 um 18 52 35" src="https://user-images.githubusercontent.com/7689616/51928894-3e434100-23f7-11e9-9160-90716542359e.png">

Will open a new issue.
