### ISSUE TITLE
Iframe send request to https://m.stripe.com/

### ISSUE THREAD

**Issue by Thebarda** [stripe/react-stripe-elements#257]
Hello there,

Stripe iframes send requests to `https://m.stripe.com/ even if `StripeProvider` is unmounted.

Here is a request : 
![screenshot from 2018-10-08 17-37-19](https://user-images.githubusercontent.com/12515407/46618850-d6ec4300-cb20-11e8-9f68-07e53aa63e9a.png)

I have one request like that each time I nativgate to another page of my project.

### Step to reproduce

1. I navigate to a page that mount `StripeProvider`. It add two iframes at the end of the DOM
2. Then I go to another page on my project that does not mount `StripeProvider`. The iframes are still there and requests to `https://m.stripe.com/` also still cotinue 

What are these requests used for ?
How could I prevent them ?

Thanks :)

**Comment by asolove-stripe** [comment]
Hi @Thebarda! This is a behavior controlled by the closed-source Stripe.js library itself rather than this open source react-stripe-elements library. I would suggest contacting [Stripe Support](https://support.stripe.com/).

**Comment by Thebarda** [comment]
Thank you @asolove-stripe for your quick answer

**Comment by Hongdeshuai** [comment]
Thank you.

**Comment by 3nvi** [comment]
This is closed but the issue is still present even a year later. Since this error leaks to the current open-source library and since the community is not allowed to help with it (since it can't contribute to closed-source code), is there a chance that we can get an update on that?

**Comment by astomusic** [comment]
so do I, it is still working. let me know how can I prevent it.
