### ISSUE TITLE
Surface errors when using individual components such as CardNumberElement or CardCVCElement?

### ISSUE THREAD

**Issue by chrismanderson** [stripe/react-stripe-elements#259]
It's entirely possibly I'm missing something, and I'm fairly new to React as well, but how do I show an error on an individual card field, like on Example #2 of https://stripe.github.io/elements-examples/.

![image](https://user-images.githubusercontent.com/418258/46765678-9bcb4a80-ccad-11e8-85bf-4610dae06fe1.png)

I saw some other Github issues with this question (e.g. https://github.com/stripe/react-stripe-elements/issues/231) but I never found a solution. 

If for example, I am following the SplitForm demo code (https://github.com/stripe/react-stripe-elements/blob/master/demo/demo/index.js#L91), submit a CC form with no number present, I get back 

`[Log] [token] – {error: {code: "incomplete_number", type: "validation_error", message: "Your card number is incomplete."}}`

How do I then set the card number field to an error state, and show that message?

**Comment by asolove-stripe** [comment]
Hi @chrismanderson: you can see the source of those demos if it helps! For example, the styling of fields when in an invalid state [is in the styles passed in when the element is created](https://github.com/stripe/elements-examples/blob/master/js/example1.js#L34).

**Comment by chrismanderson** [comment]
Hello, I did look at the source of those demos. It was super useful for the non-react version, but I'm looking at switching over to the React way and wasn't sure how it would translate. E.g. if I have a component that is 

```
const createOptions = (fontSize: string) => {
  return {
    style: {
      base: {
        fontSize,
        color: '#424770',
        letterSpacing: '0.025em',
        fontFamily: 'Source Code Pro, monospace',
        '::placeholder': {
          color: '#aab7c4',
        },
      },
      invalid: {
        color: '#9e2146',
      },
    },
  };
};


class CreditCardForm extends Component {
  constructor(props) {
    super(props);
    console.log(this.submit);
  }

  handleSubmit = ev => {
    ev.preventDefault();
    if (this.props.stripe) {
      this.props.stripe
        .createToken()
        .then(payload => console.log('[token]', payload));
    } else {
      console.log("Stripe.js hasn't loaded yet.");
    }
  };

  render() {
    return (
      <div className="checkout">
        <form onSubmit={this.handleSubmit}>
        <label className="display--Block">
          Card number
          <CardNumberElement
            onBlur={handleBlur}
            onChange={handleChange}
            onFocus={handleFocus}
            onReady={handleReady}
            {...createOptions(this.props.fontSize)}
          />
        </label>
        <label className="display--Block">
          Expiration date
          <CardExpiryElement
            onBlur={handleBlur}
            onChange={handleChange}
            onFocus={handleFocus}
            onReady={handleReady}
            {...createOptions(this.props.fontSize)}
          />
        </label>
        <label className="display--Block">
          CVC
          <CardCVCElement
            onBlur={handleBlur}
            onChange={handleChange}
            onFocus={handleFocus}
            onReady={handleReady}
            {...createOptions(this.props.fontSize)}
          />
        </label>
        <label className="display--Block">
          Postal code
          <PostalCodeElement
            onBlur={handleBlur}
            onChange={handleChange}
            onFocus={handleFocus}
            onReady={handleReady}
            {...createOptions(this.props.fontSize)}
          />
        </label>
        <button>Pay</button>
      </form>
      </div>
    )
  }
}
```

How would I trigger the invalid state on the relevant `Element`? Happy to ask elsewhere if there's a better spot for these questions, and also happy to submit a PR for the demo code in this repo to update with the error messages once I learn how to do them (I would imagine virtually everyone implementing these components will leverage the invalid states as well.)

**Comment by asolove-stripe** [comment]
You don't need to trigger the invalid state on the `Element`. It does so automatically. 

For example, [on our demo jsfiddle](https://jsfiddle.net/attystripe/xux7qzch), try entering card number "111", expiry "1", and a CVV of "1". Notice that the text changes to red as you blur each input because it is invalid.

**Comment by chrismanderson** [comment]
Ah so I did see that, which is great. What I was looking for is triggering invalid state on an individual component if an invalid entry comes back from the server call. But now looking at the https://stripe.github.io/elements-examples/, I swear I could trigger individual elements (say the CVC field) to show invalid state after submitting a token with a test card that would trigger a failed CVC error). But of course, now I'm not seeing that functionality. Will keep poking around, thanks for the information!

**Comment by atty-stripe** [comment]
Going to close as it seems you've found a solution. Elements does not allow manually setting the invalid state. You can of course set it on the container div based on your API's response.
