### ISSUE TITLE
How to reset/clear the Element

### ISSUE THREAD

**Issue by nawang-maya** [stripe/react-stripe-elements#26]
After I get a token, I'd like to reset the Element fields, making it ready to add another card. in Stripe docs, there is an element.clear method(https://stripe.com/docs/stripe.js#other-methods), can I use it here, if yes, how to use it?

**Comment by michelle** [comment]
Yep! Because React components are declarative, you'll need to get a reference to the Element instance (called "refs" in React) in order to clear it.

```jsx
<CardElement elementRef={(c) => this._element = c} />
```

and then in your handler where you want to clear the Element:

```js
handleClear = () => {
   this._element.clear();
}
```

**Comment by michelle** [comment]
Closing this out, but let me know if that doesn't work for you!

**Comment by nawang-maya** [comment]
That works, thanks!

**Comment by mizoguche** [comment]
`elementRef` seems deprecated in #181 and removed in #210

**Comment by MikaelConecto** [comment]
Nothing works for me

`onReady={this.cardElement} // with  this.cardElement = React.createRef(); in constructor`
`onReady={(c) => this._element = c}`

`elementRef={this.cardElement} // with  this.cardElement = React.createRef(); in constructor`
`elementRef={(c) => this._element = c}`

**Comment by jeffski** [comment]
How would you achieve this using React Hooks?

**Comment by rolandszpond** [comment]
> How would you achieve this using React Hooks?

I got it to work by using useState and not useRef

`function SomeComponent() {
    const [ ref, setRef ] = useState(null)

    function someEvent() {
        ref.clear()
    }

    return (
        <CardElement
            onReady={e => setRef(e)}
        />
    )
}`

**Comment by ZachMilne** [comment]
I think the best way to clear the contents is to use Stripe's "useElements" hook

```javascript
import {useStripe, useElements, CardElement} from '@stripe/react-stripe-js'

function MyComponent() {

  const stripe = useString();
  const elements = useElements();

  const handleSubmit = async (e) => {
    ...
    
    const cardElement = elements.getElement(CardElement);

    ...

    //Clear the contents of the CardElement
    cardElement.clear()

    ...

  }

  return (
    <CardElement />
  )
}
```

**Comment by nishant-k-290195** [comment]
const handleSubmit = (e) => {
    e.preventDefault();
    elements.getElement(CardElement).clear();

   //**Or, If you are using the Split payment form you have to clear each element individually.**

     elements.getElement(CardNumberElement).clear();
     elements.getElement(CardExpiryElement).clear();
     elements.getElement(CardCvcElement).clear();
}
