### ISSUE TITLE
Refactor documentation example

### ISSUE THREAD

**Issue by leotm** [stripe/react-stripe-elements#263]
Just wanting to update [Step 2: Create the payment form component](https://stripe.com/docs/recipes/elements-react#create-form) example to ES6:

```
import React, {Component} from 'react';
import {CardElement, injectStripe} from 'react-stripe-elements';

class CheckoutForm extends Component {
  constructor(props) {
    super(props);
  }

  submit = async ev => {
    // User clicked submit
  }

  render() {
    return (
      <div className="checkout">
        <p>Would you like to complete the purchase?</p>
        <CardElement />
        <button onClick={this.submit}>Send</button>
      </div>
    );
  }
}

export default injectStripe(CheckoutForm);
```

Cheers

**Comment by cweiss-stripe** [comment]
Hi @leotm thanks for the proposal!
Unlike the other modern JavaScript features used in the example, I think class field declarations are still a [stage 3 proposal](https://github.com/tc39/proposal-class-fields) and many people might not be using the [babel polyfill](https://babeljs.io/docs/en/next/babel-plugin-proposal-class-properties.html) for it. Thus, I'd prefer to hold off for a little longer before changing the examples.
