### ISSUE TITLE
CardNumberElement and CardExpiryElement star display data mirrored

### ISSUE THREAD

**Issue by eugenkr** [stripe/react-stripe-elements#265]
Enter some data, for instance `2121 2121 2121 2121` to **CardNumberElement** than select it, cursor is positioned at the beginning. Start typing the same number. You will see that the number will become mirrored `1212 1212 1212 1212`:
![mirror input](https://user-images.githubusercontent.com/294662/47155523-998c7000-d2ed-11e8-9b31-69b4b8b6b05b.gif)
Reproducible in Chrome 69 (Mac OS and Window 10) and on your demo page https://jsfiddle.net/attystripe/xux7qzch/

Related issue https://stackoverflow.com/questions/52608566/selenium-send-keys-incorrect-order-in-stripe-credit-card-input/52617894

**Comment by atty-stripe** [comment]
Hi @eugenkr, thanks for the report! We tried reproducing it, but could not do so reliably. The issue also seemed fix in the latest version of Chrome. Please reopen if you're still seeing it and it is causing issues with your integration.

**Comment by frabcus** [comment]
In case anyone needs to know, this happens in Chrome 69 but not in Chrome 70.
