### ISSUE TITLE
Keyboard won't close on iOS app

### ISSUE THREAD

**Issue by GrenardAntoine** [stripe/react-stripe-elements#266]
I have developed an ionic app and include Stripe payment on it. When I make a payment with ios phone it opens a numeric keyboard in order for me to enter the card information.

But this keyboard have no "enter" button and when I click outside of the keyboard it doesn't close.

I don't know what to do

html :
<ion-content>  
  <form>

    [...]

    <div id="payment">
      <h1>Paiement</h1>
      <button id="stripe-button" class="bigButton" (click)="openStripePayment()">Payer par carte</button>
    </div>

  </form>
</ion-content>

ts : 

```
handler: any = null;

ionViewDidLoad() {
  this.handler = StripeCheckout.configure({
      [...]
    })
}

openStripePayment(){
  this.handler.open({
    name: '...',
    description: '...',
    currency: 'eur',
    amount: ...
  });
}
```

**Comment by atty-stripe** [comment]
Hi @GrenardAntoine, sorry for the late response here. Could you post a link to a minimal reproduction that we can test on our devices? Without it, it's hard for us to reproduce the bug and fix it. Please also include the device and OS versions.

**Comment by asolove-stripe** [comment]
It looks like you are using Stripe.js and Stripe Checkout. This repo is specifically for using the React wrapper for Stripe Elements. If you're having trouble with Checkout, please contact [Stripe Support](https://support.stripe.com/).
