### ISSUE TITLE
Unhandled Rejection (Error): You did not specify the type of Source or Token to create. We could not infer which Element you want to use for this operation.

### ISSUE THREAD

**Issue by leotm** [stripe/react-stripe-elements#267]
### My goal

I would like to create a 2nd checkout form to retrieve and display the user's Stripe saved cards (our back-end does this, I get these successfully from our server), then let them submit the payment as usual.
Rather than the user entering card details as normal into the react-stripe-elements component(s), which I also have working successfully.

### The issue

I get `unhandled Rejection (Error): You did not specify the type of Source or Token to create. We could not infer which Element you want to use for this operation.` (see screenshot).

I get this because I am using none of these: `CardElement`, `PostalCodeElement`, `CardNumberElement`, `CardExpiryElement`, `CardCVC`, `PaymentRequestButtonElement` from *react-stripe-elements*.

Because I do not require any input from the user, into Stripe's components.
Because in this form, I am already displaying minimal saved card info.

And the error comes from trouble creating the token:
`const { token } = this.props.stripe.createToken({ name: 'Name' })`.

However this token is created fine if one of the *react-stripe-elements* components are used.

Any ideas?

I have also tried replacing my submit button with `PaymentRequestButtonElement`, but to no avail, as then I get `TypeError: Cannot read property 'destroy' of undefined` (see screenshot).

### My code (abstracted)

```
<StripeProvider apiKey={StripeKey}>
  <Elements>
    <CheckoutFormSavedCard
      savedStripeCards={this.state.savedStripeCards}
    />
  </Elements>
</StripeProvider>
```

Then `CheckoutFormSavedCard` looks like:

```
import React, { Component } from 'react'
import {
  injectStripe,
  CardElement,
  PostalCodeElement,
  CardNumberElement,
  CardExpiryElement,
  CardCVCElement,
  PaymentRequestButtonElement,
} from 'react-stripe-elements'
import { Router, routes } from '../../routes'
import * as Models from '../../../packages/stream-api-sdk/models'

interface Props {
  ...
}

interface State {
   ...
}

class CheckoutFormSavedCard extends Component<Props, State> {
  constructor(props: Props) {
    super(props)
    this.state = {
      ...
    }
  }

  public submit = async _e => {
    const { stripeToken } = this.props.stripe.createToken({ name: 'Name' })
    if (stripeToken) {
      const payload = {
        ...
      }
      try {
        await myApi.payments.process(myOwnAuthToken, payload)
      } catch (e) {
        console.log(e)
      }
    }
  }

  public selectCard = e => {
    this.setState({
      selectedCardID: e.target.value,
    })
  }

  render() {
    return (
      <div className="checkout">
        <h3>Select a card for payment</h3>
        <br />
        {this.props.savedStripeCards.map(card => (
          <div key={card.id}>
            <input
              type="radio"
              defaultChecked={card.isDefault ? true : false}
              onChange={this.selectCard}
              value={card.id}
            />{' '}
            {card.type} **** **** **** {card.lastFourDigits} {card.monthOfExpiry}/
            {card.yearOfExpiry}
            {card.isExpired}
          </div>
        ))}
        <br />
        <button onClick={this.submit}>Send</button>
      </div>
    )
  }
}
export default injectStripe(CheckoutFormSavedCard)
```

### Screenshots

<img width="556" alt="screenshot 2018-10-24 at 14 32 28" src="https://user-images.githubusercontent.com/1881059/47436743-fa5cf200-d79e-11e8-9fab-e04746612f5e.png">
<img width="590" alt="screenshot 2018-10-24 at 14 56 36" src="https://user-images.githubusercontent.com/1881059/47436744-fa5cf200-d79e-11e8-958c-28437ff5b283.png">

### More details

react-stripe-elements": "^2.0.1",
"@types/react-stripe-elements": "^1.1.7",
macOS Mojave 10.14
Version 69.0.3497.100 (Official Build) (64-bit)

Many thanks.

**Comment by leotm** [comment]
Sorry guys, I am a n00b, I don't need to create a new token, since there is no new card information being entered since it's being pre-filled from our back-end, so our back-end won't require a token in the payload.

But still getting this same error above with `PaymentRequestButtonElement`, if anyone can see why it's not working?
However I'll likely not be implementing `PaymentRequestButtonElement` because we will handle payment creation/execution server-side.

Cheers again.

**Comment by atty-stripe** [comment]
Hi @leotm, glad to see you figured out the original issue. Can you open a new issue here with the PaymentRequestButton problem you're facing? A link to a minimal reproduction (using CodeSandbox or JSFiddle) would be much appreciated.
