### ISSUE TITLE
ChangeObject error message language is choosed automatically

### ISSUE THREAD

**Issue by HamadaBrest** [stripe/react-stripe-elements#268]
I want to set English language for error messages included in `ChangeObject` when using `onChange` in `CardNumberElement`   
My location right now is France and I'm getting error message in French, is there a way to force a language in this case ? 

![stripe](https://user-images.githubusercontent.com/25125613/47486836-8de6ff00-d841-11e8-9cab-ad4a01183400.png)

**Comment by atty-stripe** [comment]
You can pass in a `locale` option to the `<Elements />` component. All options are listed in the Stripe.js reference: https://stripe.com/docs/stripe-js/reference#stripe-elements.

Elements by default infers the language from your browser, so you can also change that if you'd like!
