### ISSUE TITLE
CardElement HTML5 required form validation ignored on enter key submit

### ISSUE THREAD

**Issue by sanderfish** [stripe/react-stripe-elements#271]
### Summary

I'm using a CardElement combined with a couple of form fields. I want these form fields to use HTML5 form validation by setting the 'type' and by making the fields required. Normally, submission of the form is then prevented when the fields are not filled in or when the filled in data does not pass the test (e.g. email field is not in the email format).

I'm running into the following issue:
When focusing on the CardElement and pressing the 'Enter' key, the HTML5 form validation is ignored and the handleSubmit function runs. I've used the provided JSFiddle to reproduce:

https://jsfiddle.net/g9rm5qkt/752/

To reproduce, simply leave the Email field empty and fill the CardElement with a test card. Now first press the Pay button; you'll see submission is prevented because 'Email is required'. Now focus the CardElement field and press Enter, you'll now see that the handleSubmit function ran, ignoring the form validation.

I found similar issues (https://github.com/stripe/react-stripe-elements/issues/143 and https://github.com/stripe/react-stripe-elements/issues/193), but they seems to be slightly different.

Any help would be appreciated.

**Comment by mmmikeal** [comment]
i did something similar where I made a handleValidation function fire first, and if it passed my self made checks, would then submit the form. Just a suggestion if you didn't or couldn't find a workaround for HTML5 form validation

**Comment by atty-stripe** [comment]
Hi @sanderfish, thanks for reporting! This is a known issue, and something we're working on fixing. Will post here once it's done.

For now, I would recommend handling validation via JavaScript. Here's an example: https://github.com/stripe/elements-examples/pull/40.

**Comment by sanderfish** [comment]
Hi @atty-stripe, thanks for confirming. I'll validate via JavaScript for now.

**Comment by willcode4food** [comment]
@atty-stripe any progress on this one? Dealing with a use case where we'll have to apply the workaround you suggested

**Comment by atty-stripe** [comment]
Unfortunately no update yet, sorry!

**Comment by sashko-stripe** [comment]
Closing this as this project has migrated to [React Stripe.js](https://github.com/stripe/react-stripe-js). If you believe this is still important, please re-open it there.
