### ISSUE TITLE
US cardholders with Canadian postal codes cannot enter ZIP code.

### ISSUE THREAD

**Issue by blarsonat** [stripe/react-stripe-elements#273]
@atty-stripe commented: "this is a known problem unfortunately, and something we're actively working on addressing! One reason it happens is because we show postal code based on a dataset mapping card numbers to countries, but the dataset is sometimes wrong. And in some cases even if the data is correct, as you point out, the actual address might be a different country."

Creating an issue to track as I did not see one referenced in this discussion.

**Comment by atty-stripe** [comment]
Hi @blarsonat, if you don't mind, I'll keep everyone posted in the thread at https://github.com/stripe/react-stripe-elements/issues/20. This issue tracker is intended for bugs and feature requests in react-stripe-elements alone, and the issue you mention is in Stripe.js.
