### ISSUE TITLE
Why choose FLOW?

### ISSUE THREAD

**Issue by acpower7** [stripe/react-stripe-elements#274]
It's really perplexing why this library was written in flow. I'm trying to extract parts of this library to use in my app but I'm spending most my time learning how flow works which I don't want to do and is very frustrating.

hardly anyone outside facebook uses flow, please do a service to the community and migrate this library to typescript. thanks

**Comment by jenan-stripe** [comment]
Hi @acpower7. You shouldn't need to use flow to use this library. It's purely an internal choice.
