### ISSUE TITLE
Getting a blank page when using in create-react-app

### ISSUE THREAD

**Issue by aiven715** [stripe/react-stripe-elements#277]
I'm getting blank page, when I'm trying to render a CardElement using latest create-react-app(v2.1.1). Here it is the code I'm having:

```javascript
import React from 'react';
import { StripeProvider, CardElement, Elements } from 'react-stripe-elements';

export default () => (
    <StripeProvider apiKey={'pk_test_key'}>
      <Elements>
        <form>
          <CardElement />
        </form>
      </Elements>
    </StripeProvider>
);
```

**Comment by asolove-stripe** [comment]
@aiven715 Is there any error on the page? I have a simple demo in create-react-app that seems to work ok.

**Comment by aiven715** [comment]
@asolove-stripe no errors, just stripe form is not visible. I've fixed it by setting width of the form manually

**Comment by asolove-stripe** [comment]
Ah, glad you got it to work!
