### ISSUE TITLE
Getting a blank page when using in create-react-app

### ISSUE THREAD

**Issue by aiven715** [stripe/react-stripe-elements#278]
I'm getting blank page, when I'm trying to render a CardElement using latest create-react-app(v2.1.1). Here it is the code I'm having:

```javascript
import React from 'react';
import { StripeProvider, CardElement, Elements } from 'react-stripe-elements';

export default () => (
    <StripeProvider apiKey={'pk_test_key'}>
      <Elements>
        <form>
          <CardElement />
        </form>
      </Elements>
    </StripeProvider>
);
```

Also, from time to time I'm getting this error message in console:
```
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://js.stripe.com') does not match the recipient window's origin ('localhost:3000')
```

**Comment by aiven715** [comment]
Fixed by setting a width to a `form` element.

**Comment by cstoddart** [comment]
> Fixed by setting a width to a `form` element. Should that be reflected in docs?

So glad you posted this. Totally agree it should be added to the docs.

**Comment by pitops** [comment]
thats an insane issue. Thanks for the fix

**Comment by charleslouis** [comment]
Hi 

Just had the same.

Fixed by adding `width='100%'` to 
```<form onSubmit={handleFormSubmit}  width='100%'>```
as recommended in 
https://github.com/stripe/react-stripe-elements/issues/278#issuecomment-437827315

Thanks @aiven715
