### ISSUE TITLE
Requests

### ISSUE THREAD

**Issue by btn-ninja** [stripe/react-stripe-elements#280]
Hi,
Unable to find a place to file requests for Stripe, so posting here.

1 - In our old form, when a person started typing their name, all the fields could autofill.  This seems impossible to accomplish in the Elements.  Can you please create an option for this?

2 - Your example pages do not show the original HTML (only JS and CSS).  A simple update in your documentation could add clarity & save people time.

3 - I had to resort to stackoverflow, to find the documentation for creating a token when individual fields are used.  (https://stackoverflow.com/questions/42962752/creating-stripe-token-using-separate-elements/42963215)

So I have 4 issues (if you include the fact that I don't know where i could have posted this.)

Thanks!

**Comment by btn-ninja** [comment]
Also PS - Your documentation of styles is missing one that is apparently supported: fontWeight.
https://stripe.com/docs/stripe-js/reference#element-options

**Comment by cweiss-stripe** [comment]
Hi @btn-ninja 

Thank you for your feedback!

You can always reach out to our support team with questions and bug reports: https://support.stripe.com

re 1: 
It is indeed currently not possible to initiate credit card autofill from a name field and have it also fill the  card Elements. The autofill works across the individual Elements when initiated from the cardNumber/cardExpiry/cardCvc field.

re 2:
We currently have full HTML examples in the [Elements overview](https://stripe.com/docs/stripe-js) and [quickstart guide](https://stripe.com/docs/stripe-js/elements/quickstart) and [github examples](https://github.com/stripe/elements-examples). We'll look into improving the other parts with more complete examples.

re 3:
Thank you for noticing and reporting this, will fix!
