### ISSUE TITLE
Card element mount/unmount clears input state

### ISSUE THREAD

**Issue by thesmart** [stripe/react-stripe-elements#282]
#### Summary

Calling `cardElement.mount` clears whatever input the user entered into the form.  There should be an option to keep input and not reset.

#### Motivation

We have a credit card experience that spans multiple "pages".  The first page is "enter your credit card" page and the second is "confirm payment" page. It's common for users to go "back" from the confirmation page to the credit card form in order to edit something.  Unfortunately, there doesn't seem to be any way to `unmount` a card element in a way that retains the details entered by the user.  The `mount` and `unmount` reset the information.

This is unfortunate because of how React forces a re-rendering of DOM when state changes.  We should support the ability to unmount and remount elements without clearing state.

#### Alternatives

Alternative would be to provide a type of element similar to the card card form that takes a token and that renders the type and last 4-digits. It should maybe have a "reset" button for clearing the credit card for users to re-enter it.

#### Scope

Affects the Elements api.

#### Risks

Risk memory leaks. Would need to support similar mode for all types of elements.

Not implementing this just encourages writing custom card elements that are less secure than what Stripe provides.

**Comment by thesmart** [comment]
Hmm nevermind, I just realized that the card element uses an iframe and that it's not possible to remove and attach an iframe from/to the DOM without it reloading. Persisting card state across React transitions would require laying or some other CSS-only technique.

**Comment by dbo** [comment]
I'd appreciate to have this support. In case your react app renders different layouts (driven by Javascript), you for sure want to persist edit state of the element. The iframe could e.g. store/restore the edit state from its `sessionStorage` (bound to origin js.stripe.com).
