### ISSUE TITLE
Using `createToken` in Redux actions

### ISSUE THREAD

**Issue by unruffledBeaver** [stripe/react-stripe-elements#291]
This may be a feature request of sorts but I was curious if there was a pattern where I could use `createToken` in a redux-thunk. What I tried to do was:

```
// @flow
import * as React from 'react';
import { Elements, StripeProvider, injectStripe } from 'react-stripe-elements';

function stripeHOC(WrappedComponent: React.ComponentType<*>) {
    const WrappedWithStripeProps = injectStripe(WrappedComponent);
    /* eslint-disable flowtype/no-weak-types*/
    return class StripeElements extends React.Component<
        *,
        { stripe: ?Object }
    > {
        static displayName = `withStripeElements(${
            WrappedWithStripeProps.displayName
        })`;

        state = {
            stripe: null,
        };

        componentDidMount() {
            const stripe = window.Stripe(process.env.NEXT_APP_STRIPE_API_KEY);

            window.stripe = stripe;

            this.setState({
                stripe,
            });
        }

        render() {
            return (
                <StripeProvider stripe={this.state.stripe}>
                    <Elements>
                        <WrappedWithStripeProps {...this.props} />
                    </Elements>
                </StripeProvider>
            );
        }
    };
}

export default stripeHOC;
```

The issue here is that `createToken` in the window is not the wrapped version that is passed down from `inject`. It seems I would almost have to build my own implementation of the package to get the wrapped `createToken` that has access to the `registeredElements` or do something gnarly like `document.getElementById` from my action to supply the element to tokenize. One thought was if `Elements` had an optional callback for whenever elements are registered and unregistered so you could also store them in your own state manager.

Maybe there is a pattern here to do this that I'm missing though.

**Comment by asolove-stripe** [comment]
Hi @unruffledBeaver! Within the Wrapped component, the magic `createToken` is available as `this.props.stripe.createToken`, so can you just get that value back up to your redux state? You could pass a callback function down into the wrapped component and call it with `createToken` as an argument to smuggle it back up to the top level. Or any other trick you would normally use to get state from a lower-level component back up to a higher one.

Will that work? Or if not, can you explain a bit more about why not so we can come up with a solution that works?

**Comment by cweiss-stripe** [comment]
Closing this. Please let us know if the approach outline by @asolove-stripe is not working for you.
