### ISSUE TITLE
Retrieve Source

### ISSUE THREAD

**Issue by ryanolsonx** [stripe/react-stripe-elements#292]
### Summary

Given that I have a source id (or a token), would I be able to be able to pre-populate a CardElement from that? It looks like there's `retrieveSource` but the documentation is unclear.

### Other information

The problem I'm trying to solve is being able to use a CardElement to setup an initial payment that a customer can use and provide a way to update the card later.

**Comment by atty-stripe** [comment]
It's not possible at the moment to populate Elements with a source. The recommended path for allowing users to update their info is show a new form that allows them to add a new card.

More info on saving cards to customers here: https://stripe.com/docs/saving-cards

Hope that helps!

(Closing as this issue tracker is for bugs / feature requests in react-stripe-elements itself)
