### ISSUE TITLE
Firefox only - Error: Live Stripe.js integrations must use HTTPS. 

### ISSUE THREAD

**Issue by johnmosesman** [stripe/react-stripe-elements#293]
I am getting the error `Error: Live Stripe.js integrations must use HTTPS. For more information: https://stripe.com/docs/stripe-js/elements/quickstart#http-requirements` but only when viewing the page with Firefox. The same code works fine with Chrome and Safari.

![image](https://user-images.githubusercontent.com/3760568/50529504-00cb5b00-0abb-11e9-8653-3f1a54fa8688.png)

I am loading stripe through HTTPS using the advanced method as shown in [the async demo](https://github.com/stripe/react-stripe-elements/blob/master/demo/async/async.js#L95). And as you can see below it appears to be loading over HTTPS based on the Network tab of the Firefox dev tools.

![image](https://user-images.githubusercontent.com/3760568/50529584-8fd87300-0abb-11e9-9ea0-08116d97fe84.png)

Are there any other factors besides loading `https://js.stripe.com/v3/'` over HTTPS?

Thanks!

**Comment by johnmosesman** [comment]
To give you more context, here is how I am loading stripe. This component is inside of an iframe.

```
class MyComponent extends Component {
  loadStripe() {
    const stripeJs = document.createElement('script');

    stripeJs.src = 'https://js.stripe.com/v3/';
    stripeJs.async = true;

    stripeJs.onload = () => {
      const iframe = document.getElementById('my-iframe');

      this.setState({
        stripe: iframe.contentWindow.Stripe("pk_live_12345")
      });
    };

    const rawframe = document.getElementById('my-iframe');
    const framedoc = rawframe.contentWindow.document;

    framedoc.body.appendChild(stripeJs);
  }

  componentDidMount() {
    this.loadStripe();
  }
}
```

**Comment by johnmosesman** [comment]
I reached out to Stripe support and got the following response, which required reworking my app setup, but it did fix the problem. It would be great if Stripe.js would handle this issue within itself.


> The cause of the problem appears to be a difference in how Firefox returns the location attribute of the window object for an iframe versus other browsers. Specifically, as far as I can tell, for an iframe created on the page with no src attribute, on other browsers the location will be inherited from the top-level page. On Firefox however, the value will be "about:blank".
>
> When stripe.js loads, it checks the current window location to determine if the page is being loaded over HTTPS or not, as a payment form must be loaded over HTTPS. It appears that on your site, this check is failing as you are loading stripe.js only within the "my-iframe", and on Firefox the location of this iframe is about:blank, which is then not recognised by stripe.js as a HTTPS URL. You can see this by checking contentWindow.location of the iframe in different browsers.

---

> Unfortunately, I'm not sure what the cleanest solution to this would be in your case. I would suggest that you load the https://js.stripe.com/v3/ script and interact with the global Stripe object at the top level of the page, or otherwise outside of the my-iframe [0]. I appreciate that this may be difficult with the current design of your site though. Another option might be to retain the iframe approach but rather than creating the iframe directly through Javascript, load it from a defined HTTPS URL first(i.e. set the src attribute when you create the iframe DOM element). I'll also report this to the the relevant team here at Stripe in case there is a change we can make to stripe.js, but for now I would suggest trying one of these workarounds.
>
> [0] - https://stripe.com/docs/stripe-js/reference#including-stripejs 

I mentioned that I tried to load stripe.js outside of the iframe, but it runs into a known issue:

> My apologies, I think my proposed solution there of loading the script outside of the iframe won't work, as you would run into the issue described by https://github.com/stripe/react-stripe-elements/issues/134 - the stripe.js library and the StripeProvider instance need to both be in the same frame. 
> 
> Your setup essentially mirrors the setup Jenan proposed on that issue for this case [0]. It does indeed appear to work in general as he thought it would, but there is this seemingly Firefox-specific issue of the iframe that contains stripe.js having its location as about:blank that is causing a problem. Therefore I'd have to suggest my other workaround of using a specific src attribute on the iframe, as hinted at by the user on that issue. You can host the initial iframe content(essentially a basic <html></html> skeleton) at a URL from your server, create an iframe tag at the top level of your page and set its src attribute to point at this initial content, and then dynamically add content to the loaded iframe, in the same way as you do now. I believe this should work, as then the location of the iframe should be set to a https URL and stripe.js will be able to load.
>
> [0] - https://github.com/stripe/react-stripe-elements/issues/134#issuecomment-359123436 

---

So TL;DR, I moved my initialize stuff into a new file that I hosted at a secure URL (ex: `https://my-cdn.com/initialize-app.js`), and loaded the iframe with that as the src:

```
<iframe src="https://my-cdn.com/initialize-app.js"></iframe>
```

**Comment by atty-stripe** [comment]
Hi @johnmosesman, thanks for bringing this to our attention. It does seem like an edge-case in Firefox that we're not handling correctly, and we will fix it in Stripe.js. Glad you found a workaround! Will post here when we've fixed it.
