### ISSUE TITLE
Firefox Content Security Policy Console Errors

### ISSUE THREAD

**Issue by itzsaga** [stripe/react-stripe-elements#296]
### Summary

Multiple Content Security Policy Errors in the console. They're present in the sample Fiddle: https://jsfiddle.net/g9rm5qkt/

### Other information

I've only found this in Firefox. Currently using Firefox 64.0

**Comment by cweiss-stripe** [comment]
This is a long known Firefox bug. `frame-src` was deprecated but was than un-deprecated. Firefox still works fine with this warning.
see also https://w3c.github.io/webappsec-csp/#changes-from-level-2

**Comment by itzsaga** [comment]
Perfect, thank you @cweiss-stripe.
