### ISSUE TITLE
PostalCodeElement not hiding based on card number

### ISSUE THREAD

**Issue by pthieu** [stripe/react-stripe-elements#297]
Based on this [comment](https://github.com/stripe/react-stripe-elements/issues/200#issuecomment-386699814) it seems the `<PostalCodeElement>` should hide or show based on some logic under the hood.

I know it's working because the format is set to something or `optional` based on the test card. But when I try the Australian test card in (which has optional postal code), the postal code element does not get hidden, but you can type anything you want.

This is my form code:
```
      <form className="checkout-form__element">
        <label>
          Card Number
          <CardNumberElement onChange={this.handleCardChange} />
        </label>
        <label>
          Expiration Date
          <CardExpiryElement />
        </label>
        <label>
          CVC
          <CardCVCElement />
        </label>
        <label>
          Postal Code
          <PostalCodeElement onChange={this.handleCardChange} />
        </label>
        <Button
          primary
          raised
          onClick={this.handleSubmit}
          disabled={this.state.disableSubmit}
        >
          Pay
        </Button>
      </form>
```

and this is the parent container:
```
          <Elements>
            <CardForm onSubmit={this.handleFormSubmit} />
          </Elements>
```

I tried to put an `onChange` event on the `CardNumberElement` and `PostalCodeElement` to check and see if there is an `optional` field passed in, but this does not exist so I can't write logic to hide/show the `PostalCodeElement` manually.

**Comment by pthieu** [comment]
@cweiss-stripe I didn't want to use it because I couldn't change the format of the inputs from all in one line to multiple lines.

I couldn't find anything in the docs or examples showing how to do this so I'm not sure if it's possible, can you let me know if I can put the form inputs on different lines?

**Comment by atty-stripe** [comment]
Hi @pthieu, to clarify: the `CardElement` has the logic of automatically showing or hiding the postal code field, but the `PostalCodeElement` does not. 

If you want to have the fields on different lines, we suggest you use the individual Elements (as you did in your code above), and implement your own business logic to show or hide the postal code field. We do not currently expose an `optional` field or the card number itself, so you might have to do this by asking your customer for their card country first.

The `CardElement` determines the card country using our BIN table data, but this tends to be a bit brittle at times (see #20). As such, we're careful about extending this feature without looking at the problem more broadly.
