### ISSUE TITLE
Demo Split Form security Issue?

### ISSUE THREAD

**Issue by dagfs** [stripe/react-stripe-elements#30]
Is the split form elements supposed to send a get request for each character written?
Eg:
https://q.stripe.com/?event=elements.sibling_update&event_count=124&timestamp=1499856761328&frame_width=0&version=f7b9dfd&options-__privateSiblingValues-postalCode=42424&element=cardCvc&features-noop=true&features-12345_postal_placeholder_split_fields=true&key=pk_RXwtgk4Z5VR82S94vtwmam6P8qMXQ&referrer=http%3A%2F%2Flocalhost%3A8080%2F&stripe_js_id=327c3b64-6dfa-4b17-838b-b6e72b1f7cb5

It looks like it sends the current field being entered

**Comment by michelle** [comment]
Thanks for the report! We're being overly aggressive in reporting events to ourselves -- we'll push a change that fixes this in a bit.

**Comment by johnmosesman** [comment]
Hey @michelle did anything ever happen with this? On slower internet connections these events are making things like checkbox clicks of non-stripe elements elsewhere on the form very laggy.

Is there a way to scope these events to only target the stripe elements?
