### ISSUE TITLE
Basic create-react-app test throwing error

### ISSUE THREAD

**Issue by captDaylight** [stripe/react-stripe-elements#307]
I've tried this locally as well and gotten the same error, but as you can see in from this basic code snippet in [code sand box instance](https://codesandbox.io/s/ym9128k73z) I'm getting this error:

```
Please load Stripe.js (https://js.stripe.com/v3/) on this page to use react-stripe-elements. If Stripe.js isn't available yet (it's loading asynchronously, or you're using server-side rendering), see https://github.com/stripe/react-stripe-elements#advanced-integrations
```

This is happening even though I'm simply including the `StripeProvider` with a key at root. I see that this is clearly not a problem in the [jsfiddle example](https://jsfiddle.net/attystripe/xux7qzch/) from the docs, which doesn't use create-react-app. Has anyone else run into this issue and found a solution?

**Comment by atty-stripe** [comment]
Hi there, as the error message suggests, you must load Stripe.js from that URL in your web-app, in addition to using the `StripeProvider`. Concretely, this would mean adding `<script src="https://js.stripe.com/v3"></script>` to your HTML file.

The `StripeProvider` provides an instance of the `Stripe` object to child React components using the Context API. It does not load Stripe.js itself.

If you have suggestions for how we can improve our docs to make this clearer, please feel free to share here!

**Comment by ozluy** [comment]
https://medium.com/@ozluy/loading-stripe-script-if-necessary-189f228e0f34
how about this solution?
