### ISSUE TITLE
Un-mounting stripe elements disables newly-added (non-stripe) inputs in IE11

### ISSUE THREAD

**Issue by smerin** [stripe/react-stripe-elements#309]
### Summary

I have a stripe form using CardNumberElement, CardExpiryElement, CardCVCElement and also a PaymentRequestButtonElement. It works fine and has been in production for a few months, but there's an apparent bug in IE11 as described below. Code sandbox and JSFiddle don't work on IE11 so I can't reproduce it there.

When payment is successfully registered the form gets hidden (i.e. unmounted) and some new inputs appear (not stripe inputs). In IE11 these inputs can be focused on, but can't be interacted with. This is the case with react-controlled inputs and also an uncontrolled input which I put in there as a test.

### Other information

When the stripe form is hidden, a few console errors appear (in IE11)...
![consoleerrors](https://user-images.githubusercontent.com/17762279/51261079-7f733400-19a7-11e9-8c5d-42c5e37b05e0.png)

We've also noticed that the very latest version of IE11 seems to work fine, but older version i.e. 11.0.90 and 11.0.47 are having this problem.

**Comment by asolove-stripe** [comment]
Hi @smerin, thanks for reporting this and sorry for the painful bug. I'm trying to understand exactly what you're seeing.

> When payment is successfully registered the form gets hidden (i.e. unmounted) and some new inputs appear (not stripe inputs). In IE11 these inputs can be focused on, but can't be interacted with. This is the case with react-controlled inputs and also an uncontrolled input which I put in there as a test.

I think you're saying that you are adding new inputs to the page at near the same time (at the same time? after?) as you're unmounting the Stripe Elements. And that those new inputs can't be interacted with. A few questions:

- Are there other inputs that were already on the page before this, and can they be focused/interacted with?
- When does the console show those errors? Is it immediately on the Elements being unmounted? When you interact with your inputs?

We're going to try to reproduce this in older subversions of IE11 but could use some more info on what to look for.

**Comment by asolove-stripe** [comment]
Hi, I'm going to close this issue since we haven't heard enough details to investigate further. But please feel free to add more detail here or open a new issue if this is still occurring.
