### ISSUE TITLE
PostalCodeElement validation isn't enforced for Canadian CC on mobile devices

### ISSUE THREAD

**Issue by devontemac** [stripe/react-stripe-elements#311]
### Summary
When using a payment form, and entering in a Canadian credit card (ex. from Stripe docs: `4000001240000000`) on desktop, the zip code validation works perfectly. However, on mobile devices (or chrome mobile) it only validates the field based on being non-empty, not by format or length.

### Recreation
1. Create a payment form with a zip code field
2. Enter in a Canadian CC (ex. `4000001240000000`)
3. Open up the page on a mobile device, or on chrome mobile web
4. Enter in any value, for example (`f`) and see that it validates the field.

On the component, I added the onChange prop, and logged the event. 
`<PostalCodeElement onChange={(e) => console.log(e)} />`

_On Desktop_
```
{"elementType":"postalCode","value":"f","empty":false,"complete":false}
```

_On Mobile_
```
{"elementType":"postalCode","value":"f","empty":false,"complete":true}
```

As you can see, the exact same webpage, and same value (`f`) show two different results. Mobile showing complete as true, and desktop showing false.

**Comment by asolove-stripe** [comment]
@devontemac: Sorry, that seems like an obnoxious difference! I'm trying to reproduce and understand why it's happening. Can you confirm the mobile device/browser you're using? I'm especially curious whether it's iOS or Android and what OS version. Thanks!

**Comment by devontemac** [comment]
I'm using the Chrome (v. 70.0) developer tools, and I clicked the "Toggle device toolbar" button and reloaded the page to mimic a mobile device. Thanks!
<img width="67" alt="screen shot 2019-01-23 at 7 32 36 am" src="https://user-images.githubusercontent.com/43973311/51617443-19c00400-1ee1-11e9-9272-a73ddb64fa83.png">

**Comment by sashko-stripe** [comment]
Closing this as this project has migrated to [React Stripe.js](https://github.com/stripe/react-stripe-js). If you believe this is still important, please re-open it there.
