### ISSUE TITLE
Cannot display PaymentRequestButton

### ISSUE THREAD

**Issue by iKrushYou** [stripe/react-stripe-elements#313]
### Summary

I'm trying to follow the [tutorial](https://github.com/stripe/react-stripe-elements#using-the-paymentrequestbuttonelement) on adding the RequestPaymentButton in React but I am not having luck. I have recreated the code [here](https://codesandbox.io/s/rp2j6w50m)

It does not appear to be working whatsoever on codesandbox, but, for some reason, in my local environment, I can get it to work only if I try querying `paymentRequest.canMakePayment()` before trying to call it again with a `then()`

Furthermore, I can only get the button to display on Chrome using this method but not Safari. 

Update:

When trying to use the button when it appears in Chrome, it errors:
```
Uncaught Error: Payment Request is not available in this browser.
    at new t ((index):1)
    at t.<anonymous> ((index):1)
    at t.show ((index):1)
    at t.Xo._elementShow ((index):1)
    at (index):1
    at (index):1
    at Array.forEach (<anonymous>)
    at t._emit ((index):1)
    at e._handleMessage ((index):1)
    at e._handleMessage ((index):1)
    at (index):1
```
I can confirm that I have the buttons working [here](https://stripe.com/docs/stripe-js/elements/payment-request-button#try-it-out) in both Chrome and Safari

**Comment by iKrushYou** [comment]
It looks like all of my issues were stemming from me not having valid HTTPS (I had HTTPS, but it wasn't verified). 

I followed the tutorial [here](https://medium.com/@clementsauvage/testing-apple-pay-on-the-web-with-stripe-99499427e147) and used ngrok to expose my localhost and add to Apple Pay on the Stripe website. This also fixed the Google Pay issues also. 

This should probably be noted somewhere [here](https://stripe.com/docs/stripe-js/elements/payment-request-button) as well

**Comment by cweiss-stripe** [comment]
Hi @iKrushYou 
Yes, HTTPS is required [as listed in the documentation as prerequisite](https://stripe.com/docs/stripe-js/elements/payment-request-button#prerequisites).
Also, Payment Request only works inside sandboxed iframes when the `allowpaymentrequest` attribute is set on the `iframe`, which is the reason why it does not work inside the codesandbox.io iframe.
