### ISSUE TITLE
uBlock Origin blocks some network requests from Stripe elements

### ISSUE THREAD

**Issue by sambokai** [stripe/react-stripe-elements#314]
### Summary

I tested multiple popular ad blockers. All with standard config and in an isolated environment with Chrome Version 74.0.3687.0 (64-Bit):

| Name                                                                                                                                   | Works?             |
|----------------------------------------------------------------------------------------------------------------------------------------|--------------------|
| [Adblock Plus](https://chrome.google.com/webstore/detail/adblock-plus-free-ad-bloc/cfhdojbkjhnklbpkdaibdccddilifddb/)                  | :white_check_mark: |
| [AdBlock](https://chrome.google.com/webstore/detail/adblock-free-ad-blocker/gighmmpiobklfepjocnamgkkbiglidom/)                         | :white_check_mark: |
| [Ghostery](https://chrome.google.com/webstore/detail/ghostery-–-privacy-ad-blo/mlomiejdfkolichcflejclcbmpeaniij) | :white_check_mark: |
| [uBlock Origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=de)                        | :x:                |

### Other information

<img width="1672" alt="bildschirmfoto 2019-01-29 um 18 52 35" src="https://user-images.githubusercontent.com/7689616/51929714-2967ad00-23f9-11e9-9f13-3e3e7c1a17fd.png">

<img width="849" alt="bildschirmfoto 2019-01-29 um 18 55 07" src="https://user-images.githubusercontent.com/7689616/51929672-0e953880-23f9-11e9-8c40-26d8d8893fa8.png">

Related:
stripe/react-stripe-elements#222
stripe/stripe-php#528
stripe/react-stripe-elements#256

**Comment by fred-stripe** [comment]
Hello, I've tested this with uBlock and the Chrome version you reported, and Elements works as expected—the fields appear, and I can enter a card number and create a card token without issue. It appears that uBlock stops some network requests from Stripe.js, however, the blocked requests shouldn't stop users from paying.

**Comment by 10chars** [comment]
@fred-stripe Hello, some of our users are reporting an issue with uBlock on Firefox blocking stripe and causing the elements not to render.

I could not reproduce the error on OSX but have confirmed the issue via our logs.

```
Browser name
Firefox
Browser version
66.0
Language
ja
User Agent
Mozilla/5.0 (Windows NT 6.1; rv:66.0) Gecko/20100101 Firefox/66.0
Operating System
Windows 7
```

Thanks

**Comment by cinnabarcaracal** [comment]
Probably not the same issue, but this might help someone else.

I just had a problem where the presence of uBlock Origin made `elements.getElement(CardElement)` fail to return the element if called too quickly. I was running this as soon as `useElements()` returned something, then passing the cardElement ref to some other code. This worked fine without ublock.

The fix was to pass the `elements` ref to that other code, and only call `elements.getElement(CardElement)` at the moment of checkout (which is a better approach anyway).
