### ISSUE TITLE
Cannot fill stripe fields using Appium on iOS Safari

### ISSUE THREAD

**Issue by joaopslins** [stripe/react-stripe-elements#316]
## Summary ##

I'm trying to do some automated tests using BrowserStack, which uses Appium for interfacing with mobile devices. These tests are being written in Python.

On the page that uses Stripe Elements, I've used the Selenium method `driver.switch_to.frame(iframe)` so I can fill the form fields inside the iframes. This work fine until I run the tests on Apple mobile devices, where I get an error `Error while executing atom: Blocked a frame with origin "https://www.xyz.com" from accessing a frame with origin "https://www.abc.com". Protocols, domains, and ports must match. (status: 18)`. This issue is referred on the appium docs [here](http://appium.io/docs/en/advanced-concepts/cross-domain-iframes/) and on their repo [here](https://github.com/appium/appium/issues/5832). But it looks like this restriction is imposed by Apple so it's not Appium's fault.

I'd like to know if there is a workaround for this. I've tried to programmatically set the fields on my form but react-stripe-elements does not supply a way to do it, I assume it's for security purposes, which means it can't be helped. Wondering if someone already went through this before.

## Steps to reproduce ##

Try to fill react-stripe-elements form fields using Appium on Apple mobile devices, using Selenium iframe switch API, and fail because the iframe domain differs from the page's domain

**Comment by atty-stripe** [comment]
Hi @joaopslins, thanks for opening this ticket! Unfortunately we've seen issues with Appium and iOS Safari ourselves, and I'm not personally aware of workarounds to this documented limitation with Appium.

In general, we don't recommend Selenium tests that enter input into the iframes directly as the internal DOM of Elements may change without notice. There is more discussion on testing here: https://github.com/stripe/react-stripe-elements/issues/52.

At the very least I recommend skipping the tests on iOS, or writing shallow unit tests instead. Hope that helps!
