### ISSUE TITLE
shippingaddresschange returning empty array for addressLine

### ISSUE THREAD

**Issue by arronhunt** [stripe/react-stripe-elements#318]
### Summary

Listening to the shippingaddresschange event is returning an incorrect address object, notably an empty array for the key `addressLine`. I'm not sure if this is a problem with the library itself or a problem with ApplePay. 

### Other information

<img width="462" alt="screen shot 2019-02-07 at 5 01 49 pm" src="https://user-images.githubusercontent.com/298336/52452981-2efc7b80-2afa-11e9-912d-b484dd9178ad.png">

```jsx
paymentRequest.on('shippingaddresschange', (ev) => {
  if (ev.shippingAddress.country !== 'US') {
    ev.updateWith({status: 'invalid_shipping_address'});
  } else {
    console.log(ev.shippingAddress);
    ev.updateWith({ status: 'success' });
  }
});

/* returns
{
  addressLine: [],
  city: "Seattle",
  country: "US",
  dependentLocality: "",
  organization: "",
  phone: "",
  postalCode: "98101",
  recipient: "",
  region: "WA",
  sortingCode: "",
}
*/
```

Notice in the ApplePay modal both Address Line 1 and Recipient exist, but don't get returned. 

* macOS 10.14.2 
* Safari 12.0.2

**Comment by atty-stripe** [comment]
As mentioned in the docs [0], browsers and payment methods may strip some parts of the shipping address they deem not necessary to calculate shipping costs. This is by design for Apple Pay.

[0] https://stripe.com/docs/stripe-js/reference#payment-request-on

**Comment by bkrall** [comment]
Hi @atty-stripe - is the only way on web to use Apple Pay then to get a valid shipping address first? We were hoping to save the shipping address directly from Apple Pay.

**Comment by atty-stripe** [comment]
@bkrall The `shippingaddresschange` event will have a subset of the shipping address, but the `token` or `source` object will have the complete address. So you can certainly depend on Apple Pay for the full address.

**Comment by bkrall** [comment]
@atty-stripe thanks, that's encouraging.

right now in the `token` object I'm seeing all of these address fields as null, I have a shipping address for the card in Apple Pay but I'm not seeing it come through in the `token`, anything else I should check? Getting a valid token back using this method: https://stripe.com/docs/stripe-js/elements/payment-request-button#complete-payment

```
card: Object
address_city: null
address_country: null
address_line1: null
address_line1_check: null
address_line2: null
address_state: null
address_zip: null
address_zip_check: null
brand: "American Express"
...
```

**Comment by arronhunt** [comment]
Thanks @atty-stripe, I was indeed incorrectly listening to the shipping address change and not looking at the token returned.
