### ISSUE TITLE
IE Edge (Windows 10) unmount/mount issue with <CardElement> 

### ISSUE THREAD

**Issue by spencerfdavis** [stripe/react-stripe-elements#320]
### Summary
Seeing an issue with IE Edge on Windows 10 where `<CardElement>` is removed from the page and then added back.  This example allows the user to toggle payment type and does not load the <CardElement> after being removed/added back.

Not sure if it is related to this IE 11 bug https://github.com/stripe/react-stripe-elements/issues/309

### Other information
I have the `<Elements>` tag on the parent component and `injectStripe` as a hoc on the child.

![screen recording 2019-02-15 at 03 19 pm](https://user-images.githubusercontent.com/1526292/52887726-03027b00-3136-11e9-9a02-9ef8162b3401.gif)

**Comment by asolove-stripe** [comment]
@spencerfdavis Oh no, that's no good!

Can you say more about what your code is doing? It looks to me like you might be unmounting the content under the "Credit Card" tab, causing the Element to need to load again. Is it possible you want to still render the content and just have it be hidden?

**Comment by IreneIrene** [comment]
I have the same issue with CardNumberElement, CardExpiryElement and CardCVCElement. When I toggle the payment type, elements don't load. Is there a way to fix this?

**Comment by asolove-stripe** [comment]
Hi @IreneIrene: can you describe what your code is doing in this toggle? Is it updating to no longer render the Element, or just styling part of the DOM as hidden? Because Elements wrap iframes which are relatively expensive to set up, we strongly recommend the latter rather than the former.

**Comment by IreneIrene** [comment]
> Hi @IreneIrene: can you describe what your code is doing in this toggle? Is it updating to no longer render the Element, or just styling part of the DOM as hidden? Because Elements wrap iframes which are relatively expensive to set up, we strongly recommend the latter rather than the former.

Yes, it is updating to no longer render.

**Comment by asolove-stripe** [comment]
That approach is going to be quite slow as this requires re-creating the iframe and having it reload all of its content each time it is rendered. I would recommend having the Element always be rendered and just using CSS to hide it when you don't want it visible.

**Comment by IreneIrene** [comment]
> That approach is going to be quite slow as this requires re-creating the iframe and having it reload all of its content each time it is rendered. I would recommend having the Element always be rendered and just using CSS to hide it when you don't want it visible.

Thanks, I'll try this approach.

**Comment by IreneIrene** [comment]
It worked, but now I have the same problem with  PaymentRequestButtonElement in Microsoft Edge. 
I  have two buttons in order to the toggle payment type  - PaymentRequestButtonElement  and my custom button.  When I click my custom button, CardNumberElement, CardExpiryElement and CardCVCElement are displayed (I use CSS already). 
The problem is that my custom button is displayed, but PaymentRequestButtonElement isn't.
I can't always render PaymentRequestButtonElement  because  I have to call stripe.canMakePayment first.  How do I fix this?

**Comment by asolove-stripe** [comment]
@IreneIrene I think you want to use the same strategy: render the PaymentRequest button inside the right element after `canMakePayment` and then have that element be visible or invisible via css.
