### ISSUE TITLE
Change cardCVCElement to cardCvcElement

### ISSUE THREAD

**Issue by adolfoportilla** [stripe/react-stripe-elements#323]
Feature request or idea? Consider opening an
[API review](https://github.com/stripe/react-stripe-elements/tree/master/.github/API_REVIEW.md)!

### Summary

The CardCVCElement has an incorrect casing name. In the DOM, it renders as CardCvcElement, but to import the element you need to use CardCVCElement. This should be the same.

This is useful for testing, because if you try to find the component you need to search it as CardCvcElement, not as CardCVCElement, which is not intuitive.

**Comment by asolove-stripe** [comment]
Hey @adolfoportilla, thanks for pointing this out! I agree it would be better that way, but also it would be a breaking change. I think in the future we might also export `CardCvcElement` as a synonym. But given that this isn't that hard to search for, I don't think we'll be fixing it immediately.

**Comment by asolove-stripe** [comment]
Sorry for the late follow-up here, but this was already fixed in the [v4](https://github.com/stripe/react-stripe-elements/releases/tag/v4.0.0) release!
