### ISSUE TITLE
CVV number should display in dot like input Type password

### ISSUE THREAD

**Issue by masterGennadij** [stripe/react-stripe-elements#328]
Hello,

I faced one issue that CVV number is directly shown to user. The CVV number should not be visible to user because it is private for security.

Like password field

**Comment by asolove-stripe** [comment]
Hi @masterGennadij! Most online checkout forms don't mask out the CVC number. The PCI and other appropriate standards also don't recommend doing so.

**Comment by dalba1992** [comment]
This is very important this, I think so.
If possible, I want to hide the CVC part in CardElement
How can I do so?
Please help me.

**Comment by asolove-stripe** [comment]
Hi @dalba1992, there is no way to do this with Stripe Elements. Is there a particularly strong reason you need to do so?

**Comment by dalba1992** [comment]
Thank you for your reply.
Honestly, I need to hide the CVC part in card element for the security.
Please let me know how I can do so.
Regards.

**Comment by Sbphillips19** [comment]
@dalba1992 did you ever figure out a way around this?

**Comment by Axelesin** [comment]
Hello,
I have the same problem, but I have not seen a solution.
Could you please say whether such an opportunity has arisen?

**Comment by coding-parrot** [comment]
Can this be re-opened? 

> The PCI and other appropriate standards also don't recommend doing so.

The customer experience when looking at their unhidden CVV is horrible. A person nearby can also read the CVV. This should be a feature provided by Stripe.

**Comment by danny-dang** [comment]
Please reopen this. This is very important. A nearby person may take picture and get all the credit card information
