### ISSUE TITLE
Can't find variable: document

### ISSUE THREAD

**Issue by Dorian942** [stripe/react-stripe-elements#329]
Hello, 
Im trying to use Stripe for the first time and i took the demo's code (**index.html** and **index.js**)

### Summary

Im using Expo and i just took the code copy + paste and it doesn't work
I tryied to install storybook but it didn't solve my problem 👎 

> Can't find variable document

### Other information

![image](https://user-images.githubusercontent.com/36959155/53981855-c661e800-4113-11e9-9267-cd40960e6313.png)

**Comment by asolove-stripe** [comment]
Hi @Dorian942, sorry you're having trouble with this. It's hard for me to say what's going wrong here. The index.js file in `demo` depends on a lot of details of the babelrc and other config files in this repo. Did you copy this and install dependencies, too? 

If you're looking to try this out in the easiest way possible, there are some examples [over on stripe.dev](https://stripe.dev/react-stripe-elements/) that I think you can use directly inside of a new [create-react-app](https://github.com/facebook/create-react-app) app.
