### ISSUE TITLE
[Question] Which queries can be cached by a PWA?

### ISSUE THREAD

**Issue by Sturgelose** [stripe/react-stripe-elements#331]
### Summary

First of all, thanks for your platform, is amazingly easy to use :)

Anyways, we have a PWA in our company and we are using Stripe on it.
I'd like to optimize a bit the queries that Stripe does back to its servers, but of course, I do not want to break or somehow make insecure my transactions.

So: which queries can be cached by the Service Worker? Or, maybe, should we just set the default caches as given by Stripe servers?

Mostly I can see that there arre requests to js.stripe.com and m.stripe.com.

Are there any guidelines on this?

Thanks a lot!

**Comment by atty-stripe** [comment]
Hi @Sturgelose, as far as I'm aware, I don't think your PWA or service worker can operate on network requests made by Stripe iframes, as they are on a different origin. Rest assured that we do our best to keep requests secure and performant, and you should be able to use this library out of the box.
