### ISSUE TITLE
I need to hide the CVC part on CardElement component.

### ISSUE THREAD

**Issue by dalba1992** [stripe/react-stripe-elements#333]
### Summary

Dear guys,
I am using this component for my project.
CardElement component is good for me, but from security problem, I need to hide the CVC part.
I tried much time by myself, but can't find solution.
Please help me to hide the CVC Part.
I need other functions of CardElement. (Only need to hide the CVC Part).
Thank you.
Regards.
### Other information

![image](https://user-images.githubusercontent.com/20521231/54349964-4c87ac80-4687-11e9-9b07-f433cff8d9eb.png)

**Comment by BalkrishnaBhatt** [comment]
Same as #328

**Comment by asolove-stripe** [comment]
Hi @dalba1992: is the problem that you don't want to collect CVC at all? Or that you want the CVC value the user types in to be hidden, like a password field? (That would be the same as #328)

**Comment by dalba1992** [comment]
I don't want to collect CVC at all

**Comment by Arthy-Castro** [comment]
did you get solution
Please tell me once you got

**Comment by Burize** [comment]
@asolove-stripe   The customer may require this field to be hidden. Therefore, it would be great to have such an opportunity for `CardCVCElement` =(

**Comment by ahmadabdolsaheb** [comment]
I think it would be great to re open this issue and add this functionality.
