### ISSUE TITLE
CardElement .StripeField--fake input appears after autofill

### ISSUE THREAD

**Issue by ravenwilde** [stripe/react-stripe-elements#334]
### Summary

In our application we are consistently experiencing a bug in the `CardElement` where the `<input class="Stripefield--fake" element is visible (see screenshots below). This occurs after the card number field has been auto-filled by Chrome's payment info manager. Since this element is within the iframe, I can't figure out a way to hide it. Is there a style prop that I need to pass to make this disappear?

![Screen Shot 2019-03-18 at 6 48 50 PM](https://user-images.githubusercontent.com/2431504/54568832-1dd34400-49af-11e9-9909-cbda3f835a99.png)

![Screen Shot 2019-03-18 at 6 59 53 PM](https://user-images.githubusercontent.com/2431504/54569125-16f90100-49b0-11e9-85bc-fcd4ccb4a558.png)

### Other information

Appears in Chrome, on desktop and mobile.
We are using `"react-stripe-elements": "^2.0.3"`

**Comment by atty-stripe** [comment]
Hi there! Thank you for bringing this to our attention. I'm not able to reproduce this behavior on Chrome on our example site: https://stripe.dev/elements-examples. What versions of Chrome / operating system are you using?

**Comment by ravenwilde** [comment]
The bug is not appearing for me on the demo site either, only on our implementation.

I am testing on Chrome 72.0.3626.121 macOS Sierra 10.12.6

**Comment by atty-stripe** [comment]
Could you share a link to your site or a jsfiddle with a reproduction?

**Comment by ravenwilde** [comment]
It won't repro in jsfiddle, the site is app.farmlogs.com, you would need to sign up for a free account and navigate to `https://app.farmlogs.com/#billing`. I'm sorry for the inconvenience.

**Comment by atty-stripe** [comment]
I'm able to reproduce on your site! A cursory analysis shows that the hidden input we use for autofill is being stripped of styles (the input you've highlighted in screenshot above.) I see that you're using FullStory in your application — could you try and disable that and see if that fixes it? Will also continue investigating.

**Comment by asolove-stripe** [comment]
Hi @ravenwilde: I was just going to dig into this and see if we could figure out what's going on, but it looks like I can no longer reproduce the issue. Do you still see this happening? Or did you change something on your side that fixed it?

Thanks!

**Comment by ravenwilde** [comment]
@asolove-stripe we rolled out a new form that no longer uses the `CardElement` component. We're now just using `CardNumberElement`, `CardExpiryElement`, `CardCVCElement` and I can no longer reproduce the issue either.

**Comment by asolove-stripe** [comment]
Great, I'm glad it's fixed!
