### ISSUE TITLE
Cannot call paymentRequest.show() with Apple Pay, Google Pay works fine. Using React

### ISSUE THREAD

**Issue by binaryst4r** [stripe/react-stripe-elements#335]
Using the react StripeElements `PaymentRequestButtonElement` to complete a checkout on our app. Basically im trying to use `paymentRequest.show` to trigger the dialog manually (async after performing some address validation actions). 

With google, im able to pass the paymentRequest object as an argument and then trigger the `show()` function after doing what i need to do and all is well. For whatever reason, with iOS and apple pay, im unable to call `paymentRequest.show` outside of some gesture handler?

Have you come across a good way to handle this?

Thanks in advance

**Comment by atty-stripe** [comment]
Unfortunately it is a requirement for `show` to be called from within a user gesture handler for Apple Pay. This is documented here: https://stripe.com/docs/stripe-js/reference#payment-request-show.

**Comment by atty-stripe** [comment]
Can you share more about when and how you're triggering your async call? Is it possible to wait for that to happen first, and only then show the Apple Pay button?

**Comment by binaryst4r** [comment]
I am using the Payment Request button to trigger its onclick, in the onClick handler I have the async logic and subsequent call. 

Here is the code:
```<PaymentRequestButtonElement
                      onClick={this.handleInstantPayButtonClick}
                      paymentRequest={this.state.paymentRequest}
                      className="PaymentRequestButton"
                      style={{
                        width: '100%',
                        // For more details on how to style the Payment Request Button, see:
                        // https://stripe.com/docs/elements/paymentrequestbutton#styling-the-element
                        paymentRequestButton: {
                          theme: 'dark',
                          height: '59px'
                        },
                      }}
                    />```

the onClick:

```
handleInstantPayButtonClick = (e) => {
    e.preventDefault()
    makeApiRequest().then((response) => { 
       this.state.paymentRequest.show()
   }
}     
```

Works fine with google pay, not with apple pay.

**Comment by binaryst4r** [comment]
@atty-stripe I am doing the call in the onClick provided by the docs, see above. 

Thank you.

**Comment by atty-stripe** [comment]
Got it. That flow is not supported, unfortunately. Without additional details on what your API request does, I would recommend doing it before the button is shown, or after you receive a source / token.

**Comment by binaryst4r** [comment]
Gotcha, thanks for the response.
