### ISSUE TITLE
createTokening with IbanElement failed

### ISSUE THREAD

**Issue by SergeyShablenko** [stripe/react-stripe-elements#341]
I'm trying to tokenize iban input, but it throws me error

![Selection_280](https://user-images.githubusercontent.com/13334277/55570041-4e371400-570b-11e9-99d0-cd48fd8a5485.png)

Element initialized like this

![Selection_281](https://user-images.githubusercontent.com/13334277/55570082-5e4ef380-570b-11e9-8ee6-f54cd4825e06.png)

to tokenize I'm doing this

```javascript
this.props.stripe.createToken()
```

How can I add currency to the data which stripe tries to tokenize? All I could find in documentation is how to create token like this

```javascript
stripe.createToken('bank_account', {
  country: 'US',
  currency: 'usd',
  routing_number: '110000000',
  account_number: '000123456789',
  account_holder_name: 'Jenny Rosen',
  account_holder_type: 'individual',
})
```

but this is not my case, because I don`t know account number which is inside IbanElement

**Comment by asolove-stripe** [comment]
Hi @SergeyShablenko! The method you're calling as `this.props.stripe.createToken` accepts the same parameters as `stripe.createToken`, just with the type and any data collected by the Element filled in.

So I think you want to call:

```js
this.props.stripe.createToken({ currency: 'eur' })
```

Which React Stripe Elements will turn into a call something like

```js
stripe.createToken('bank_account', {
  currency: 'eur',
  ...dataGatherByTheElement
});
```

Hope that works! Let us know if you run into any further problems.
