### ISSUE TITLE
Is it possible to have something like this PayPal react project

### ISSUE THREAD

**Issue by sunshineo** [stripe/react-stripe-elements#348]
https://github.com/thinhvo0108/react-paypal-express-checkout

My experience with react-paypal-express-checkout is much better than here. After 3 layers of components, all I got are some boxes all messed up on my page. Likely something to do with the react-bootstrap I have in the project.

But with react-paypal-express-checkout , just couple lines of code and you got a working button. Is there something similar for stripe like that? I'm totally OK with pop up window.

**Comment by fred-stripe** [comment]
Hi @sunshineo! I think that's a good suggestion, however, I'm not sure it's a good fit for this library. We designed Stripe Elements for making custom payment fields on an existing checkout form, whereas PayPal Express Checkout appears to add a single button to the page.

This library is a set of React components for integrating credit card fields into an existing React form, which allows full customization over your app's style and appearance.

However, I could see a future Stripe component for the new [Checkout](https://stripe.com/docs/payments/checkout), which provides a similar "one button to checkout" flow that requires little-to-no customization. It's unclear right now whether that component would be part of this library, but it's something we'll think about adding in the future!

**Comment by sunshineo** [comment]
@fred-stripe Thank you very much for your answer. Do you know if there is any existing repo like that for stripe?

**Comment by fred-stripe** [comment]
There is not at this time. For now I'd recommend following the Checkout
instructions and building your own component around the Checkout Javascript
API. As I said—this may be something that we build in the future, but I
don't have a definite timeline for when it'd be available.

**Comment by sunshineo** [comment]
Thank you @fred-stripe for pointing out a direction for me. I'll try to wrap Checkout in a react environment
