### ISSUE TITLE
Minor typo in the documentation

### ISSUE THREAD

**Issue by edward-hong** [stripe/react-stripe-elements#349]
Hi there's a minor typo in the documentation: instead of 'create-react-app' it says 'create react-app' there's a hyphen missing on [this page](https://stripe.com/docs/recipes/elements-react) under step 1:

![Screen Shot 2019-04-21 at 9 26 36 PM](https://user-images.githubusercontent.com/16217130/56468296-916ce300-647e-11e9-87af-29ff770a46a7.png)

**Comment by asolove-stripe** [comment]
@edward-hong Thanks for the report! I'm going to deploy a fix there shortly.

**Comment by asolove-stripe** [comment]
@edward-hong: Actually, this is correct as-is. You can run `create-react-app` as a binary or if running through yarn, you can run [`yarn create react-app`](https://github.com/facebook/create-react-app#yarn).
