### ISSUE TITLE
Server-side rendering exception: ReferenceError: window is not defined

### ISSUE THREAD

**Issue by zackshapiro** [stripe/react-stripe-elements#351]
### Summary

I'm getting intermittent failures where my app will stop working entirely and I'll the the following error: 

> Server-side rendering exception: ReferenceError: window is not defined

To remedy I have to comment out the two files where I import this library, restart my front-end server, refresh the page (works), comment the code back in, refresh the page and now I won't get an error.

Both references to `react-stripe-elements` are in components which are obviously server-side so I'm confused about the error.

Here's the front-end console readout:

```
Exception ReferenceError: window is not defined
    at new Provider (/Users/me/dev/myApp-site/frontend/node_modules/react-stripe-elements/lib/components/Provider.js: 70: 7)
    at processChild (/Users/me/dev/myApp-site/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js: 2829: 14)
    at resolve (/Users/me/dev/myApp-site/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js: 2795: 5)
    at ReactDOMServerRenderer.render (/Users/me/dev/myApp-site/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js: 3175: 22)
    at ReactDOMServerRenderer.read (/Users/me/dev/myApp-site/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js: 3134: 29)
    at ReactMarkupReadableStream._read (/Users/me/dev/myApp-site/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js: 3671: 38)
    at ReactMarkupReadableStream.Readable.read (_stream_readable.js: 449: 10)
    at MultiStream._forward (/Users/me/dev/myApp-site/frontend/node_modules/multistream/index.js: 46: 33)
    at MultiStream._gotNextStream (/Users/me/dev/myApp-site/frontend/node_modules/multistream/index.js: 99: 8)
    at MultiStream._next (/Users/me/dev/myApp-site/frontend/node_modules/multistream/index.js: 85: 10)
    at StringStream.onEnd (/Users/me/dev/myApp-site/frontend/node_modules/multistream/index.js: 120: 10)
    at Object.onceWrapper (events.js: 273: 13)
    at StringStream.emit (events.js: 182: 13)
    at StringStream.EventEmitter.emit (domain.js: 442: 20)
    at endReadableNT (/Users/me/dev/myApp-site/frontend/node_modules/readable-stream/lib/_stream_readable.js: 1010: 12)
    at process._tickCallback (internal/process/next_tick.js: 63: 19)
```

Obviously I can't ship this as-is and I haven't found anything online that could be helpful to fixing this, in this repo or on StackOverflow.

Would love some guidance here. Thanks!

**Comment by atty-stripe** [comment]
Per https://github.com/stripe/react-stripe-elements#server-side-rendering-ssr, this library does not natively support server side rendering. We ask that you follow the instructions in the link to only render the components on the client.

**Comment by zackshapiro** [comment]
Thanks @atty-stripe but as I mentioned in my issue

> Both references to react-stripe-elements are in components which are obviously server-side so I'm confused about the error.

**Comment by atty-stripe** [comment]
Ah, I misunderstood, sorry. Is the `Provider` also being only mounted client-side? It looks like that's the component accessing `window`.

**Comment by zackshapiro** [comment]
You understood correctly, I didn't proof read. My fault 😅 

Yes, the `Provider` is being mounted client-side

```
import React, { Component } from 'react';
import { Elements, StripeProvider } from 'react-stripe-elements';
import CheckoutForm from 'app/payments/components/CheckoutForm';

export default () => {
  return (
    // <div />
    <StripeProvider apiKey="pk_test_sha">
      <div className="example">
        <h1> React Stripe Elements Example </h1>
        <Elements>
          <CheckoutForm />
        </Elements>
      </div>
    </StripeProvider>
  );
};
```

**Comment by atty-stripe** [comment]
Hmm, if all components are being mounted client-side, then I'm not sure where the error is coming from, especially given it mentions `Server-side rendering exception`. Is that error being thrown on the client or on your Node server?

Is it possible for you to create a minimal reproduction in a GitHub repo?

**Comment by zackshapiro** [comment]
Error is being thrown on my client server. 

If I comment out the `import` from `react-stripe-elements`, and just return a `<div>` from that component, and comment out everything in `CheckoutForm` also pertaining to `react-stripe-elements` and restart my client server, page loads fine. When I uncomment them and restart, it breaks again. It's very strange.

Recreating in a minimal repo is going to be complicated. Would prefer not to.

**Comment by zackshapiro** [comment]
FWIW, until I posted this, this was working intermittently, I could comment out, restart, comment in and restart and it would work for a bit, then break. Now it just straight up doesn't work. I haven't changed the components at all in that time, been working in other parts of my app, namely the controller that actually does the charge.

**Comment by zackshapiro** [comment]
I've narrowed it down a bit.

It must have something to do with the `StripeProvider`. As soon as the `StripeProvider` is commented in, the error occurs. When it's commented out, the page loads fine.

**Comment by atty-stripe** [comment]
To be clear, is it the `import` that is causing errors, or the fact that you're rendering the `StripeProvider` in the exported function?

Also, can you share the code where you're actually rendering the exported component? It should only be mounted on the client.

**Comment by zackshapiro** [comment]
It's the fact that I'm using the `StripeProvider`. If I comment out that line but leave in the `import,` the front end renders fine.

In another component (again, rendered front-end), I `import ChargeProvider from 'app/payments/components/StripeProviderWrapper';` and then use it as `<ChargeProvider />` in a `render` function. Nothing crazy

**Comment by atty-stripe** [comment]
I'm sorry, but it looks like your SSR framework is trying to mount the component somewhere, resulting in the error you see (which is not thrown by this library).

So if you can share the code for the parent component that is importing and rendering this component, I can help you debug. What you need to do is to `setState({ renderElements: true })` in `componentDidMount`, and only if `renderElements` is true, should you render the child component.

**Comment by zackshapiro** [comment]
Thanks @atty-stripe. That seemed to do the trick, I'll have to dig deeper into the other aspects of how we render to see what's going on here. When I have some more info, I'll report back to hopefully help anyone else dealing with this in the future. For now, your last comment worked. Appreciate your time and help, have a great day!
