### ISSUE TITLE
Is createPaymentMethod mandatory for handleCardPayment?

### ISSUE THREAD

**Issue by erksch** [stripe/react-stripe-elements#354]
Hey there!

First of all, thanks for the great work on this package!

I am trying to update to the new PaymentIntents API and I was successfully able to create a PaymentIntent on my server, send the `clientSecret` back to my react app and am now trying to use `handleCardPayment` to submit my payment form. 

Since I was used to that react-stripe-elements handles injecting the card information into my methods I used the `stripe.handleCardPayment(clientSecret[, data])` version of the method like this:

```javascript
const { error } = await props.stripe.handleCardPayment(
  clientSecret,
  {
    receipt_email: this.formData.email,
    shipping: { ... },
  },
);
```

The client secret is sent correctly and all but I get the following error response:

```
{
  "error": {
    "code": "payment_intent_incompatible_payment_method",
    "doc_url": "https://stripe.com/docs/error-codes/payment-intent-incompatible-payment-method",
    "message": "A card payment method was expected to be present, but this PaymentIntent does not have a payment method and none was provided. Try again with a payment method or card data.",
    "payment_intent": { ... }
  }
}
```

The card payment method just seems to be missing. My first guess is that I could use ` this.props.createPaymentMethod` to create the card payment method and append it to my `handleCardPayment` call. But the README of this repo says: 
> "You can also use handleCardPayment"

Which indicates that the `handleCardPayment` should work on its own.

Am I doing something wrong?
It is mandatory to create the payment method with `createPaymentMethod` first? If so, it would be nice to give a hint in the README or the Stripe docs.

**Comment by erksch** [comment]
Okay I tried using `createPaymentMethod` before but it is kind of the same problem. Now `createPaymentMethod` fails with 
```
{
  "error": {
    "code": "parameter_missing",
    "doc_url": "https://stripe.com/docs/error-codes/parameter-missing",
    "message": "Missing required param: card.",
    "param": "card",
    "type": "invalid_request_error"
  }
}
```

I am using `react-stripe-elements: v3.0.0` by the way.

**Comment by asolove-stripe** [comment]
Hey @erksch: yikes, that's no good! Your original intuition is right that you should be calling `handleCardPayment` and that should forward along the card data from the Element. You shouldn't need to call `createPaymentMethod` yourself.

If it's alright with you, I'm going to reach out via email and get some details like transaction ids so I can look at what's happening here.

**Comment by asolove-stripe** [comment]
@erksch: looks like there isn't an email on your profile. Can you email me at asolove@stripe.com with a PaymentIntent or Request Id that I can look at?

**Comment by erksch** [comment]
Hey, thanks for the kind answer!

I somehow managed to get it working. The only thing I did change was updating the API version to the latest one in my stripe dashboard. But I guess this would not change a missing card parameter.

But it works now, so I'll close. 
Keep up the great work!

**Comment by jimhill** [comment]
Hey there, we have the same issue. No card details present. We were also on an older API (if that _is_ the issue) and although switched in the dashboard, there is no `setApiVersion ` as suggested in https://stripe.com/docs/building-plugins#set-api-version

**Comment by jimhill** [comment]
In case you land here with the same issue and are using hooks, here's a workaround for the short-term that we are using:

Card in state:
`const [card, setCard] = useState(null);`

Set the state when the card element loads:
`<CardElement onReady={el => setCardRef(el)} />`

And wherever you are sending:
```
await stripe.handleCardPayment(*yourIntentClientSecret*, card, {payment_method_data: {...}});
```

Hope that helps.

**Comment by karaarda** [comment]
@jimhill having the same issue. I have also tried using the refs. However, it causes the following exception:

`Unhandled Rejection (TypeError): cyclic object value
en
https://js.stripe.com/v3/:1:25393
value
https://js.stripe.com/v3/:1:30350
value
https://js.stripe.com/v3/:1:29805
Rr/this._sendCAReq/<
https://js.stripe.com/v3/:1:44714
Rr/this._sendCAReq
https://js.stripe.com/v3/:1:44638
confirmPaymentIntent
https://js.stripe.com/v3/:1:45069
vs
https://js.stripe.com/v3/:1:124983
Tn/<
https://js.stripe.com/v3/:1:35152
value/p<
https://js.stripe.com/v3/:1:137991
sn/<
https://js.stripe.com/v3/:1:26248
`

**Comment by karaarda** [comment]
It was apparently my fault. One should not use the ref, which is a reference to the React object, but the onReady callback which gives access to actual DOM element.

**Comment by giacomoalonzi** [comment]
it doesn't work for me, i'm still getting 
```javascript
{
  "error": {
    "code": "resource_missing",
    "doc_url": "https://stripe.com/docs/error-codes/resource-missing",
    "message": "No such payment_intent: seti_xxxxxxxxxxxxx",
    "param": "intent",
    "type": "invalid_request_error"
  }
}
```

**Comment by asolove-stripe** [comment]
@giacomoalonzi: 

From that error message, it looks like you're trying to confirm a `SetupIntent` (`seti_xxx`) instead of a `PaymentIntent`. To confirm a `SetupIntent`, use `handleCardSetup` instead of `handleCardPayment`.

**Comment by keiraarts** [comment]
Thanks @jimhill, you're a life saver.
