### ISSUE TITLE
PaymentRequestButtonElement doesn't load via ngrok

### ISSUE THREAD

**Issue by avcohen** [stripe/react-stripe-elements#355]
### Summary
Issue : When using the demo repo provided with ngrok for HTTPS as advised in README, the `PaymentRequestButtonElement` does not show up.

I've made no alterations to the demo repo except adding my own test API key in all three locations.

I'm running ngrok with the `--host-header` flag : `ngrok http 8080 -host-header="localhost:8080"`

It seems the `paymentRequest.on('token', ({complete, token, ...data}) => {})` event is not getting back a token as nothing inside this function is firing.

Furthermore, `paymentRequest.canMakePayment().then((result) => console.log(result))` returns `null`. 

### Other information
I know my key works as I _was_ able to get a `PaymentRequestButtonElement` element to show up on a [codepen](https://jsfiddle.net/attystripe/xux7qzch/) once putting in my key.

I've not yet attempted / been able to host this on my own domain which uses a Let's Encrypt SSL certificate. Will report back once able.

**Comment by atty-stripe** [comment]
Hi there, what browser are you using? Also, do you have a saved card in your browser? (In Chrome, you can add one in chrome://settings/payments).

Further instructions for the button to show up: https://stripe.com/docs/stripe-js/elements/payment-request-button#testing

**Comment by avcohen** [comment]
Hi, Atty. Thanks for the quick followup.

I tried this on Chrome, Chrome Mobile, Safari and Safari Mobile (both mobile browsers were iOS). Yes, I do have some saved cards in my browser.

I'll take a peek at the docs noted with a fresh set of eyes and deploy my test version to my domain with a Let's Encrypt SSL and report back.

**Comment by avcohen** [comment]
@atty-stripe I was able to deploy this evening to AWS S3 to a bucket that has a valid SLL cert and still no change.

**Comment by atty-stripe** [comment]
Do you have a repro URL or any console logs to share? Does the button show up on https://stripe.com/docs/stripe-js/elements/payment-request-button? If it does on that page but not yours, likely a problem with your payment methods setup.

**Comment by avcohen** [comment]
There seems to be some inconsistency on my end between when the Payment Request button would show up + a possible misunderstanding on my part of what constitutes a 'Saved Card'

I looked into my saved payment methods in Chrome and they were synced from my Google Wallet account. While this didn't seem to pose any issue on the Codepen posted, at least insofar as getting he button to show up, the payment button would not show up locally with HTTPS via ngrok, on stripe.com or hosted on AWS with HTTPS.

Perhaps this has something to do with the Codepen environment itself that allowed the button to show despite cards not being saved directly to Chrome.

All-in-all, I think this could be closed. Thanks for pointing me in a direction that helped me to figure out the issue.
