### ISSUE TITLE
Documentation is suggesting an unsafe way of handling API keys

### ISSUE THREAD

**Issue by michalczaplinski** [stripe/react-stripe-elements#359]
In the [docs](https://stripe.com/docs/recipes/elements-react#create-form) as well as in the README, the provided code example for `src/App.js` is outright suggesting embedding the api key in the JSX. This makes the API key readable to anyone who can open the devtools with react extension.

Here's the offending snippet: 

```jsx
import React, {Component} from 'react';
import {Elements, StripeProvider} from 'react-stripe-elements';
import CheckoutForm from './CheckoutForm';

class App extends Component {
  render() {
    return (
      <StripeProvider apiKey="pk_test_lalalalalalalalalalalala">
        <div className="example">
          <h1>React Stripe Elements Example</h1>
          <Elements>
            <CheckoutForm />
          </Elements>
        </div>
      </StripeProvider>
    );
  }
}

export default App;
```

I also understand that for the purposes of PCI compliance, the credit card data should *not* pass through my own servers so that rules out sending the credit card info to my own server and making a tokenization call from there. Does the stripe team have a recommendation on how to accomplish both at the same time? Avoid sending user information to my server AND not exposing the API key on the client?

**Comment by the-vampiire** [comment]
the key used client-side is the publishable (public) key. it is not necessary (or possible) to hide htis key. server-side you use your secret key to complete the payment. this is the one you want to keep secret.

the flow is:
- [client] create a payment token  
- [client] send the token `id` property to your server
- [server] create a charge using the token `id` (through a Stripe instance configured with your secret key)
- [server] send back an OK or fail response to the client

**Comment by the-vampiire** [comment]
you never touch the cc information client or server side. this is all handled internally by the stripe lib (the script in your index.html) and the wrapper utilities provided by the stripe client lib. when you are ready to create your token you follow [this process from the docs](https://stripe.com/docs/recipes/elements-react#create-token)

```js
async submit(ev) {
  let {token} = await this.props.stripe.createToken({name: "Name"});

// send the token.id to your server by whatever means youd like
  let response = await fetch("/charge", {
    method: "POST",
    headers: {"Content-Type": "text/plain"},
    body: token.id
  });

// check the response and notify the user (set state etc)
  if (response.ok) console.log("Purchase Complete!")
}
```

**Comment by atty-stripe** [comment]
@the-vampiire is right, the `pk_xxx` is your publishable key, and is safe and expected to be used on your client. You can read more here: https://stripe.com/docs/keys.

**Comment by michalczaplinski** [comment]
Thanks for pointing those out @atty-stripe and @the-vampiire and sorry for the noise! 🙂

**Comment by the-vampiire** [comment]
@michalczaplinski no worries man. when dealing with customer transactions its better to ask than to assume! 

a public / private key pair is used to ensure that both the tokenized payment request (client - creating a token) and the charge request (server - using the created token) are by the same business. on their own neither key is functional, they only work as a pair. 

but the public key is readily available (because nothing can be hidden on the front end, its all client-side). the important one to guard is your server-side private key which completes the pair. never expose that one / check it into git.
