### ISSUE TITLE
<CardElement> (styled or unstyled) displays red line separators between exp/cvc/zip even when valid

### ISSUE THREAD

**Issue by the-vampiire** [stripe/react-stripe-elements#360]
### Summary
`<CardElement>` displays red (invalid?) line separators between expiration / CVC / zip code when viewing in responsive design mode on firefox quantum. happens on all mobile screen widths from ipad (vertical) and below

### Other information

**unstyled (raw `<CardElement>`)**
<img width="338" alt="Screen Shot 2019-06-05 at 7 02 55 PM" src="https://user-images.githubusercontent.com/25523682/58996373-e01fd380-87c5-11e9-8bd9-c44d1aa27c98.png">

**styled with inline style tag**
<img width="352" alt="Screen Shot 2019-06-05 at 7 03 23 PM" src="https://user-images.githubusercontent.com/25523682/58996374-e01fd380-87c5-11e9-8b5c-c2488bac4cde.png">

this is occurring in firefox quantum on OSX - 67.0.1 (64-bit) mobile responsiveness view

**Comment by the-vampiire** [comment]
i just tested this out locally on my phone and it does not appear. so this must be a bug with firefox. on widths > ipad vertical the lines do not appear.

not sure if this should be a separate issue:

when testing on my phone i noticed that clicking in the CreditElement causes a zoom effect on focus. this does not return back to normal zoom level after unfocusing / switching to another input. is there a way to correct this behavior? it looks broken during usage. occurs with and without inline styling.

**Comment by the-vampiire** [comment]
for the second issue this is a problem with safari and inputs that have a font-size < 16px.

i added this meta tag rule `content="user-scalable=0, ..."`  and it restricts this nonsense. despite the name it still allows users to manually zoom / pinch to zoom.

**full tag if anyone needs it**
```html
<meta
  name="viewport"
  content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0, shrink-to-fit=no"
/>
```

[solution from here](https://blog.osmosys.asia/2017/01/05/prevent-ios-from-zooming-in-on-input-fields/)

**Comment by mbarrett-stripe** [comment]
Hi @the-vampiire - we've looked into this and have discovered the root issue. We'll be working on a fix and will let you know when it's ready.

**Comment by asolove-stripe** [comment]
We finally narrowed down the _real_ cause of this problem. It only occurs in Firefox Responsive Design mode, not in actual Firefox (or other browsers) running on native devices. It is caused by the browser-provided base stylesheet for responsive design mode having a few rules that don't match the actual base stylesheet of a native mobile browser. Specifically, there's a rule to add a red outline to invalid text inputs with a very specific selector. This rule is not present in any other situation. We believe this is a bug/oddity of responsive design mode itself.
