### ISSUE TITLE
Please expose StripeProviderProps in typescript definitions

### ISSUE THREAD

**Issue by cmavromoustakos** [stripe/react-stripe-elements#362]
I am using typescript and have a component which looks as follows:

```
interface Props {
  stripe?: any
}

const PaymentInfoForm: FunctionComponent<Props> = ({stripe}) => {
 ```

Ideally I would like to use the type `StripeProviderProps` instead of redefining it locally or using the `any` type.

```
type StripeProviderProps = { apiKey: string; stripe?: never; } & StripeProviderOptions | { apiKey?: never; stripe: stripe.Stripe | null; } & StripeProviderOptions;
```

**Comment by atty-stripe** [comment]
Hi @cmavromoustakos! This library does not ship official TypeScript type definitions. They are community maintained here: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/stripe-v3.

Feel free to open an issue there or contribute a PR!
