### ISSUE TITLE
'change' event is not called after pasting correct card number with same brand.

### ISSUE THREAD

**Issue by storm2513** [stripe/react-stripe-elements#367]
### Summary
'change' event is not called after pasting correct card number with same brand.

### How to reproduce
Paste **4000000000000036** to the card number component.
Then paste **4242424242424242** to this component.
'change' event is not called second time.

![Jul-01-2019 13-20-33](https://user-images.githubusercontent.com/3923930/60429170-27ea1d00-9c03-11e9-96c8-7536dd2a4c95.gif)

https://jsfiddle.net/attystripe/xux7qzch/

**Comment by dweedon-stripe** [comment]
Hi @storm2513 

This is intentional. We only fire `change` events when the payload has changed. In this case, the payload will not have changed. I'm going to close this, but let me know if you have any questions.
