### ISSUE TITLE
Uncaught IntegrationError: Live Stripe.js integrations must use HTTPS

### ISSUE THREAD

**Issue by DennisdeBest** [stripe/react-stripe-elements#392]
### Summary

I have been using Stripe elements for a while and today I was making some changes to my website without any problems all my JS ran fine and at around 7 GMT +1 I got the error you see in the title :

![Selection_094](https://user-images.githubusercontent.com/15683927/61998108-509eee80-b0ab-11e9-8658-b2f86664f26a.png)

Everything still works in my staging and production environments as these are running as HTTPS but it makes local development more difficult.

**Comment by mbarrett-stripe** [comment]
Hi @DennisdeBest - this error appears when you use a Live Mode publishable key with Stripe.js in an environment that isn't being served over HTTPS. In your case, it sounds like you're working in a local environment without HTTPS. This error won't appear if you use a Test Mode key in your development environment.

You can find your test mode publishable key on your dashboard, or by checking out this page while logged in to Stripe: https://stripe.com/docs/keys#api-keys

I hope that helps to clear things up!

**Comment by DennisdeBest** [comment]
Pardon my stupidity I rsynced some configuration the wrong way around, thank you for pointing this out

**Comment by Mkhira** [comment]
what should i do to work in live mode?

**Comment by develalfy** [comment]
@Mkhira  
![image](https://user-images.githubusercontent.com/7834932/103664594-1f526f80-4f7b-11eb-84d4-ee4fe1cda564.png)
