### ISSUE TITLE
Card Brand Ui Element

### ISSUE THREAD

**Issue by ferdinandgoor** [stripe/react-stripe-elements#393]
Hello everybody,

I'm using the separated UI elements to build my Form.

If i'm using the ```CardElement```, the Card Brand Widget appears before the card number input.

I would like the insert this widget in my form even if i'm using the "separated" UI components.

![Capture d’écran 2019-07-29 à 11 49 28](https://user-images.githubusercontent.com/50441480/62039137-615c7b00-b1f7-11e9-8b03-2dbb2c58ffad.png)

Is it possible, maybe i missed something?

I hope i'm clear,

Best regards,

Ferdinand

**Comment by mbarrett-stripe** [comment]
Hi @ferdinandgoor - There's currently no way to show the card brand widget when using the separate card elements. The best way to get that to show would be to use the unified `card` element as you mentioned.

**Comment by ferdinandgoor** [comment]
Thanks a lot for the answer.

Do you plan to add it?

**Comment by mbarrett-stripe** [comment]
It's on our radar, but not something we're currently planning to do in 2019.

**Comment by ferdinandgoor** [comment]
super cool, thanks
