### ISSUE TITLE
Cannot save a card outside of checkout flow with handleCardSetup

### ISSUE THREAD

**Issue by GavBaros** [stripe/react-stripe-elements#395]
Hey Stripe,

I have been following this guide **(please click on 'Saving Cards Outside Checkout Flow tab):** https://stripe.com/docs/payments/payment-intents/migration#saving-cards

The goal was to save a card outside of a checkout flow, and I followed:
1.  Fetch a `client_secret` from my app's backend
2. Pass the `client_secret` to `handleCardSetup` along with `elements`

Here is a simplified example of my frontend code for **fetching:**

```javascript
 const responseWithSecret = await axios().get('/get_my_client_secret')

    try {
      const responseAfterHandleCardSetup = await props.stripe.handleCardSetup(
        responseWithSecret.data.data.client_secret,
        this.element
      )

    } catch (error) {
      console.log('error:', error)
    }

```

**this.element**:
<img width="461" alt="Screen Shot 2019-08-01 at 09 08 53" src="https://user-images.githubusercontent.com/30755017/62276478-09fb1c80-b43c-11e9-8454-642bc132f4e1.png">

But I get the following error:
<img width="386" alt="Screen Shot 2019-07-31 at 17 13 44" src="https://user-images.githubusercontent.com/30755017/62276495-10899400-b43c-11e9-993b-e15d88c9cd90.png">

What might be the issue here?

Thanks

**Comment by callumjh009** [comment]
Hi GavBaros, 

I don't have an answer but I've run into a similar issue, as have a few others. I've been speaking to support about this. Supposedly there is a need to isolate the handleCardSetup() call from the CardElement.

https://github.com/stripe/react-stripe-elements/blob/8b5d1ffb2eaf5235193597b7d4f57349163a12ef/src/components/inject.js#L316
https://github.com/stripe/react-stripe-elements/blob/8b5d1ffb2eaf5235193597b7d4f57349163a12ef/src/components/inject.js#L317
https://github.com/stripe/react-stripe-elements/blob/8b5d1ffb2eaf5235193597b7d4f57349163a12ef/src/components/inject.js#L318

I've tried isolating them this morning (wrapping a checkout form in one `Element`, and calling `handleCardSetup() `from another `Element`. However I've found that `handleCardSetup() `then complains that it can't find a card element when it's isolated in a different element. I'll edit with  a Gist shortly.

**Comment by GavBaros** [comment]
Hey Callum, forgot to mention that `handleCardSetup` is now working for me, the above error is now replaced with the expected success response. I would guess Stripe did some BE update to this by coincidence.

Regarding your issue, perhaps setup two separate `handleCardSetup` ?

**Comment by callumjh009** [comment]
I've spent a bit more time reading about the isolation methods others have discussed in the issues here. Solution was to keep the isolation between the element containing the card and the element calling handleCardSetup(). The final issue was that handleCardSetup(clientSecret,{}) requires a second parameter, an empty object. Without the empty object, it searces and fails to find the now isolated card element. 

Am going to raise an issue about the documentation for creating subscriptions with free trials using react-stripe-elements. Implementing the flow using the regular stripe.js library took about 30 minutes, spent over a day trying to get elements to work with the flow documented in the Stripe docs.

**Comment by GavBaros** [comment]
would passing `elements` (in my case `this.element`) also help? 

I got my solution here from the answer from `dweedon-stripe`: https://github.com/stripe/react-stripe-elements/issues/368

**Comment by GavBaros** [comment]
UPDATE:
It seems I can only use the `handleCardSetup` process once successfully. When I try to add another card again, it gives me the above error once again.

**Comment by GavBaros** [comment]
LATEST UPDATE:
I can no longer add even one card. `handleCardSetup` does not even work anymore for the exact same logic as above. I get:
<img width="294" alt="Screen Shot 2019-08-02 at 09 12 00" src="https://user-images.githubusercontent.com/30755017/62354835-9f161800-b505-11e9-9924-4be4e3b8cc2b.png">

**Comment by mikeshaw-stripe** [comment]
Hey @GavBaros can you try this again? We released an update to the API that allows you to use a PaymentMethod not associated with a Customer on setup. (Not that it wont automatically associated it with the customer. You will have to do that via a call on your backend when this handleCardSetup resolves

**Comment by GavBaros** [comment]
@mikeshaw-stripe , everything works great now; can add 1 or more cards with SCA challenge toggled or just plain test cards. Thanks!

**Comment by paolavness** [comment]
@mikeheaton-stripe can you say where to access the update? I see the last official release `4.0.0` was 28 days ago.
Thank you!
