### ISSUE TITLE
Error message: You did not specify the type of Source or Token to create.

### ISSUE THREAD

**Issue by JonathanWbn** [stripe/react-stripe-elements#40]
I have a basic setup like it is documented, when I call the `createToken` method, I get this error:

_Uncaught Error: You did not specify the type of Source or Token to create. We could not infer which Element you want to use for this operation._

Would appreciate any ideas on how I could tackle this issue.

**Comment by michelle** [comment]
@JonathanWbn would love to see what your setup was! It could be confusing for others, too, and we should fix that.

**Comment by isaacjtullis** [comment]
We are running into the same error message with our react bootstrap modals. @JonathanWbn any code that you can show on how you fixed this?

**Comment by JonathanWbn** [comment]
I'll try my best.
My setup was that my page was rendering multiple cardstacks (react-slick) next to each other, with one of the card in each cardstack having a payment form. (many cardstacks, each has many cards, one of the cards has a payment form with react stripe elements)
I was wrapping each cardstack inside the <Elements> tag from this package, and then this error occured.

My fix was that i didn't wrap each cardstack in the <Elements> tag, but did the wrapping inside the relevant card, wrapping only the form. Since the cards in the lazy loading, this means the <Elements> only get mounted when the user scrolls to the card, as opposed to on loading.

As you might recognise I can't say that I fully understand what's going on here, but I hope this helps.

**Comment by bewestphal** [comment]
I ran into this issue when passing the "injectStripe" high level component into my redux "connect" function. Swapping the order fixed it.

**Comment by richban** [comment]
@bewestphal could you actually how you have done it? I don't understand the order.

**Comment by bewestphal** [comment]
@richban Here is my code, "_PaymentDetailsForm" is my component which contains the payment elements (CardNumberElement, CardExpiryElement, etc.)
```
_PaymentDetailsForm = connect(mapStateToProps)(_PaymentDetailsForm)
_PaymentDetailsForm = injectStripe(_PaymentDetailsForm)
```
This won't work
```
_PaymentDetailsForm = injectStripe(_PaymentDetailsForm)
_PaymentDetailsForm = connect(mapStateToProps)(_PaymentDetailsForm)
```
Hope this helps

**Comment by richban** [comment]
@bewestphal it doesn't unfortunately here is a code snippet:

```javascript
const Cardnumber = connect(
  state => ({
    prop1: state.prop1,
    prio2: state.prop2,
  }), {
  dispatch1,
  dispatch2,
})(CardNumberForm);

export default injectStripe(Cardnumber);

**Comment by richban** [comment]
I still got the same errors as above any idea what's the problem?

```
Uncaught (in promise) Error: You did not specify the type of Source or Token to create.
        We could not infer which Element you want to use for this operation.```

**Comment by fred-stripe** [comment]
Hey @richban would you mind emailing Stripe support with some more details about your application? Ideally include a link to a URL that we can use to test. Or, if you're able to create a minimal page that demonstrates the error and share a gist here, that'd be excellent.

For specific application development questions, the fastest way to get help is to contact Stripe support: <https://support.stripe.com/email/login>

**Comment by keeth** [comment]
I got this error due to a programming error with conditional rendering.. had a case where CardElement was not being rendered inside Elements but createToken was being called.  This error message is not very helpful.

**Comment by atty-stripe** [comment]
@keeth sorry to hear that! Do you want to open a PR to improve the error message? No obligation to — we'll do it otherwise.

**Comment by SergeyShablenko** [comment]
Hi, I`m having similar issue

My component is exported like this
![Selection_258](https://user-images.githubusercontent.com/13334277/55391647-77f10f00-5542-11e9-8ca6-0548acb46877.png)

this is how it looks on page structure, Provider is StripeProvider, just renamed it
![Selection_259](https://user-images.githubusercontent.com/13334277/55391653-7aebff80-5542-11e9-9cae-ae5c007943b2.png)

there is an error

![Selection_260](https://user-images.githubusercontent.com/13334277/55391791-b981ba00-5542-11e9-855a-efe3d0f497d1.png)

this is what I`m doing 

```javascript
this.props.stripe.createToken({ type: 'card' }).then((token, ...args) => console.log(token, args));
```
