### ISSUE TITLE
If you create a PaymentIntent with capture_method manual, is this handled by handleCardPayment?

### ISSUE THREAD

**Issue by sgript** [stripe/react-stripe-elements#400]
As said in the title, if we're using **automatic confirmation** and when creating the `PaymentIntent` object on our backend (we use the Python SDK) , can we proceed with payment on the frontend using `handleCardPayment`? Or are there additional steps involved when `capture_method=True`?

**Comment by asolove-stripe** [comment]
Hi @sgript, if you want calling `handleCardPayment` to also confirm and possibly perform the charge, you should pick automatic confirmation. If you want your server to always do the final confirm and possibly perform the charge, then you should select manual confirmation, then call `stripe.handleCardAction` on the frontend, and then re-confirm from your backend. You can see an overview of the complete steps for each integration in our [manual quickstart](https://stripe.com/docs/payments/payment-intents/migration) and [automatic quickstart](https://stripe.com/docs/payments/payment-intents/migration/automatic-confirmation).

**Comment by asolove-stripe** [comment]
Going to close this, as I hope this is clear now. Please feel free to reopen or get back in touch if you need further help!
