### ISSUE TITLE
SCA Modal is hidden and inaccessible behind browser HTML5 API window

### ISSUE THREAD

**Issue by sverraest** [stripe/react-stripe-elements#406]
### Summary

When combining the HTML5 PaymentAPI for Google Pay or Microsoft Pay on Chrome / Edge and Apple Pay on Safari the SCA modal that pops up after selecting the card in the browser is hidden behind the browser prompt window. You cannot complete the payment as the modal is inaccessible.

### Other information
<img width="405" alt="Screenshot 2019-08-13 at 09 28 01" src="https://user-images.githubusercontent.com/7394603/62926782-17ee5d00-bdad-11e9-9d36-375b90160911.png">

**Comment by asolove-stripe** [comment]
Please see my response in the other issue: https://github.com/stripe/react-stripe-elements/issues/402#issuecomment-520894334 I apologize for offering the wrong advice originally: the [docs you were originally following](https://stripe.com/docs/stripe-js/elements/payment-request-button#complete-payment) were correct and deal with solving this problem.
