### ISSUE TITLE
Uncaught (in promise) undefined

### ISSUE THREAD

**Issue by harvey56** [stripe/react-stripe-elements#408]
Feature request or idea? Consider opening an
[API review](https://github.com/stripe/react-stripe-elements/tree/master/.github/API_REVIEW.md)!

### Summary

I have an implementation very similar to what you have in the demo > async rep. 
When my component loads, the console shows (sometimes) the following error/warning message : 

> Uncaught (in promise) undefined

### Other information

[See here](https://ibb.co/PYjCZ5q)

**Comment by asolove-stripe** [comment]
Yikes, that's not a very helpful error message. Thanks for the report, @harvey56. Can you share more about what you changed relative to the async demo that is causing this to happen?

**Comment by ashatat** [comment]
I am facing the same error message, any luck on what it is about?

![image](https://user-images.githubusercontent.com/18149438/64480115-6d5e3400-d1ca-11e9-94ad-6cc472b3ff25.png)

**Comment by harvey56** [comment]
@ashatat No luck. It logs in the console, sometimes. Not on every loading. Loading the Stripe script works regardless, in my case. So does creating a new customer/plan/subscription etc... on Stripe. 

I'm only worried about what it means. It seems to me the issue comes from the Stripe script.

The errors point to lines [1418, 1446](https://ibb.co/YQcwFNW), [1514](https://ibb.co/7XdhkTM)

@asolove-stripe 

I mount an  `AsyncStripeProvider` wrapper component that is in charge of loading the stripe script (as documented here : https://gist.github.com/mrcoles/8c79595f488f0e334e528163feb23293).

I then add the `Elements` and `MyForm` children components as follows : 

```
<AsyncStripeProvider apiKey={process.env.REACT_APP_STRIPE_KEY}>   
  <Elements>
    <MyForm />                              
  </Elements>
</AsyncStripeProvider>
```

**Comment by markgarbers** [comment]
I've come across the same issue... I've been able to consistently replicate it by throttling the connection speed of my browser, that makes the error occur every time.

**Comment by stevez86** [comment]
I'm also getting this issue. I notice it when I test on slow internet connections and not on faster ones

**Comment by markgarbers** [comment]
@asolove-stripe any joy in replicating the issue and/or issuing a fix?

This appears to be a bug in live code, which isn't ideal.

**Comment by andressakalil** [comment]
@asolove-stripe I also have the same problem when the internet connection is poor. Any updates on this one?

**Comment by ShenLanJohn** [comment]
same issue here also.  
"Uncaught (in promise) undefined"

**Comment by sdarnell** [comment]
FYI I've seen this appearing recently on lots of sites, and despite trying to diagnose it in my own app, I now believe it is related to a browser plugin. The error even appears on stackoverflow.com, but if I disable the 'Office' chrome extension ver 2.1.0 (chrome://extensions/?id=ndjpnladcallmjemlbaebfadecfhkepb ) the problem goes away.

**Comment by markgarbers** [comment]
I don't use any Office extensions and still get the error on slow connections... so not sure it's related to a particular plugin.
Although it could be that the Office plugin is creating the conditions for the error to occur (e.g. slowing down the connection or doing something else that freaks Stripe out).

**Comment by BraulioBracamonte** [comment]
> FYI I've seen this appearing recently on lots of sites, and despite trying to diagnose it in my own app, I now believe it is related to a browser plugin. The error even appears on stackoverflow.com, but if I disable the 'Office' chrome extension ver 2.1.0 (chrome://extensions/?id=ndjpnladcallmjemlbaebfadecfhkepb ) the problem goes away.

This worked for me

**Comment by rpaschal** [comment]
> I don't use any Office extensions and still get the error on slow connections... so not sure it's related to a particular plugin.
> Although it could be that the Office plugin is creating the conditions for the error to occur (e.g. slowing down the connection or doing something else that freaks Stripe out).

This worked for me as well.

**Comment by philipimperato** [comment]
This is still an issue for me for slow connections.

**Comment by sashko-stripe** [comment]
Closing this as this project has migrated to [React Stripe.js](https://github.com/stripe/react-stripe-js) as of early 2020, which also has a somewhat different API and implementation. If this still happens in the new library, please re-open it there.
