### ISSUE TITLE
IntegrationError and how to add callbacks through parent containers

### ISSUE THREAD

**Issue by lesreaper** [stripe/react-stripe-elements#411]
Getting this error:
`IntegrationError: You cannot update Payment Request options while the payment sheet is showing`. Can't find any information on it.

Using the build-card example to test our integration. You can see the example here: https://i.imgur.com/KZGDC49.png

I'm building PaymenRequest API Button, and straight from the docs, I use: 
```
paymentRequest.on('token', ({ complete, token, ...data }) => {
            console.log('Received Stripe token: ', token);
            console.log('Received customer information: ', data);
            complete('success');

            // This is the called function to handle the passing of the generated tokens
            // and info to our back end, as well as continue to the confirmation screen
            this.handlePayment({ data, token });
        }
);
```

I have to change some of the values in the returned data object and then submit that to our backend to process. I only included the prop call to show the part that generates an error.
```
  handlePaymentInfo = ({ data, token }) => {
        const { onSubmit } = this.props;

        onSubmit({
            token,
            card: token.card,
            data
        });
    };
```

The `onSubmit` comes from the parent container. For some reason, this throws the error, and I have no idea how to fix it based on the error. Shouldn't you be able to call prop functions when someone clicks on pay?

**Comment by asolove-stripe** [comment]
Hi @lesreaper: that seems like an unfortunate error message, sorry for the confusion!

My first thought is that it seems like something in your `token` event callback is causing you to change state and re-render the PaymentRequestButton component with different options. They might be "different" in some trivial way, like the same options but inside a different-in-memory object or array. Is it possible that `handlePaymentInfo` or `onSubmit` are doing anything that changes state and causes a re-render?

**Comment by lesreaper** [comment]
Thanks for the fast feedback @asolove-stripe !

Yes, there is a state change in the token callback. It's used to both setState for the token data for further use in the checkout process, as well as to navigate to the next step in the checkout process. If I disable the setState, it will then give me a different error  (which isn't what we're dealing with here). Pseudocode:
```
   handleSubmit = data => {
        const { navigate } = this.props;
        this.setState(data);
        navigate("/next-step");
    };
```
I don't understand how to perform actions on the token that affect state like this. All the calls for what to do with the token data happen inside the `paymentRequest.on` function, but you can't modify anything related. It doesn't seem like there's a way to do anything with the token data after you get it. Is there a process I'm not understanding?

**Comment by asolove-stripe** [comment]
The error message you're seeing is specifically about something in the token event then updating state and changing the props you pass to the PaymentRequestButton element while the payment sheet is still showing. 

Inside the token event, I would expect that you send the token to your server or do something else to actually charge the card (which will involve doing it asynchronously), then after that completes you call the `success` callback to dismiss the payment sheet, and then after that you navigate to any changes in your UI. If that is what you're doing and you're still seeing this error, then I'm a bit stumped and might need more detail.

**Comment by lesreaper** [comment]
Yes, that is exactly what I'm trying to do in the token event, except instead of charging it right away, we're taking the UI to a confirmation step. 

Using debugger, I can see the flow dies when I do the `this.setState(data);` in the `handleSubmit`, since there's some data that forces a re-render. However, that `handleSubmit` function call happens AFTER `complete('success');` in the token process. I even tested an async/await version like this and still get the error: 

```
        paymentRequest.on('token', async ({ complete, token, ...data }) => {
            console.log('Received Stripe token: ', token);
            console.log('Received customer information: ', data);

            try {
                await complete('success');
                this.handlePaymentInfo({ data, token });
            } catch (err) {
                 console.log(err)
            }
        });
```

**Comment by asolove-stripe** [comment]
Hmm, I've got an example app that does pretty much that same thing, and does not trigger that error. Can you share any more code or a hosted example? (If it needs to be private, you can find me at asolove@stripe.com.)

**Comment by lesreaper** [comment]
Thank you, I sent an email.

**Comment by sashko-stripe** [comment]
Closing this as this project has migrated to [React Stripe.js](https://github.com/stripe/react-stripe-js). If you believe this is still important, please re-open it there.
