### ISSUE TITLE
Can't get card details in response after handleCardPayment Stripe request

### ISSUE THREAD

**Issue by bebebeka** [stripe/react-stripe-elements#418]
Guys, I changed usage of your component by docs to support SCA
#### injection `stripev3` into hmtl <body>: 
```
<script src="https://js.stripe.com/v3/"></script>
```
#### into my react app:
```
      <Elements>
      	<StripePaymentForm > // with injectStripe HOC
      		<CardNumberElement />
      		<CardExpiryElement />
      		<CardCVCElement />
      	</StripePaymentForm>
      </Elements>
```
###  into backend (PHP: "stripe/stripe-php": "^6.43") side:
 - route for paymentIntent creating (+`customerid` if exist and 'setup_future_usage' = 'off_session' arguments) ( `PaymentIntent::create` )
 - route for `add card` after success payment with `payment mehtod attaching to customer` 
```
$stripe_payment = PaymentMethod::retrieve($payment_method);
$stripe_payment->attach(['customer' => $paymentUserId] );
```
my steps:
1) created paymentintent into backend by loggedin user .
2) create handleCardPayment (with `clientSecret` after paymentIntent creating) after filling stripe's elements (CardNumberElement, CardCVCElement, CardExpiryElement)

I see in admin panel payments and customers but can't to get card details into server response and I'm not sure that I made correct implementation (based on comment  https://github.com/stripe/react-stripe-elements/issues/215#issuecomment-515491674 )

**Comment by MusabAkram** [comment]
try this it worked for me. https://github.com/stripe/react-stripe-elements/issues/354#issuecomment-492995707

**Comment by sashko-stripe** [comment]
Closing this as this project has migrated to [React Stripe.js](https://github.com/stripe/react-stripe-js). If you believe this is still important, please re-open it there.
