### ISSUE TITLE
How to pass a customer data in handleCardPayment?

### ISSUE THREAD

**Issue by Valentin1918** [stripe/react-stripe-elements#419]
I made several test payments using handleCardPayment, seems they passed normally, but in stripe account there is no customer information.

handleCardPayment under hood create new paymentMethod, but v1/payment_intents/pi_id/confirm doesn't return a "customer" field.

I decided to create a paymentMethod with stripe.createPaymentMethod, pass it to my backend, where we attached a customer. The id of this paymentMethod I tried to pass in handleCardPayment like { payment_method: paymentMethod.id }, but received a following error : "When calling handleCardPayment on an Element, you can't pass in a pre-existing PaymentMethod ID, as a PaymentMethod will be created using the Element."

How to create a paymentMethod with customer data by using handleCardPayment?

In advance thank you.

**Comment by bebebeka** [comment]
What customer data do you mean?
I guess you need to create new customer in your backend (you can use `metadata` or `description` arguments to save some additional data ) and to attach stripe's `payment_method_id` to it.
Another way: to create customer user in your backend side before backend's paymentIntent creating and pass customer's data to your FE together with `client_secret_id`.
I hope it helped :)

**Comment by Valentin1918** [comment]
Under customer data I mean created customer with email. 
We do exactly the same. On back was created a customer and attached to paymentIntent, and received client_secret_id I passed in stripe.handleCardPayment(client_secret_id, data). I tried also wo data.
The problem is, that stripe.handleCardPayment creates an another paymentMethod (without customer's data) instead this one, which was created on back.

**Comment by Valentin1918** [comment]
Instead of Destination Charges we used Direct Charges on back.
Together with apiKey we transferred on front a connectedAccountId.

Instead of passing apiKey in StripeProvider as attribute, I made a stripe object:
`const stripe = window.Stripe(stripeKey, { stripeAccount: connectedAccountId });`
and passed it to StripeProvider:
`<StripeProvider stripe={stripe}>`
