### ISSUE TITLE
Too complicated

### ISSUE THREAD

**Issue by armetiz** [stripe/react-stripe-elements#42]
Hi team;

I'm using React with Redux; I'm used to separate component and container.
I think this component is too complicated to use.

What I was expected was very simple :

```javascript
<StripeSourceElement onSourceCreated={::this.handleSourceCreated} publicKey="pk_test" type="card" />
<StripeTokenElement onTokenCreated={::this.handleTokenCreated} publicKey="pk_test" type="card"/>
```

Regards.

**Comment by jenan-stripe** [comment]
Hi @armetiz. Thanks for the feedback! Elements doesn't create tokens or sources for you right now (although it may in the future) because you'll usually want to hook up source creation to the rest of your form. For now, you'll have to call `createToken`/`createSource` yourself.
