### ISSUE TITLE
Can the authentication modal be tracked?

### ISSUE THREAD

**Issue by joeltaylor** [stripe/react-stripe-elements#420]
### Summary

Is it possible to track if the authentication modal pops up? I wasn't able to find anything.

Specifically, I'm using `handleCardSetup` with a `SetupIntent` and it'd be great to know if a user is prompted to authenticate. I know I can determine if authentication succeeds/fails, but that doesn't help me measure if authentication during the check-out process causes customers to drop off.

**Comment by mbarrett-stripe** [comment]
Hi @joeltaylor - if you're using `handleCardSetup`, that is the totally automated flow, and there's no hook into showing an authentication modal. If you'd like more control over the flow, you can look into using [`confirmSetupIntent`](https://stripe.com/docs/stripe-js/reference#stripe-confirm-setup-intent) which returns a payload that would indicate if more work needs to be done to confirm the intent.

I hope that helps. If you need more information and it's not specifically related to React Stripe Elements, you can contact our support team who can help you out further!
