### ISSUE TITLE
Autofill all form elements

### ISSUE THREAD

**Issue by matihabbas** [stripe/react-stripe-elements#423]
### Summary

Bumping an issue mentioned in https://github.com/stripe/react-stripe-elements/issues/280#issuecomment-444148807 (Request 1). This is still not possible to do using elements. Any info regarding if this is being pursued?

### Other information

Unable to use [`input`](https://developers.google.com/web/updates/2015/06/checkout-faster-with-autofill) where it works flawlessly.

**Comment by mbarrett-stripe** [comment]
Hi @matihabbas - this is something we're tracking internally but do not currently have a delivery timeline to share. I've noted your ask for this as well. Thanks!
