### ISSUE TITLE
typescript - typing bug with respect to stripe.createToken({})

### ISSUE THREAD

**Issue by zeuslawyer** [stripe/react-stripe-elements#425]
### Summary
The [README](https://github.com/stripe/react-stripe-elements) for react-stripe-elements indicates that this format is ok: 
```javascript
  // You can also use createToken to create tokens.
    // See our tokens documentation for more:
    // https://stripe.com/docs/stripe-js/reference#stripe-create-token
    this.props.stripe.createToken({type: 'card', name: 'Jenny Rosen'});
```
it contemplates passing in an options object with a property called `type`, but the typings module for this library has token options defined as follows:
```
interface TokenOptions {
        name?: string;
        address_line1?: string;
        address_line2?: string;
        address_city?: string;
        address_state?: string;
        address_zip?: string;
        address_country?: string;
        currency?: string;
    }
```

as a result there is a typescript error that gets thrown when we use it as recommended in the README file.  

### Other information
Getting around this currently by using ` // @ts-ignore` right above first entry in the options object' so my code looks like this, which seems to work:
```
 if (this.props.stripe) {
      const tokenResponse = await this.props.stripe.createToken({
        // @ts-ignore  -- this is needed due to a bug in the type defs for createToken?
        type: "card"
        // name: "Cardholder Name?",
        // email: "cardHolder@email.com"
      });
```

**Comment by mbarrett-stripe** [comment]
Hey @zeuslawyer - never fun to run into typing issues.

Unfortunately we do not currently provide 1st party TypeScript definitions for React-Stripe-Elements. The existing definitions are community managed, so our advice is to bring this to the attention of the [type definition maintainers](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-stripe-elements).
