### ISSUE TITLE
Add support for handleCardAction

### ISSUE THREAD

**Issue by yamsellem** [stripe/react-stripe-elements#426]
### Summary

As proposed in [this pull request](https://github.com/stripe/react-stripe-elements/pull/399), add support for `handleCardAction`. Without this the SCA manual flows are not available in `react-stripe-elements`.

As stated in the docs "Manual confirmation [is] the easiest way to migrate from the Charges API". We'll be a lot to migrate in these early days of September, so this will be of great help (as now, I'll love to use bombek92 code to start migrating, but because it's typescript I cannot add it's repo to package.json).

**Comment by yamsellem** [comment]
The SCA entering in action this Saturday, may you please take a quick look on this one?
It'll be a life saviour!

**Comment by yamsellem** [comment]
@cweiss-stripe @dweedon-stripe @jez @atty-stripe I'm sorry to bother, I've found you've been the top contributors of this repo. Please, can you take a look at this issue?

It seems only a couple of line of code — [a pull request already exists](https://github.com/stripe/react-stripe-elements/pull/399) — but without `handleCardAction`, the sca manual confirmation flow is not available. Without it, the 14 September SCA introduction is way harder to handle properly in the time remaining.

Thanks a lot.

**Comment by yamsellem** [comment]
After a complete test, even if the `handleCardAction` is missing from `react-stripe-elements` and not documented there, a call from it to this method works.

So, this issue is not so urgent anymore.
So sorry for the unneeded big warning.

**Comment by cweiss-stripe** [comment]
Hi @yamsellem 
Thank you for reporting this and I'm glad you managed to find a workaround for now.
We'll add proper support for it soon and will update you once it is done.

**Comment by cweiss-stripe** [comment]
After thinking about this some more and syncing with my colleagues, we realized that it does not make sense to add a wrapper for `handleCardAction` to react-stripe-elements, since it does not require an Element.
The approach you are currently using is the correct one. We will look into improving the docs to make this more obvious.
