### ISSUE TITLE
Installation issue with npm and v0.0.3

### ISSUE THREAD

**Issue by szeller** [stripe/react-stripe-elements#43]
If I try to install the latest version using npm `3.10.10`, I get the following error
```
npm ERR! cb() never called!
```

I installed `0.0.2` and it worked fine.

**Comment by jenan-stripe** [comment]
I can reproduce. Looks like the upload might have failed. Investigating. Hold tight!

**Comment by jenan-stripe** [comment]
@szeller I cut a new release. Should work now! Please let us know if you have any more issues.

**Comment by szeller** [comment]
Yep.  That cleared up the issue I was seeing.
