### ISSUE TITLE
createPaymentMethod fails on IE11

### ISSUE THREAD

**Issue by gyurj** [stripe/react-stripe-elements#430]
Hi folks,
First of all thanks for the great library. It really helped us.
Unfortunately we have an issue on IE11 (v.3.0.0, but its also available in v.5.0.0), where `createPaymentMethod` generates exception that `.include` function is not supported. 
I've checked the codebase and found that in `inject.js` file on [this](https://github.com/stripe/react-stripe-elements/blob/606d506e2b38201346eb0bff202be2d58ebd423f/src/components/inject.js#L235) line...
```
if (!['card'].includes(paymentMethodType)) {
        throw new Error(
          `Invalid PaymentMethod type passed to createPaymentMethod. ${paymentMethodType} is not yet supported.`
        );
      }
```
Could you please replace it with IE11 compatible `indexOf` please? It seems to be the only usage, so the rest should be fine.

Thanks in advance,
Narek

**Comment by dweedon-stripe** [comment]
👋Thats no good. Thanks for catching this! We just shipped a fix for this on v3, v4, and v5 (all versions affected by this bug). Let me know if you see any other issues.

Thanks!
