### ISSUE TITLE
Update latest tag in npm?

### ISSUE THREAD

**Issue by moretti** [stripe/react-stripe-elements#433]
### Summary

I just installed [`react-stripe-elements`](https://www.npmjs.com/package/react-stripe-elements) from npm and I noticed that the latest version is `3.0.1`:

<img width="360" alt="Screenshot 2019-09-19 at 13 17 28" src="https://user-images.githubusercontent.com/1186409/65239924-5a0f6a80-dae0-11e9-9edd-1a01b48cc011.png">

even if v4 and v5 are published. Are v4 and v5 considered experimental?

**Comment by BuusMuus** [comment]
Just ran npm, went back to version 3.0.1. The whole thing stopped working. SMH

**Comment by oliver-stripe** [comment]
Sorry all, this should be fixed now.

**Comment by moretti** [comment]
Thank you! 🎉
