### ISSUE TITLE
CardNumberElement is generating the iframe without <head> tag in IE11

### ISSUE THREAD

**Issue by lissod** [stripe/react-stripe-elements#434]
### Summary
On IE11, the iframe generated by CardNumberElement is not having an html, body or head tag. The  custom styles are being appended to the iframe src tag.

```html
<iframe  title="Secure payment input frame" src="https://js.stripe.com/v3/[rest of the url].html#style[base][textAlign]=right&amp;style[base][fontSize]=14px&amp;style[base][::placeholder][color]=%23a1a1a1" allowtransparency="true" allowpaymentrequest="true" ...></iframe>

```

IE11 only, working fine in Chrome.

Using version: `^2.0.1`

**Comment by oliver-stripe** [comment]
@lissod Thanks for the report. We'll take a look.

**Comment by oliver-stripe** [comment]
@lissod I haven't been able to reproduce this. The styles seem to be appropriately applied. Could you provide an example on something like https://jsfiddle.net/ or https://codesandbox.io/?

**Comment by oliver-stripe** [comment]
Closing this for now, but please feel free to reopen or make a new issue with a repro.
