### ISSUE TITLE
HandleCardSetup Not Sending Data

### ISSUE THREAD

**Issue by JVannucc** [stripe/react-stripe-elements#435]
### Summary
When trying to use the handleCardSetup method, card data is not being sent to the api.

Have checked handleCardPayment and createToken and both of these are sending the card data through.

My component is below:

`import React, { useEffect, useState } from "react";
import { CardElement, injectStripe } from "react-stripe-elements";

const CheckoutForm = props => {
  const [intent, setIntent] = useState("");

  useEffect(() => {
    axios
      .post('/payment-method-intents')
      .then(({ data }) => setIntent(data.data));
  }, []);

  const submit = () => {
    props.stripe.handleCardSetup(intent.client_secret).then(data => console.log(data));
  };

  return (
    <div className="checkout">
      <CardElement />
      <button type="button" onClick={submit}>
        Purchase
      </button>
    </div>
  );
};

export default injectStripe(CheckoutForm);`

the data being sent through is:

`{
    use_stripe_sdk:true,
    expected_payment_method_type:'card',
    key:xxxx,
    client_secret:xxxx
}`

**Comment by oliver-stripe** [comment]
Hi @JVannucc could you provide a repro on something like https://codesandbox.io/ ?

**Comment by JVannucc** [comment]
Sorry, for some reason when I installed the package it was version 3.0.1, have upgraded to 5.0.1 and all is working!

Thanks for your reply anyway. Appreciate it!
