### ISSUE TITLE
Issues with styling CardElement with styletron and Baseweb

### ISSUE THREAD

**Issue by matchatype** [stripe/react-stripe-elements#436]
I've been quite successful at styling the component to integrate it with styletron and [Baseweb](https://baseweb.design), but I'm not able to replicate styles for pseudo-classes so, with my current implementation I am not able to pass the correct styling to the parent... because of how styletron works. Here is how I implemented `CardElement`:

```
<FormControl label="Credit card details">
  <Block
    $as={CardElement}
    className={useCss({
      backgroundColor: theme.colors.mono300,
      borderRadius: theme.borders.radius200,
      borderWidth: theme.sizing.scale0,
      borderStyle: theme.borders.border100.borderStyle,
      borderColor: theme.colors.mono300,
      paddingBottom: theme.sizing.scale400,
      paddingLeft: theme.sizing.scale550,
      paddingRight: theme.sizing.scale550,
      paddingTop: theme.sizing.scale400,
    })}
    style={{base: {...theme.typography.font300}}}
  />
</FormControl>
```

and here is how it looks next to a regular Baseweb component.

<img width="892" alt="CleanShot 2019-09-25 at 14 28 44@2x" src="https://user-images.githubusercontent.com/28128/65600730-ff26b900-dfa0-11e9-8f32-d76658eebded.png">

Probably my implementation is not correct, and I can achieve the desired result by simply hooking in the style prop of the CardElement itself, but I've not been successful that way. Any idea on how could I set styles for the container, so I can change settings for border, backgroundColor and transition on focus? Here is an example:

![Screen Capture on 2019-09-25 at 14-51-41](https://user-images.githubusercontent.com/28128/65602413-203cd900-dfa4-11e9-9ab0-ca4e2c4689e3.gif)

**Comment by oliver-stripe** [comment]
I'm not familiar with styletron, but we have examples of styling the input on focus at https://stripe.dev/elements-examples/ that you can use as a guide.

Outside of that, if programmatically determining focus/blur can be useful (such that you can track the state yourself and adjust variables/classes/etc/ accordingly), there are events you can subscribe to: https://stripe.com/docs/stripe-js/reference#element-on

**Comment by matchatype** [comment]
@oleolek-stripe That did the job, thank you for the tip! However, it would be great if you could expose some sort of api for the parent too, so these kind of things can be set easily without much overhead.

**Comment by oleolek-stripe** [comment]
I think it should be @oliver-stripe
