### ISSUE TITLE
Missing method handleCardAction

### ISSUE THREAD

**Issue by yankopetrov** [stripe/react-stripe-elements#444]
`handleCardAction` method is missing.

https://stripe.com/docs/stripe-js/reference#stripe-handle-card-action

Do you plan to add it soon?

**Comment by fred-stripe** [comment]
Hi @yankopetrov, great question! You can actually call `this.props.stripe.handleCardAction` from inside an `injectStripe` HOC—any underlying Stripe.js methods can be called:

https://github.com/stripe/react-stripe-elements#example

> Within the wrapped component, the stripe prop has the type:
```
type FactoryProps = {
  stripe: null | {
    createToken: …,
    // and other functions available on the `stripe` object,
    // as officially documented here: https://stripe.com/docs/elements/reference#the-stripe-object
  },
};
```


As a quick example, you'd write something like:
```
class CheckoutForm extends React.Component {
  render() {
    /* ... */
  }
  onCompleteCheckout() {
    /* … other steps to attach a payment method, etc … */

    this.props.stripe.handleCardAction(clientSecret).then((result) => {
       if (result.error) {
           // Display error to your customer
       }
       else {
          // Success, do something with result.paymentIntent
       }
    });
  }
}

const InjectedCheckoutForm = injectStripe(CheckoutForm);
```
