### ISSUE TITLE
iDEAL select bank change dropdown icon 

### ISSUE THREAD

**Issue by johnhult** [stripe/react-stripe-elements#446]
Hi! Love the work you've done. I was just wondering if there's any way to change the icon that is rendered inside the dropdown for iDEAL bank. I don't mean the images for the different banks, but rather the "dropdown icon" that is to the right, that today is made up by two arrows. Would it be possible to implement this?

**Comment by mbarrett-stripe** [comment]
Hello @johnhult. Thanks for the feedback! Issues in this repo are for react-stripe-elements specific issues. You can send a message to our support team via https://support.stripe.com if you'd like to request features for Stripe Elements, which this repo just wraps in a React-friendly wrapper.
