### ISSUE TITLE
Testing Stripe with Jest-Puppeter

### ISSUE THREAD

**Issue by santaclauze** [stripe/react-stripe-elements#452]
First of all thanks for this package. Its saving me a lot of fo time and I'm looking forward to the next implementations (such as an Element that I can customize rather than being stuck with the predefined ones). But that is a problem for another day.

Right now I am trying to test Stripe with `jest-puppeter` and I can't seem to find a way to fill the form.

Simple methods are provided to accomplish those tasks such as `await expect(page).toFillForm(${selector}, { key: value }` where the key is the input name and the value is what I wish to fill the form with.

This normally works on other forms and you have provided a name for the inputs as well, yet I cannot find a way to fill the `CardElement`.

Does anyone have experience or is there a way to accomplish this??

THanks a lot.

**Comment by oliver-stripe** [comment]
Hi @santaclauze I don't have any direct experience with writing the tests you're describing, but there's another issue that has an example of a puppeteer test. Perhaps that will help you! https://github.com/stripe/react-stripe-elements/issues/137

**Comment by sashko-stripe** [comment]
Closing this as this project has migrated to [React Stripe.js](https://github.com/stripe/react-stripe-js). If you believe this is still important, please re-open it there.
