### ISSUE TITLE
confirmCardSetup support?

### ISSUE THREAD

**Issue by thomasdohyunkim** [stripe/react-stripe-elements#455]
I was looking at the tutorial on "Saving card details without payment" (https://stripe.com/docs/payments/cards/saving-cards-without-payment#submit-card-details-web), and I noticed that the function used to save the card changed from `handleCardSetup` to `confirmCardSetup`. Will react-stripe-elements support `confirmCardSetup` as `handleCardSetup` is now deprecated? And is it still okay to use `handleCardSetup` when the api docs indicate that it's deprecated?

**Comment by maximematheron** [comment]
Hi @TdhyunK, did you find an answer to your question?
