### ISSUE TITLE
Ability to set `required` (or `aria-required=true`) on the input elements

### ISSUE THREAD

**Issue by leslchan** [stripe/react-stripe-elements#457]
### Summary

There are already existing aria tags for accessibility on the input fields like "aria-label" and "aria-invalid" (thank you!). 

Can the CardElement also support adding the "required" attribute to the input field based on an input prop?

(Note: Modern screen readers can understand the simplified `required` attribute, but `aria-required=true` works too.)

**Comment by mbarrett-stripe** [comment]
Hi @leslchan! Happy to see your interest in further `aria-` attributes. That would be a feature request for Stripe.js Elements itself. If you'd like to, please reach out to [our support team](https://support.stripe.com/email) with your suggestion. This repo's issues are for the react wrapper around Stripe.js itself, so we cannot take action here at this time.
