### ISSUE TITLE
Call to paymentRequest.canMakePayment returns false in Cordova webview

### ISSUE THREAD

**Issue by skvariljan** [stripe/react-stripe-elements#459]
We are currently using react-stripe-elements v2.0.3 in our app.

The following code logs `true` in Safari on iPhone with activated ApplePay.

```
paymentRequest.canMakePayment()
    .then(result => {
        console.log(result && result.applePay)
    })
```

Nevertheless, the same code logs `false` when running in Cordova webview.

Would upgrade to react-stripe-elements v6.0.1 help? What else can we do to make ApplePay/GooglePay detection work in Cordova webview?

**Comment by mbarrett-stripe** [comment]
Hi @skvariljan -

This repo just wraps Stripe.js with a react-friendly API. Upgrading to the latest version, while useful in general, does not change the functionality of the `paymentRequest` API.

Please reach out to [our support team](https://support.stripe.com/email) for help with the Stripe.js integration.
