### ISSUE TITLE
Suggestion: use Rollup rather than Webpack for bundling

### ISSUE THREAD

**Issue by tstirrat15** [stripe/react-stripe-elements#460]
### Summary
The conventional wisdom is [rollup for libraries, webpack for applications](https://medium.com/webpack/webpack-and-rollup-the-same-but-different-a41ad427058c). There's less of a difference between the two than there used to be, but it wouldn't surprise me if there were some bundle size gains to be made by getting rid of the webpack runtime.

Thoughts?

**Comment by dweedon-stripe** [comment]
Thanks @tstirrat15, we are indeed planning to move to Rollup. 👍
