### ISSUE TITLE
IBAN + createSource: cannot pass element to createSource

### ISSUE THREAD

**Issue by freen** [stripe/react-stripe-elements#464]
### Summary

The `StripeShape` -- just like the Stripe.js SEPA [quick start](https://stripe.com/docs/stripe-js/elements/iban#create-source) and [API docs](https://stripe.com/docs/stripe-js/reference#stripe-create-source) --  hints that `createSource` optionally accepts an Element as the first argument of `createSource`: https://github.com/stripe/react-stripe-elements/blob/91c465c95927dad429f9eba27398607dfdff2f2f/src/decls/Stripe.js#L31

```typescript
declare type StripeShape = {
  elements: (options: MixedObject) => ElementsShape,
  createSource: (
    element: ElementShape | MixedObject,
    options: ?{}
  ) => Promise<{source?: MixedObject, error?: MixedObject}>,
```

However when I run `stripe.createSource(iban, sourceData)`, per the below code snippet, I get an error saying that I have not passed a `type` option:

![Captura de Pantalla 2019-11-19 a la(s) 3 44 44 p  m](https://user-images.githubusercontent.com/1816457/69187049-cbbb6300-0ae7-11ea-803a-298f73062d52.png)

Indeed, per source, the injected `wrappedCreateSource` **does *not* support passing an Element as the first argument of `createSource`:** 

https://github.com/stripe/react-stripe-elements/blob/91c465c95927dad429f9eba27398607dfdff2f2f/src/components/inject.js#L198

Here we see that `createSource` _only_ accepts an options object. The element variable is supposedly inferred later in the method, but this doesn't work either.

### Excluding `iban` from `createSource`, to be inferred in `wrappedCreateSource`, also doesn't work

If I simply provide `sourceData` as the first argument, and no `iban`, like so:

```javascript
return stripe
  .createSource(sourceData)
  // ...
```

RSE doesn't find the contextual `IBANElement`, and just sends the request without the IBAN number, resulting in this response:

```json
{
  "error": {
    "code": "missing_parameter",
    "message": "The payment method `sepa_debit` requires the parameter: sepa_debit[iban].",
    "param": "sepa_debit[iban]",
    "type": "invalid_request_error"
  }
}
```

### Relevant snippet from my app

```javascript
componentDidMount() {
  const {setClick, country, stripe, locale} = this.props;

  const options = {
    supportedCountries: ['SEPA'],
    placeholderCountry: country
  };
  const elements = stripe.elements({locale});
  const iban = elements.create('iban', options);

  iban.on('change', (event) => this.ibanOnChange(event));
  iban.mount('#iban-element');

  // A bit of indirection, the submit button event is bound to a higher-order container
  setClick(() => this.handleSubmit(iban));
}

handleSubmit(iban) {
  const {showFlashMessageError, ownerNameValue, stripe} = this.props;

  const sourceData = {
    type: 'sepa_debit',
    currency: 'eur',
    owner: {
      name: ownerNameValue
    }
  };

  return stripe
    .createSource(iban, sourceData) // <--- stripe.createSource
    .then((result) => {
      if (result.error) {
        return showFlashMessageError(result.error.code);
      }
    })
    .catch((error) => {
      showFlashMessageError('PROCESSING_ERROR');

      return Promise.reject(error);
    });
}

render() {
  const {submitting} = this.props;
  const {ibanFieldError} = this.state;
  const formPrefix = 'checkout-sepa';

  return (
    <form id='payment-form' method='post'>
      <fieldset className={classNames({
        'x-disabled': submitting
      })}>
        <Field
          name='ownerName'
          className='name'
          component={renderInput}
          formPrefix={formPrefix}
          type='text'
          label={translate('checkout.payment.sepa.ownerNameLabel')}
          autoComplete='cc-name'
          ariaRequired='true'/>
        <div className={classNames('iban', {
          'x-error': ibanFieldError
        })}>
          <label className='label'>{translate('checkout.payment.sepa.ibanLabel')}
            <div id="iban-element"></div>
          </label>
          {ibanFieldError && <FieldInlineError message={ibanFieldError.message}/>}
        </div>
        <div className='mandate'>{translate('checkout.payment.sepa.mandate')}</div>
      </fieldset>
    </form>
  );
}
```

**Comment by dweedon-stripe** [comment]
Hi @freen 

If you are using `react-stripe-elements` you need to use the `<IbanElement>` instead of mounting it yourself. Sorry the guide did not make a callout about how to do this! We will get it updated.
