### ISSUE TITLE
Error message don't use locale parameter

### ISSUE THREAD

**Issue by ddcq** [stripe/react-stripe-elements#466]
The componenet \<Elements/\> have a "locale" parameter as it is a part à stripe.elements() options but the error messages use the browser configuration (french for me). I can't force a different language.

**Comment by dweedon-stripe** [comment]
Can you share a bit more info and perhaps a minimum reproduction? What methods are you using?

**Comment by sashko-stripe** [comment]
Closing this as this project has migrated to [React Stripe.js](https://github.com/stripe/react-stripe-js). If you believe this is still important, please re-open it there.
