### ISSUE TITLE
Is it possible to implement payment in the serverless app?

### ISSUE THREAD

**Issue by Juna9515** [stripe/react-stripe-elements#467]
Hello?
I have one question to implement payment using stripe.

what I want to say is below.

 Can I implement payment using it without any own backend such as Node?

Best Regards.

**Comment by dweedon-stripe** [comment]
Hi @Juna9515 

This repo is just for a thin wrapper around Stripe Elements, for broader questions like I think you will have better like on our [support site](https://support.stripe.com/). Your best option may be Checkout, which does have a [client-only integration](https://stripe.com/docs/payments/checkout/client-only).

Thanks!
