### ISSUE TITLE
Confused about createToken argument(s?)

### ISSUE THREAD

**Issue by indiesquidge** [stripe/react-stripe-elements#47]
I'm a bit confused about how to work with the arguments in `stripe.createToken`.

I can see in the [source code](https://github.com/stripe/react-stripe-elements/blob/c32e5a296183dc93079231c5e66d205598c713b7/src/components/inject.js#L83-L86) that `createToken` is a bit strange for legacy reasons, and I'd love it if we could perhaps shed a bit more light on that.

For context, here is the signature

```javascript
createToken: (
  type: string | ElementShape,
  options: mixed
) => Promise<{token?: MixedObject, error?: MixedObject}>
```

What string values are applicable to `type`? The README example shows 'card', I assume this is because the example is using the `CardElement` component. So if I were to be using individual `*Element` components, what type would I specify? `cardNumber` perhaps? Is this what is being set implicitly if I pass in no arguments?

I think most of my confusion is surrounding the disparities between this function's API and the official [documentation](https://stripe.com/docs/stripe.js#stripe-create-token). Seems like the point of my confusion has been [mentioned before](https://github.com/stripe/react-stripe-elements/pull/9#discussion_r116373048), but didn't seem to result in a discussion.

Just curious about the best way to make use of `createToken` without it feeling like a blackbox (i.e. no arguments).

**Comment by michelle** [comment]
In the official docs, it's documented that you can use `bank_account`[0] or `pii`[1] as string arguments to `createToken` .

> So if I were to be using individual *Element components, what type would I specify? cardNumber perhaps? Is this what is being set implicitly if I pass in no arguments?

If you were using Element instances, you can specify the Element as the first argument. However, if you're using this library, you can omit the first argument and just call `props.stripe.createToken()` directly within a component that has `stripe` injected.

[0] https://stripe.com/docs/stripe.js#collecting-bank-account-details
[1] https://stripe.com/docs/stripe.js#collecting-pii-data

**Comment by michelle** [comment]
Ah, re: black box, you can use it like this if you want to explicitly specify the type:
`stripe.createToken({type: 'card' | 'bank_account' | 'pii'})`

**Comment by jenan-stripe** [comment]
For additional clarification: you would never use `cardNumber` because that's an Element type, but not a _token_ type. I definitely see the confusion with `card` being both an Element type and a Token type!

Please let us know if this clarifies things!

**Comment by indiesquidge** [comment]
> I definitely see the confusion with card being both an Element type and a Token type!

Yeah, this is what was tripping me up at first.

I appreciate y'all trying to explain this to me. I'm still a bit confused by the ostensibly conflicting nature of these two comments

> If you were using Element instances, you can specify the Element as the first argument.

> you would never use `cardNumber` because that's an Element type, but not a `token` type.

It isn't a token itself that we pass, it's ["the **Element** you wish to tokenize data from"](https://stripe.com/docs/stripe.js#stripe-create-token), right? And since `cardNumber` is a [type of element](https://github.com/stripe/react-stripe-elements#element-components), very similar to the `card` element, I guess I had figured that `cardNumber` would also have been tokenizable.

I think I'm square on how it works now, it was just the ability to call `props.stripe.createToken()` and have the element be passed implicitly that was mysterious to me since it doesn't work this way in the official Elements docs. And then having to pass an object, `{type: 'card'}`, was also tripping me up since I wasn't sure what this was doing.

**Comment by indiesquidge** [comment]
All said, I don't know what an alternative solution would be for this. I think what y'all have created is great considering the limitations at hand.

Doing something like the docs would be hard

```js
const card = elements.create('card')
// …later
const {token, error} = await stripe.createToken(card)
```

Since the `<*Element>` components are already created for us, there is never a point in time where we as developers call something like `elements.create()` (in fact, `elements.create()` isn't even exposed publicly). Using something like `{type: 'card'}` feels like an okay solution, I just imagine it may confuse other people the way it initially confused me.

**Comment by jenan-stripe** [comment]
@indiesquidge Sorry, I made it more confusing! :) What I meant was you would never pass the string `'cardNumber'` to `createToken`. You _could_ pass a `cardNumber`-type Element (and that is in fact how you tokenize using the split fields). Does that help?

**Comment by indiesquidge** [comment]
> You _could_ pass a `cardNumber`-type Element (and that is in fact how you tokenize using the split fields).

But this is not the case with this repository, right? You don't pass in the `CardNumberElement` component as an argument to `stripe.createToken()`. But you _do_ do this when you use the Stripe API in vanilla JS.

This is kind of the essence of my confusion here: You never actually pass an element type into `stripe.createToken()`—it seems to be implicitly derived.

**Comment by jenan-stripe** [comment]
@indiesquidge Right! In `react-stripe-elements`, you're not calling `elements.create()` directly, so it would be awkward to require users to pass the Element to `createToken`.

**Comment by ptaking** [comment]
So what will be passed to `stripe.createToken()` if my form rendered as below?
```
   return (
      <div id="wrapper">
        <HeaderComponent />
        <main>
          <StripeProvider stripe={this.state.stripe}>
              <Elements>
                <label>
                  Card details
                  <CardElement/>
                </label>
              </Elements>
          </StripeProvider>
        </main>
      </div>
    );
```

**Comment by jez** [comment]
@ptaking 

If you're using the `stripe={...}` prop on StripeProvider (which means you're using one of the advanced loading strategies), your code would look like this:

https://github.com/stripe/react-stripe-elements/blob/7fe4fdf3f532921b10b56d98ae757c0d9b3fb999/demo/async/async.js#L44-L53

Another thing is that you're missing a call to `injectStripe`. You won't be able to do this unless you've called `injectStripe` on your checkout form:

https://github.com/stripe/react-stripe-elements#setting-up-your-payment-form-injectstripe

**Comment by rdalfonso** [comment]
Where in the process is the payment made to Stripe?
I've been able to setup my form component using individual form components CardElement, CardNumberElement, CardExpiryElement, CardCVCElement) and I'm getting back the strip token.
What I don't understand is where the payment (amount, currency, stripe token, etc) is supposed to occur?

**Comment by jez** [comment]
@rdalfonso You need to send the token to your backend server, and use your Stripe API secret key to POST to the /v1/charges endpoint:

https://stripe.com/docs/charges
