### ISSUE TITLE
Uncaught TypeError: window.Stripe is not a function

### ISSUE THREAD

**Issue by laingmedia** [stripe/react-stripe-elements#470]
Has anyone seen this error before? 

- Uncaught TypeError: window.Stripe is not a function

**Comment by oliver-stripe** [comment]
@laingmedia This usually means you haven't loaded Stripe.js on your page (e.g. https://github.com/stripe/react-stripe-elements#then-load-stripejs-in-your-application).

**Comment by yazmnh87** [comment]
Loading Stripe.js asynchronously

Loading Stripe.js asynchronously can speed up your initial page load, especially if you don't show the payment form until the user interacts with your application in some way.

<html>
  <head>
    

    
    
    <script id="stripe-js" src="https://js.stripe.com/v3/" async></script>

    
  </head>
  
</html>
