### ISSUE TITLE
<CardElement /> fakeNumber-last4 don't not render correctly

### ISSUE THREAD

**Issue by matikrk** [stripe/react-stripe-elements#472]
Hi I have problem with using <CardElement /> on small screens, when last4 digits span is appearing instead of whole numbers.

I have 2 problems with that component, one more general and secound one more specyfic with my styling.

### Problems:
1) fakeNumber-last4 don't get class `is-complete` when number are filled corecctly. When you fill it badly this have `is-invalid` class. It's very annoying if you have diffrent colors for valid input (green in my case). Screenshots are at bottom.

For prove that you can query last 4 digits inside your example page (https://stripe.dev/elements-examples)
```
document.querySelector('.CardField-number-fakeNumber-last4')
```

after filling with card number with bad number 4242 4242 4242 4244 you will get:
`<span class=​"CardField-number-fakeNumber-last4 InputElement is-invalid">​424​4</span>​`

after filling with card number with corect number 4242 4242 4242 4242 you will get:
`<span class=​"CardField-number-fakeNumber-last4 InputElement">​4242​</span>​`
instead of
`<span class=​"CardField-number-fakeNumber-last4 InputElement is-complete">​4242​</span>​`
so class `is-complete` is missing

2) fakeNumber-last4 have problems with different font/font-size. 
When I have styling like this:
```
const style = {
  base: {
    fontSize: '16px',
  }
};
```
span with last 4 digits is few pixels above baseline

Posible solution:
For fix that you could delete property `height: 1.2em` from css class `ElementsApp input`. It won't break anything (what I've tested) and fix placement of last 4 digits

### Screenschoots

Screenshots (we could se both issues here): 
<img width="387" alt="Screenshot 2019-12-02 at 09 07 44" src="https://user-images.githubusercontent.com/17196505/69940783-5f773100-14e3-11ea-95de-387dc30ad2f8.png">
<img width="331" alt="Screenshot 2019-12-02 at 09 07 49" src="https://user-images.githubusercontent.com/17196505/69940785-5f773100-14e3-11ea-920b-28c197baec89.png">
<img width="358" alt="Screenshot 2019-12-02 at 09 08 11" src="https://user-images.githubusercontent.com/17196505/69940787-5f773100-14e3-11ea-98b0-12454989213f.png">
<img width="361" alt="Screenshot 2019-12-02 at 09 08 15" src="https://user-images.githubusercontent.com/17196505/69940788-600fc780-14e3-11ea-915f-05e94e4eb98d.png">

**Comment by mbarrett-stripe** [comment]
Hi - it looks like the issues you are having are more aligned with Stripe.js itself rather than this repo, which is only a thin wrapper to enable use with React. For Stripe.js support, please contact [our support team](https://support.stripe.com/) who can help you with these issues. Thanks!
