### ISSUE TITLE
Elements not applying textAlign style to input placeholder on IE11

### ISSUE THREAD

**Issue by summermin** [stripe/react-stripe-elements#478]
### Summary

CardNumberElement, CardExpiryElement, and CardCVCElement (and potentially others) are not getting the `textAlign` style applied to the input placeholders on Internet Explorer 11. `textAlign` works fine on the input itself, it's only the `::placeholder` that it is not getting applied to. Example implementation:
```javascript
<CardNumberElement
  style={{
    base: {
      textAlign: 'right',
      fontSize: '14px',

      '::placeholder': {
        textAlign: 'right',
        color: '#a1a1a1',
      },
    },
  }}
  placeholder="0000 0000 0000 0000"
/>
```

### Other information

IE11:
<img width="629" alt="Screen Shot 2019-12-18 at 6 05 59 PM" src="https://user-images.githubusercontent.com/11067527/71131200-033e2d80-21c2-11ea-892a-929bacf0c2bb.png">
Chrome:
![Screen Shot 2019-12-18 at 6 12 37 PM](https://user-images.githubusercontent.com/11067527/71131253-27017380-21c2-11ea-978d-5bec8819cbc0.png)

Works fine on all other browsers. Other style attributes like `color` also working fine on the placeholder in IE11. Tested using v2 and v6 of react-stripe-elements

**Comment by sashko-stripe** [comment]
Closing this as this project has migrated to [React Stripe.js](https://github.com/stripe/react-stripe-js) as of early 2020, which also has a somewhat different API. If you believe this is still important, please re-open it there.
