### ISSUE TITLE
Uncaught IntegrationError: Can only create one Element of type card.

### ISSUE THREAD

**Issue by r3wt** [stripe/react-stripe-elements#479]
# PLEASE BE URGENT, THIS IS A KILLER FOR US

### Summary

We are using `react-responsive` to render different views for Mobile and Tablet/Desktop. we have media query components called `Mobile` and `TabletUp`. So we are rendering a Mobile version and then a version for Tablet, Netbook, Desktop, etc. The issue is when resizing between the media queries, this error is thrown(**but only after the second resize**). Below that is another error printed apparently from your react components in the iframe and it reads:

`Error: A cross-origin error was thrown. React doesn't have access to the actual error object in development.`

I included a screenshot of all the seperate errors:

![image](https://user-images.githubusercontent.com/4483325/71222951-f429af00-2297-11ea-845a-9962639202dd.png)

![image](https://user-images.githubusercontent.com/4483325/71222975-0b689c80-2298-11ea-8024-f8e22f9771c9.png)

![image](https://user-images.githubusercontent.com/4483325/71222989-14f20480-2298-11ea-9e6a-087f70c964fc.png)

I tried to make a minimal example below to illustrate the problem, but this code is untested as i don't know how to setup jsfiddle for react and dependencies.

```js
import ReactDOM from 'react-dom';
import React,{Component} from 'react';
import Responsive from 'react-responsive';
import {StripeProvider,Elements,CardElement,injectStripe} from 'react-stripe-elements';

// ADD API KEY HERE
const apiKey= '...';

const Mobile = props => (
  <Responsive {...props} query="(max-width: 500px) and (orientation: portrait), (max-width: 800px) and (orientation: landscape)" />
);

const TabletUp = props => (
  <Responsive {...props} query="(min-width: 501px) and (max-width: 1024px) and (orientation: portrait), (min-width: 801px) and (orientation: landscape)" />
);

const Page = ()=>(
  <div>
    <Mobile><CardElement /></Mobile>
    <TabletUp>CardElement /></TabletUp>
  </div>
);

@injectStripe class PageComponent extends Component {
  render(){
     return <Page />;
  }
}

class App extends Component {
  render(){
    <StripeProvider apiKey={apiKey}>
      <Elements>
         <PageComponent />
      </Elements>
    </StripeProvider>
  }
}

ReactDOM.render(<App />,document.getElementById('root'));
```

**Comment by dweedon-stripe** [comment]
Hi @r3wt,

We block rendering multiple Card elements at the same time because this is generally the wrong thing to do. I'm not sure how `react-responsive` handles mounting/unmounting its children but it looks like it ends up rendering both trees at some point. 

To get around this, you can use a separate Elements context for each breakpoint:

```jsx
const Page = ()=>(
  <div>
    <Mobile><Elements>{/* ... */}</Elements></Mobile>
    <TabletUp><Elements>{/* ... */}</Elements></TabletUp>
  </div>
);
```

Note that this means you will probably need to rework your component nesting a bit to ensure you are calling `injectStripe` below `<Elements>`. Let me know if this helps.

**Comment by syedzubairahmed001** [comment]
Iam having the same issue. I was wondering is this because of the react-router-dom?

**Comment by sashko-stripe** [comment]
Closing this as this project has migrated to [React Stripe.js](https://github.com/stripe/react-stripe-js) as of early 2020, which also has a somewhat different API. If you believe this is still important, please re-open it there.
