### ISSUE TITLE
"You did not specify the type of source or token to create"

### ISSUE THREAD

**Issue by kylehotchkiss** [stripe/react-stripe-elements#48]
Hello, in my payment form, many cards from visa, mastercard, and amex have processed fine. But intermittently, a customer encounters this error:

"You did not specify the type of source or token to create"

This doesn't quite make sense given that I don't see `type` as an option inside of the react stripe elements configuration, so I assume this is an error encountered in the script that isn't passed quite up the react chain. My boss fired this earlier when he used 1password autofill in elements. 

Does anybody have tips regarding this error during tokenization, and what I can do to catch it and communicate errors to customers better? I am unable to share source due to proprietary nature of code.

**Comment by michelle** [comment]
I think this fix might be related: https://github.com/stripe/react-stripe-elements/pull/45

**Comment by kylehotchkiss** [comment]
@michelle thanks for the link. My form's payment code was in a "collapsed" (not rendered at page ready) step so I'll give latest version a go.

**Comment by michelle** [comment]
Yep, about to publish it!

**Comment by michelle** [comment]
It's done -- 0.0.6! Let me know if that fixes it.

**Comment by michelle** [comment]
Closing this for now, but let me know if you still see issues.

**Comment by kylehotchkiss** [comment]
@michelle since merging this in I haven't seen this error crop up again, thank you for your work here.

**Comment by blaynem** [comment]
I'm still getting this issue. Weird things is, if I navigate to our `/payment` by itself and press the button, it works as you'd expect it to. But if you navigate to it via a `<Link to="/payment" />` from react-router, and press the button it throws this error. Doesn't seem to be an issue with using `<a>` tags, but..

**Comment by devarashetty** [comment]
I am seeing this issue in version 0.0.7

**Comment by THPubs** [comment]
Just noticed that this error can come up if you are using Redux. The right way to do it is, first wrap the component with redux connect and then wrap with `injectStripe` like this:

    export default injectStripe(connect(null, {})(CardDetailsForm));

**Comment by jez** [comment]
Yep! And there's more information about this [in the README **→**](https://github.com/stripe/react-stripe-elements#troubleshooting).
