### ISSUE TITLE
Customizing local 

### ISSUE THREAD

**Issue by yashasolutions** [stripe/react-stripe-elements#481]
Is there a way to provide custom translation for elements?
Especially for CardElement ?

**Comment by dweedon-stripe** [comment]
Hi @yashasolutions 

Sorry, this is not possible and we currently have no plans to support this with the `CardElement`, but it is possible to provide custom placeholder strings with the split card Elements: 

```jsx
<CardNumberElement placeholder="A Card Number" />
<CardCvcElement placeholder="A CVC" />
<CardExpiryElement placeholder="An Expiration Date" />
```

Additionally, for any Element's `'change'` event or any Stripe.js method response, you can provide your own errors by keying off the error `code` rather than using the default messages:

```jsx
const CardForm = ({stripe, elements}) => {
  const handleSubmit = async (e) => {
    e.preventDefault();

    const payload = await stripe.confirmCardPayment({
      payment_method: {
        card: elements.getElement('card'),
      },
    });

    if (payload.error) {
      // show some custom error based off of payload.error.code
    }
  }
  
  const handleChange = (change) => {
    if (change.error) {
      // show some custom error based off of change.error.code
    }
  }

  return (
    <form onSubmit={handleSubmit}>
      <CardElement onChange={handleChange} />
      <button>Pay</button>
    </form>
  );
};

injectStripe(CardForm)
```

**Comment by dweedon-stripe** [comment]
What is your use case? Do you need some locale not currently supported, or are you unhappy with the translations for an existing locale?

**Comment by yashasolutions** [comment]
I needed the locale in russian - and in most places (emails and checkout) stripe dont support russian as part of the locales, I assumed it was the same with elements, but I read the doc better and found I can pass the desired locale as an argument and turns out russian was supported. So I am am good with the current implementation,
