### ISSUE TITLE
dropdown for card expiry element

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [stripe/react-stripe-elements#483]
There are studies that suggest drop-downs are easier to use resulting in more conversion rate.

That is why I was wondering if it would be possible to have drop-downs for the card expiration date instead of text fields?

Thank you

**Comment by mbarrett-stripe** [comment]
Hi @ahmadabdolsaheb - thanks for the input! However, this is a feature request for Stripe Elements directly and not a question about the react integration. This repo's issues section is only for solving issues with the React Stripe Elements integration. I recommend [reaching out to Stripe Support](https://support.stripe.com/email).
