### ISSUE TITLE
Poor / Incomplete examples custom payment requests

### ISSUE THREAD

**Issue by D19cannon** [stripe/react-stripe-elements#486]
Hey guys,

Would you be so kind to post or update the documentation how to complete custom payment request. As it right now, I can only send request when there would a products added in stripe. However, some people like me only need the card validation and payment confirmation.

My products are coming from WP-commerce in a  WP, Gatsby, Grapqhl, Apollo stack and I simply need the payment system and nothing else.

**Comment by mbarrett-stripe** [comment]
Hi @D19cannon - this repo's issues are only for specific problems with the React wrapper for Stripe. Our support team is available to help with guidance for your use case and can point you in the right direction or help you figure your integration out. You can [reach out to them here](http://support.stripe.com/email) for help.
