### ISSUE TITLE
Please add Connect usage examples

### ISSUE THREAD

**Issue by bionicles** [stripe/react-stripe-elements#487]
### Summary

I'd like to put Connect on a react app but there's no example. The only example is for a swift app

Would it please be possible to add a usage example of react-stripe-elements to make a stripe connect app?

Then it would be much easier to develop web platform marketplace type things...

**Comment by ajsharp** [comment]
It's a little hard to find in the readme, but it's here: https://github.com/stripe/react-stripe-elements#stripeprovider. Quoting from the readme:

> For example, if you are using Stripe Connect and want to act on behalf of a connected account, you can pass stripeAccount="acct_123" as a property to <StripeProvider>.

**Comment by sashko-stripe** [comment]
Closing this as this project has migrated to [React Stripe.js](https://github.com/stripe/react-stripe-js) as of early 2020, which also has a somewhat different API.

I'll track this internally as a docs improvement ticket on our end.
