### ISSUE TITLE
Zip code won't disappear

### ISSUE THREAD

**Issue by CamilleRungette** [stripe/react-stripe-elements#492]
Hello, 
I want to remove the Zip code from de Card Element on my React app. I've tried to use hidePostalCode: true, but i can't seem to make it work trhough style={{}}. I've ried to use three different elements for card number, CVC and expring date but as soon as I implement css o it (flexbox) they disppear. 
Can you please help me with those issues ? How to implement css on stripe elements ?

Thank you ,

**Comment by oliver-stripe** [comment]
Hi @CamilleRungette Please use https://support.stripe.com/ to contact our support team to help with integration issues. If you think what you're encountering is a bug after that, please include a reproduction case. Going to close this out for now.
