### ISSUE TITLE
Differentiate between react-stripe-elements and react-stripe-js

### ISSUE THREAD

**Issue by wesbos** [stripe/react-stripe-elements#493]
I can't figure out what the difference is between this project, and https://github.com/stripe/react-stripe-js

react-stripe-js says this is legacy? But this one seems well supported and updated.

What is the difference? Which one do I need?

**Comment by fred-stripe** [comment]
Hi there, great question!

For now you’ll want to use react-stripe-elements. We’re getting
react-stripe-js ready for beta release and we plan to integrate it into the
main Stripe documentation as well. We will make a more general announcement
soon, but for now follow the react-stripe-js repo if you’re curious. Hope
that clears things up!

**Comment by wesbos** [comment]
Makes sense -thank you :)

**Comment by samuelcastro** [comment]
Hi @fred-stripe I just posted the same question. on React Stripe JS (https://github.com/stripe/react-stripe-js/issues/82), so what's the status now? Do we sill want to keep using React Stripe Elements over React Stripe JS?

Thanks!

**Comment by fred-stripe** [comment]
`react-stripe-js` is now out of beta and is the preferred path for anyone building on React 16+. This repository, `react-stripe-elements` is for React 15 and earlier. Both libraries will receive updates for new Elements as we add them, however, we intend for react-stripe-js to be the primary approach for new projects.
