### ISSUE TITLE
Card element Icon padding bug

### ISSUE THREAD

**Issue by JClackett** [stripe/react-stripe-elements#494]
Hello!

This has just changed for me and now my card element looks like this

<img width="463" alt="Screenshot 2020-01-22 at 21 49 21" src="https://user-images.githubusercontent.com/12549124/72932973-1adc7900-3d61-11ea-9010-bb7e3ee43dd4.png">

the icon has been squashed down

code: 

```js
        <CardElement
                  hidePostalCode={true}
                  onReady={el => el.focus()}
                  iconStyle="default"
                  style={{
                    base: {
                      fontSize: "16px",
                      color: "white",
                      fontFamily: "Helvetica",
                      "::placeholder": { color: "#999" },
                      iconColor: "white",
                    },
                  }}
                />
```

**Comment by dweedon-stripe** [comment]
Hi @JClackett,

This was a short-lived bug that we introduced in the core Stripe.js library. It has been fixed now.
