### ISSUE TITLE
Elements not  able to testing (at least I tried on Cypress.js) . I had error when I try typing CardNumberElement and others too. 

### ISSUE THREAD

**Issue by mustafaerk** [stripe/react-stripe-elements#496]
Feature request or idea? Consider opening an
[API review](https://github.com/stripe/react-stripe-elements/tree/master/.github/API_REVIEW.md)!

### Summary
I am getting error when I try to type numbers in CardNumberElement. I checked error because of "Pointer event:none" its make it untestable this inputs.

I could not see any props or something like that to change it.

**Comment by rkrueger11** [comment]
Stripe uses iFrames to embed each element component due to PCI compliance. Unfortunately, Cypress does not handle iFrames well, but check out this article for ways to modify Cypress so that it works. https://medium.com/@michabahr/testing-stripe-elements-with-cypress-5a2fc17ab27b

**Comment by sashko-stripe** [comment]
Closing this as this project has migrated to [React Stripe.js](https://github.com/stripe/react-stripe-js) as of early 2020, which also has a somewhat different API. If you believe this is still important, please re-open it there.
