### ISSUE TITLE
this.props.elements is undefined in injected  function

### ISSUE THREAD

**Issue by ArtakKostanyan** [stripe/react-stripe-elements#497]
I go through steps  in example from Get Started to Setting up your payment form (injectStripe)
 , but I had  this error
![image](https://user-images.githubusercontent.com/26996949/73293988-54f4c180-421e-11ea-9fa4-57c04a54aa3b.png)

I print the props and there is no elements object

**Comment by dweedon-stripe** [comment]
Hi @ArtakKostanyan,

Are you using the latest version? The injection of `elements` was added in [v6.0.0](https://github.com/stripe/react-stripe-elements/releases/tag/v6.0.0).
