### ISSUE TITLE
<IbanElement> documentation

### ISSUE THREAD

**Issue by Pixelatex** [stripe/react-stripe-elements#500]
So I'm trying to implement direct debit payments and oh boy, what a mess this has been. It's nigh impossible to find coherent docs on how this should work. There is an IbanElement component in this package but I can't find any example on how this should work, the API,...

Even simple stuff like supportedCountries=['SEPA'] I had to find out by following the error messages.

Can you guys please make a basic direct debit example and explaining the API for this component?

**Comment by dweedon-stripe** [comment]
Hi @Pixelatex, 

Sorry, the current state of the docs for using `react-stripe-elements` with non-card payments is not great. While it is not React specific, [this guide](https://stripe.com/docs/payments/sepa-debit/accept-a-payment) will show you how to use the IBAN element with SEPA direct debit. If you already have the Element working, you should be able to use it with `confirmSepaDebit` payment as referenced in the guide.

Additionally, we are currently testing [React Stripe.js](https://github.com/stripe/react-stripe-js), a new library for integrating Stripe Elements with React. As part of this testing we have written a lot of new docs, including React specific content for the guide I referenced above. If you are interested, email [stripejs-feedback@stripe.com](mailto:stripejs-feedback@stripe.com) with your Stripe account ID for access to the new beta docs. This may be easier than trying to translate the steps from the existing guide to React, and we would love to hear your feedback on the new content.

Thanks!

**Comment by devchris** [comment]
@dweedon-stripe is this documentation already published?

**Comment by devchris** [comment]
Nvm found it: https://stripe.com/docs/payments/sepa-debit/accept-a-payment

**Comment by sashko-stripe** [comment]
Glad this was resolved, thank you both!
