### ISSUE TITLE
Stripe element gets focus if error occurred in createToken(...)

### ISSUE THREAD

**Issue by zhdanouskikh** [stripe/react-stripe-elements#502]
I'm using CardElement component. When I'm trying to call stripe.createToken(...) and get error (user didn't enter cvc for example) component is autofocused. I do not expect such behaviour, cause stripe input is the last one, and there are inputs that needs to be focused instead stripe if there was an error.

Does someone have thoughts how I can disable autofocus?

**Comment by dweedon-stripe** [comment]
🤔I can definitely see the value in this, but we don't currently have a direct way to disable this behavior.

For now, I would listen to focus events and conditionally send the focus to the desired input.

```jsx
<CardElement 
  onFocus={() => {
    if (hasMoreImportantError) {
      moreImportantInputRef.current.focus();
    }
  }
/>
```

Let me know if this approach will work for your case.

**Comment by dweedon-stripe** [comment]
@zhdanouskikh, it looks like you should be able to override this behavior by sending the focus wherever you like after `createToken` has resolved. Take a look at this example:

https://codesandbox.io/s/trusting-worker-ehxnv?fontsize=14&hidenavigation=1&theme=dark

Let me know if this doesn't work for you.

**Comment by sashko-stripe** [comment]
Closing this as this project has migrated to [React Stripe.js](https://github.com/stripe/react-stripe-js). If you believe this is still important, please re-open it there.
