### ISSUE TITLE
support or ommit __self and __source props

### ISSUE THREAD

**Issue by shablenko-sednor** [stripe/react-stripe-elements#504]
In development mode there are some debug props like __source and __self with circular structure, your elements crash during props check (isEqual util), could you add support for those props or just ignore them, or fix your util to support circular structures?

I would like to turn off those props, but I'm using create-react-app and I don't have control over presets inside webpack config, ejecting is not an option

**Comment by jonchurch** [comment]
I'm curious about this and would like to play with it. Can you help me by providing some reproduction steps, or even better a codesandbox or repo that demonstrates the crash?

**Comment by shablenko-sednor** [comment]
Just create empty project with latest CRA and try to use CardNumberElement
Cannot reproduce on sandbox, it seems to use production build

**Comment by yocmen** [comment]
Happen to me too with GatsbyJS in dev :(

**Comment by sashko-stripe** [comment]
Closing this as this project has migrated to [React Stripe.js](https://github.com/stripe/react-stripe-js) as of early 2020, which also has a somewhat different API. If you believe this is still important, please re-open it there.
