### ISSUE TITLE
onClick on PaymentRequestButtonElement does not appear to work.

### ISSUE THREAD

**Issue by peitalin** [stripe/react-stripe-elements#509]
onClick prop on PaymentRequestButtonElement does not appear to work.
E.g: no console.log fires when clicking the PaymentRequest (purple) button

```
<PaymentRequestButtonElement
    paymentRequest={paymentRequest}
    onClick={() => {
      console.log("clicked apple pay button")
    }}
/>
```

**Comment by fred-stripe** [comment]
Hmm… just tried to replicate this on the latest version of this library and the `onClick` works as expected:

https://codesandbox.io/s/ecstatic-morning-vkvnz?fontsize=14&hidenavigation=1&theme=dark

Do you have any more details I can use to track down the issue?
