### ISSUE TITLE
Support className for styling elements

### ISSUE THREAD

**Issue by tim-soft** [stripe/react-stripe-elements#51]
I've seen closed PR #14 and want to express interest in adding styles via className

I'm testing the waters with these elements in an SSR app and have not been successful applying styles the old fashioned way

**Comment by jenan-stripe** [comment]
@tim-soft Agreed! Just cut v0.0.7 with this fix. Let us know if that works for you!

**Comment by tim-soft** [comment]
Things are looking good, I've been able to style up the CardElement _almost_ the same way as is demo'd [here](https://stripe.com/docs/elements/examples) with two exceptions

Styles relating to fonts must be provided via `style={{ base: {...} }}`
```javascript
<div className={s.group}>
    <label>
        <span>Card</span>
        <CardElement className={s.StripeElement} style={{base: {fontSize: '12px', fontWeight: '300', lineHeight: '40px'}}} />
    </label>
</div>
```

I haven't found a way (yet) to style the color of the little card -- is there a nice way to change it's color?

Here's react-stripe-elements in action **with styles** in an SSR setting:
![capture](https://user-images.githubusercontent.com/10257939/28948593-ebd199c4-7873-11e7-96cf-5fc1d3c0783f.PNG)

**Comment by jenan-stripe** [comment]
@tim-soft Sorry I'm not following -- is `fontFamily` not working?

**Comment by tim-soft** [comment]
From what I can tell, line-height, font-weight, font-family etc have no effect on the stripe element when passed as CSS via className. It appears that these properties must be passed as an object in the style prop.

**Comment by jenan-stripe** [comment]
@tim-soft Ah yes, that is correct. Anything within the Element, which uses an iframe (conceptually: anything that might be *within* an `<input>`) must be passed by the style prop.

**Comment by siakaramalegos** [comment]
@tim-soft To add fonts, you have to add that to the `<Elements />` `fonts` attribute. Here is the Stripe API with all the fields: https://stripe.com/docs/stripe-js/reference#stripe-elements

I just figured it out and added to SO: https://stackoverflow.com/questions/49239767/how-do-i-add-a-custom-font-to-my-card-element-when-using-react-stripe-elements/49239833#49239833

I'm struggling to change the padding or height though. My CardElement has a slightly different height than all my other inputs.

**Comment by siakaramalegos** [comment]
On re-reading, I misunderstood your original issue.  I might try the className to change the height or padding though.
