### ISSUE TITLE
<IdealBankElement> documentation

### ISSUE THREAD

**Issue by nejurgis** [stripe/react-stripe-elements#510]
I've been trying to set up a custom payment system with Gatsby and react-stripe-elements but theres's so many conflicting guides to do it in the documentation. Ive been following this repo as an example: https://github.com/stripe/react-stripe-js/blob/master/examples/hooks/5-iDEAL.js 

However, it's not complete as the IDEAL payment method requires a secondary step where the user gets redirected to their bank page. I've managed to achieve that with stripe.createSource but in the docs i've learned that it's the old way of doing it (?) and now you need to use createPaymentMethod but that also requires a paymentIntent? I'm a tad confused.. 

Could anyone give a full example of how IDEAL payments are supposed to be implemented in 2020 ?

**Comment by hofman-stripe** [comment]
Hi @nejurgis, [this guide](https://stripe.com/docs/payments/ideal/accept-a-payment) should have all the steps to accept an IDEAL payment, including creating the PaymentIntent and confirming with react examples.

**Comment by nejurgis** [comment]
hey @hofman-stripe  thanks for your answer, any idea how would one recreate this with SSR?  (I am using @stripe/react-stripe-js with Gatsby)

**Comment by hofman-stripe** [comment]
React Stripe.js supports SSR. [`loadStripe` returns a promise that resolves to `null` on the server](https://github.com/stripe/stripe-js/blob/master/README.md#loadstripe), which prevents the React Stripe Elements from rendering.

**Comment by asolove-stripe** [comment]
Let us know if you still need help with this!
