### ISSUE TITLE
this.props.stripe.elements is not a function

### ISSUE THREAD

**Issue by lhtdesignde** [stripe/react-stripe-elements#513]
Hi,
we are just running into an error related to elements. This started happening for us yesterday. We are running the latest version 6.1.1 with react 16.13. We are pulling in stripe (https://js.stripe.com/v3/) in the head.

<img width="669" alt="Screenshot 2020-04-02 at 23 25 45" src="https://user-images.githubusercontent.com/5528640/78301440-58b40580-7539-11ea-9f9f-606a25fb8a8e.png">

It seems this.props.stripe is defined but elements() never gets created. 
Do you maybe have an idea why this error could happen?

**Comment by christopher-stripe** [comment]
Hi @lhtdesignde, could you provide some information about the calling code here? What does the `componentDidMount` hook in `StripeNewCardForm.js` look like?

**Comment by lhtdesignde** [comment]
We think it was a race condition. We moved the stripe script further up to get initialized earlier. Using the latest version 6.1.1 of react-stripe-elements.
componentDidMount just does `const elements = this.props.stripe.elements()`; where elements() function would not be defined at this point.
