### ISSUE TITLE
Can this library be used with Angular?

### ISSUE THREAD

**Issue by xinthose** [stripe/react-stripe-elements#514]
Because you do not have an Angular library and the other libraries are community supported and not guaranteed to work, I was wondering if this library could be used with Angular somehow?  I can install it with `npm` just the same.

**Comment by asolove-stripe** [comment]
Hi there: no, this library is specifically a React API and won't work with Angular. You can either use a community Angular wrapper or directly interface with the [Stripe.js API](https://stripe.com/docs/js).
