### ISSUE TITLE
Display issues on mobile

### ISSUE THREAD

**Issue by blaynem** [stripe/react-stripe-elements#53]
If you switch browser to a mobile format the base CardElement has a rough time with everything overlapping and looking quite ugly.

**Comment by jenan-stripe** [comment]
@blaynem Can you provide a reproducible example? Elements should dynamically adjust for different available widths, but at some point it depends on how much space you give it and what font size you're using.

**Comment by blaynem** [comment]
After going through it, seems we had a margin that was causing it to overlap a ton. This can probably be closed for now.

**Comment by jenan-stripe** [comment]
Great!
