### ISSUE TITLE
docs: confirmCardPayment with split card elements needs a docs update

### ISSUE THREAD

**Issue by mweibel** [stripe/react-stripe-elements#534]
The documentation on pretty much all the react cases assume that you have a single `CardElement` and therefore specify the `confirmCardPayment()` call as follows:
```javascript
    const result = await stripe.confirmCardPayment(clientSecret, {
      payment_method: {
        card: elements.getElement(CardElement),
        billing_details: {
          name: `${firstName} ${lastName}`
        }
      }
    })
```

However there's the possibility to have them separated and the docs aren't clear what to do in this case as you have no `CardElement` in this case.
In my opinion there should be some mention (probably in [confirm_card_payment docs](https://stripe.com/docs/js/payment_intents/confirm_card_payment)) on how to do this, which is:

```javascript
    const result = await stripe.confirmCardPayment(clientSecret, {
      payment_method: {
        card: elements.getElement(CardNumberElement),
        billing_details: {
          name: `${firstName} ${lastName}`
        }
      }
    })
```

Which is cool - the library seems to be get the other 2-3 elements on it's own, which is great 👍

**Comment by asolove-stripe** [comment]
Hi @mweibel and thanks for reporting this confusion! We've added a note to the reference docs for the `card` field: 

> Uses the provided `card` or `cardNumber` Element to use for confirmation.
