### ISSUE TITLE
Payment Fields are not clickable in Samsung device

### ISSUE THREAD

**Issue by ersachit** [stripe/react-stripe-elements#535]
Hey Team, we have integrated the stripe in our react-native-web project but there is one problem that we are facing in Android (only Samsung) device i.e, we are not able to click on the payment fields when we are adding card details. Since there is a next button enable on the keyboard but there is no option to go back if the user wants to edit any of the detail.  Things are perfectly working fine on iOS. 

Seems like when the keyboard is open, the input fields have no focus since we can't tap on it. As soon as, keyboard hides, they got the focus back and we can click on that.

**Comment by asolove-stripe** [comment]
Hi @ersachit: sorry you didn't get a faster reply, did you ever find a solution to this problem? I just checked and things seem to work with Elements on Samsung devices, so I would have to speculate that there might be something from the addition of react-native-web that is complicating things.

**Comment by sashko-stripe** [comment]
Hi, this project has migrated to [React Stripe.js](https://github.com/stripe/react-stripe-js) as of early 2020, which also has a somewhat different API. If you believe this is still important, please re-open it there.
