### ISSUE TITLE
3D Secure Test Payment Screen iFrame - Any way to preview or control width/height?

### ISSUE THREAD

**Issue by appility** [stripe/react-stripe-elements#537]
So I'm testing out the 3D Secure Test Payment Screen, 
and I'm using Stripe Elements
```
/* Stripe Elements */
import {
  CardNumberElement,
  CardExpiryElement,
  CardCvcElement,
} from "@stripe/react-stripe-js"
```
I don't manually trigger the popup iFrame manually, it's all built in to Elements
but in preview mode the content is creating a scroll bar,
so I'm wondering is there a way to control the width of the window/iFrame when using Stripe Elements?

Am I right to assume it will render different content 
and look very different depending on the card issuing bank anyway?

**Comment by asolove-stripe** [comment]
Hi @appility: yes, sorry, but your guess here is correct. The content inside the modal is controlled by the bank and will be radically different depending on the customer's bank. Also, even Stripe does not find out how tall the content renders, so there is no way for us to size our modal such that we always avoid a scroll bar. This is an unfortunate property of the 3DS protocol.
