### ISSUE TITLE
Not able to customize CSS of CardElement

### ISSUE THREAD

**Issue by Nikhil22** [stripe/react-stripe-elements#539]
Feature request or idea? Consider opening an
[API review](https://github.com/stripe/react-stripe-elements/tree/master/.github/API_REVIEW.md)!

### Summary

Here is my code. I am trying to override the margin.

```function PaymentCard() {

  const CARD_ELEMENT_OPTIONS = {
    style: {
      base: {
        color: "#32325d",
        margin: '10px 0 20px 0',
        "::placeholder": {
          color: "#aab7c4",
        },
      },
      invalid: {
        color: "#fa755a",
        iconColor: "#fa755a",
      },
    },
  };

  return (
    <>
      {lang.cardDetails}
      <CardElement options={CARD_ELEMENT_OPTIONS} />
    </>
  );
};

export default PaymentCard;
```

However, I am getting an error in the console.

```Unrecognized property: margin is not a customizable CSS property for the card Element.```

The same thing happens with just about any other property (i.e padding, maxWidth).

How do I override margin, etc of the CardElement?

**Comment by asolove-stripe** [comment]
Hi @Nikhil22! Yeah, you can't customize the margin, or some other css properties, within Elements. Please see the [Style object docs](https://stripe.com/docs/js/appendix/style) for exact info on the options we support. 

Depending on what you need, you may want to use our `padding` style, or you may want to apply the `margin` to the DOM node that you are rendering the Element inside.
