### ISSUE TITLE
Split Card Number Not Inserted with 1Password Autofill

### ISSUE THREAD

**Issue by pacocoursey** [stripe/react-stripe-elements#541]
### Summary

In a split form, inserting a credit card number with the 1Password extension for Chrome on macOS does not fill in the card number correctly.

Here is a JSFiddle, forked from the Demo listed in the readme: https://jsfiddle.net/07x4joeu

Reproduction:
- Focus on the credit card number input
- Open the 1Password extension and autofill a card
- The card number is not filled correctly, but the CVC and Expiration are

### Other information

ZIP file including a `.mov` showing a reproduction: [video-reproduction.zip](https://github.com/stripe/react-stripe-elements/files/5257076/video-reproduction.zip)

Reproduction machine 1:
**Browser**: Chrome: Version 85.0.4183.102 (Official Build) (64-bit)
**OS**: macOS Big Sur Version 11.0 Beta (20A5354i)

Reproduction machine 2:
**Browser**:   Chrome: Version 85.0.4183.102 (Official Build) (64-bit)
**OS**: macOS Catalina Version 10.15.6 (19G2021)

Does *not* happen on Safari on machine 1.

**Comment by hofman-stripe** [comment]
I was able to reproduce this issue with 1Password 7. 1Password X works fine.

I believe this is a 1Password extension bug. The value that is getting set in the DOM input element is itself truncated. When inspecting the content script of the 1 Password extension, it doesn't even receive the full card information.

We've reported this issue to AgileBits.

<img width="533" alt="Screen Shot 2020-09-21 at 11 42 03 AM" src="https://user-images.githubusercontent.com/58793428/93807706-d9f27800-fbff-11ea-851c-668a3a4e0bb4.png">
