### ISSUE TITLE
When click on stripe element its getting blur

### ISSUE THREAD

**Issue by ejoo** [stripe/react-stripe-elements#543]
When I try to click on any of stripe element it is not getting focus. 
When I try that from another screen then it is working fine.
I have render the payment model in the another and there it is not working and another case where I have used outside a model then it is working fine.

In this screen it is not working
![image](https://user-images.githubusercontent.com/8073885/94680713-121c4980-02d7-11eb-8b68-250d9a46e517.png)

In this screen it is working properly
![image](https://user-images.githubusercontent.com/8073885/94680844-42fc7e80-02d7-11eb-9158-a0235f5d27d1.png)

**Comment by sashko-stripe** [comment]
Hi, this project has migrated to [React Stripe.js](https://github.com/stripe/react-stripe-js) as of early 2020, which also has a somewhat different API. If you believe this is still important, please re-open it there.
