### ISSUE TITLE
About scan card feature in mobile device

### ISSUE THREAD

**Issue by hiep294** [stripe/react-stripe-elements#544]
Hi, I have found that CardCVCElement and CardNumberElement component can scan card in mobile device, but they cause lagging. So I would like to know how to disable this feature, or something else to improve performance. Thank you

**Comment by sashko-stripe** [comment]
Hi, this project has migrated to [React Stripe.js](https://github.com/stripe/react-stripe-js) as of early 2020, which also has a somewhat different API. If you believe this is still important, please re-open it there.
