### ISSUE TITLE
PaymentRequestButton Does Not Load On Safari PWA

### ISSUE THREAD

**Issue by daylonball** [stripe/react-stripe-elements#545]
### Summary

PaymentRequestButton does not load Apple Pay in Safari browser for react-stripe-elements npm package. 

To reproduce go to [the official docs codesandbox example react project](https://codesandbox.io/embed/react-stripe-official-q1loc?fontsize=14&hidenavigation=1&theme=dark&codemirror=1) on safari on ios 14.

**Comment by sashko-stripe** [comment]
Closing this as this project has migrated to [React Stripe.js](https://github.com/stripe/react-stripe-js) as of early 2020, which also has a somewhat different API. If you believe this is still important, please re-open it there.
