### ISSUE TITLE
Stripe console message : parameter: betas is not a recognized parameter.

### ISSUE THREAD

**Issue by darsh4tech** [stripe/react-stripe-elements#546]
Hi Dears,
i am trying stripe at dev environemt then i see the following message in the browser console:

> Unrecognized payment-request-google-pay-inner.html parameter: betas is not a recognized parameter. This may cause issues with your integration in the future

and there is a link to the file cause that message to appear as following:
controller-207a0a1b39a190f1e22c08ab25c9f3ee.js:formatted:274

thanks in advance

**Comment by hofman-stripe** [comment]
Thanks for the report. This warning in the console is harmless. That said this will be fixed soon.

**Comment by hofman-stripe** [comment]
There should no longer be a warning in the console.
