### ISSUE TITLE
styling CardElement

### ISSUE THREAD

**Issue by naissa12** [stripe/react-stripe-elements#551]
I would like to style the <CardElement> to make it look like this. How do I do so?

<img width="603" alt="Screen Shot 2021-01-18 at 12 17 03 PM" src="https://user-images.githubusercontent.com/951837/104953439-6a657d00-5994-11eb-96bc-dabcd050cb17.png">

Here's my code:

 <div className="container">
       <CardElement />
</div>

**Comment by sashko-stripe** [comment]
Hi @naissa12, we aren't able to provide integration advice in the issues here. In the future if you have questions, please reach out to [Stripe Support](https://support.stripe.com/) for help.
