### ISSUE TITLE
Add a full stripe elements integration example

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [stripe/react-stripe-elements#556]
Adding a full Stripe integration example similar to https://github.com/stripe/stripe-payments-demo that includes country dropdown, optional zip/postal code based on country, other payment options, etc is highly appreciated.

This addition would give react developers access to an all in one payment solution that uses best practices which would lead to increase in overall conversions.

**Comment by sashko-stripe** [comment]
Hi @ahmadabdolsaheb, thank you for the suggestion. We're working on some new features and documentation for Elements that I believe will help significantly in this area.
