### ISSUE TITLE
Input for Card Element squished

### ISSUE THREAD

**Issue by chadwtkns** [stripe/react-stripe-elements#59]
Trying to implement this into my react app the input from the cardElement is all squished together, is that how it comes out of the box? Do I need to apply extra styling from the get go to get it to appear correctly? Thanks. 
<img width="284" alt="screen shot 2017-08-16 at 9 03 30 am" src="https://user-images.githubusercontent.com/5611546/29370337-4ab7f760-8262-11e7-852a-aaba9a9a4f56.png">

**Comment by cweiss-stripe** [comment]
Hi @chadwtkns, thanks for filing this issue. The input elements always stretch to 100% of the width of their parent container. So you would control this behavior by adjusting the width of the parent element. Let me know if that worked for you.

**Comment by cweiss-stripe** [comment]
Closing for now, please let us know if things are still unclear.

**Comment by chadwtkns** [comment]
Yeah sorry for the late response but it was how I was styling the label. Thanks for the advice. It probably wouldn't have been found/thought of for while.

**Comment by KudMath** [comment]
Is there a way to have the card elements vertically rather than on the same line?

**Comment by jez-stripe** [comment]
@KudMath There's no way to do this with `CardElement`. If you want to lay it out a different way, you can use the individual `CardNumberElement`, `CardExpiryElement`, `CardCVCElement`, and `PostalCodeElement`.

If you also want the card brand icon, you'll have to show this yourself (but the `CardNumberElement` includes the brand information in the [`change`](https://stripe.com/docs/stripe.js#element-on) event it gives to your `onChange` callback).

It's a good idea though! We're considering whether we want to support an option like that in the future.

**Comment by RP-3** [comment]
@chadwtkns could you share your styling? I'm having the same issue and it's totally not obvious to me how I'm supposed to style the label.

**Comment by Rcuz8** [comment]
Hi, this is definitely still an issue, under 340px. if you create a `CardElement`, with no other context, the UI falls apart under 340px width.

 I understand 340 px seems small, but consider this example:
 -  iPhone  X Width (via Chrome): 417px
 - App has 20px padding on either side (- 40px combined)
 - View has 10px padding (- 20px combined)
 - All Non-header elements have 10px left/right margins  (- 20px combined)
= 417px - 80x = 337px

Pictures of the issue:

<img width="703" alt="Screen Shot 2020-04-14 at 4 23 32 PM" src="https://user-images.githubusercontent.com/9902132/79271417-c29fa980-7e6d-11ea-9b43-256bab0f1d77.png">
<img width="711" alt="Screen Shot 2020-04-14 at 4 24 02 PM" src="https://user-images.githubusercontent.com/9902132/79271406-bfa4b900-7e6d-11ea-84dd-031e4168d8fd.png">
<img width="703" alt="Screen Shot 2020-04-14 at 4 23 50 PM" src="https://user-images.githubusercontent.com/9902132/79271412-c0d5e600-7e6d-11ea-8e65-c7a51df5388c.png">

**Comment by IliaMaz** [comment]
As @cweiss-stripe pointed out, the width is based on the parent element, and if you don't set the width of the parent element it will sit near invisible. Thanks for the solution.

**Comment by blainemuri** [comment]
Also concur with Rcuz8 above. The elements are not mobile responsive on fairly common screen sizes (iPhone SE), at around 320px. Making the container larger does not fix this.

We should either reopen this issue or create a new one.
