### ISSUE TITLE
SSR doesnt work

### ISSUE THREAD

**Issue by rgnevashev** [stripe/react-stripe-elements#64]
Server side rendering throw error
![2017-08-22_14-31-48](https://user-images.githubusercontent.com/123600/29563535-b15f9796-8746-11e7-800a-e3d646e2144f.png)

**Comment by fred-stripe** [comment]
Hi @rgnevashev, this is actually working as expected. Stripe Elements does not function outside of a browser DOM, so you will need to take care that your initial server-side render does not display any Elements components. You will want to make sure the Stripe instance is loaded and available in the browser before displaying any components from this library.

Hopefully that makes sense, I'm happy to clarify if you have any further questions!

**Comment by rgnevashev** [comment]
If I hide elements on server side and active only on client, I get react error "Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering." + stripe elements appers with some a delay.. It looks not good..

**Comment by unframework** [comment]
Even though the library technically works as intended, it would be very useful to have support for "isomorphic" apps that render both server-side and in browser.

Thinking through the technical implications, I can see that this could be complex: all of the Elements instantiation logic would need to run on component did-mount. That might be too much hassle to implement as out-of-the-box functionality, but I'd still like to log my vote for this feature.

Thanks!

**Comment by veeramarni** [comment]
@fred-stripe Any plan for supporting "isomorphic" apps?

**Comment by quachsimon** [comment]
+1 for this as well. We are using [react starter kit](https://github.com/kriasoft/react-starter-kit) and also having this same problem

**Comment by keeth** [comment]
this package being SSR-friendly would be really great. +1

**Comment by leebenson** [comment]
This isn't just 'nice to have', it's **vital**.

With everything that's happening in React 16 with server-side streaming, and frameworks like Next.js and my own kit [ReactQL](https://reactql.org), SSR is expected to work out the box -- it's naive to expect that every integration will solely use browser-side rendering.

At the very least, `react-stripe-elements` should return a skeletal representation of the underlying React components via SSR, even if they're not injected with functionality. This would be very easy to do -- just detect whether `window` is available, and attach or not.

**Comment by leebenson** [comment]
See https://github.com/stripe/react-stripe-elements/issues/120#issuecomment-341895412 for a fix.

**Comment by oliviertassinari** [comment]
> Hi @rgnevashev, this is actually working as expected.

@fred-stripe While it make sense to only have the strip elements displayed when the JS runtime is available, this doesn't make the issue resolved. 

The main issue comes from the fact than we can't take advantage of the libraries in isomorphic react applications. We should be able to import the library server side. Then only rendering it client side.

```jsx
import React from 'react';
import {render} from 'react-dom';
import {StripeProvider} from 'react-stripe-elements';

import MyStoreCheckout from './MyStoreCheckout';

import React, { Component } from 'react'
import PropTypes from 'prop-types'

class NoSSR extends Component {
  state = {
    mounted: false,
  }

  componentDidMount() {
    this.setState({ mounted: true })
  }

  render() {
    return this.state.mounted ? this.props.children : <() => null />
  }
}

const App = () => {
  return (
    <NoSSR>
      <StripeProvider apiKey="pk_test_12345">
        <MyStoreCheckout />
      </StripeProvider>
    </NoSSR>
  );
};
```

**Comment by leebenson** [comment]
@oliviertassinari - I released [react-stripe-elements-universal](https://www.npmjs.com/package/react-stripe-elements-universal) which fixes SSR compatibility.

**Comment by oliviertassinari** [comment]
@leebenson No offense, but relying on third party for payment isn't an option for us.

**Comment by leebenson** [comment]
_Everything_ is third-party in open source. If Stripe don't get their act together, what's your alternative?

**Comment by jez** [comment]
👋 Hey everyone! First I want to say thanks for your work on both bringing this issue to our attention, and for coming up with some creative solutions on your own. At Stripe we love building tools and features that make our lives easier, and support for SSR is one of many such features.

We're currently discussing the best way to implement SSR alongside some of our other goals, such as allowing Stripe.js to be loaded asynchronously (#24). We might be able to kill two birds with one stone!

**Comment by jandramila** [comment]
@jez I'm not trying to sound like I'm hurrying you but do you guys have an ETA on this functionality? As I'm planning to move from Stripe v2 to v3, and would be great if this package supports SSR, so maybe it's better for me to wait for it.

**Comment by leebenson** [comment]
@jandramila - just use https://www.npmjs.com/package/react-stripe-elements-universal and then switch to the 'official' version when it's ready. It's exactly the same library, minus lib instantiation when `window` doesn't exist. Hence, it works via SSR.

This whole repo in its current form is just a really thin wrapper that basically passes through the Stripe element tree as context, so there's zero magic here.

A more interesting feature will be async loading, but until then, no need to wait for anything to land officially!

**Comment by jandramila** [comment]
@leebenson I'll give it a try, thanks for the quick response.

**Comment by iamuteti** [comment]
@leebenson your package worked for me perfectly. Thank you

**Comment by leebenson** [comment]
My pleasure, @iamuteti. Glad you found it useful.

**Comment by mmmikeal** [comment]
@leebenson dumbest question youll get today, how do i install your library and replace my current elements? Readme doesnt say

**Comment by leebenson** [comment]
@mmmikeal, whilst you could just `npm i -S react-stripe-elements-universal` and import _that_ instead of react-stripe-elements, I'd advise against it before getting the official word from @jez -- it's possible/(probable?) that SSR support is already officially support.

Plus, my fork is 10 months old now, so is likely horribly out of date...

**Comment by mmmikeal** [comment]
thanks guys I figured out how to install and import universal yesterday, also that my problems were unrelated to SSR!
