### ISSUE TITLE
Accessing Error state of <CardElement>

### ISSUE THREAD

**Issue by sonarforte** [stripe/react-stripe-elements#65]
The `<CardElement>` component obviously has some internal method of determining error state, as it will highlight red certain values that are invalid.

How can I access this state, (maybe through the `StripeProvider`) so that I can disable the form submission if the values are invalid?

**Comment by fred-stripe** [comment]
Hi @sonarforte, you'll want to pass an `onChange={changeFunction}` property to the CardElement. Stripe Elements will send an event for each update to the elements' fields contents, and each event contains an `error` field that specifies the current error state. More on this in the Stripe.js reference:

https://stripe.com/docs/stripe.js#element-on

You will want to assume that any elements are initially invalid, because they will not have any information entered in them, and then use your `onChange` callback to update your parent component's state accordingly.

**Comment by sonarforte** [comment]
Thanks, I'll probably dispatch an action with the `onChange` function that will include the error payload (I'm using redux).

**Comment by jenan-stripe** [comment]
👍

**Comment by alonsorobles** [comment]
I'm currently using version 1.3.1 and looking to do the same thing. Basically, I want to modify the UI look and feel to display appropriate error message to the end user. I am able to get a token upon form submission. However, my onChange handler doesn't seem to be getting called. 

My element is declared like `<CardElement style={{base: {fontSize: '16px'}}} onChange={onStripeChange} className="CardElement"/>`. 

Using the Chrome React tools, I can see that the only thing assigned to the onChange prop is a noop(). 

![image](https://user-images.githubusercontent.com/98739/34902648-8568911e-f7e5-11e7-95c3-f6c41d8b5a4a.png)

Any advice on what I maybe doing wrong?

**Comment by morenoh149** [comment]
@fred-stripe can you expand on this with a snippet?
I am trying to do
```es
import { func } from 'prop-types'                                                  
import { Button, Form, FormGroup, Label } from 'reactstrap'                        
import { connect } from 'react-redux'                                              
import { Field, reduxForm } from 'redux-form'                                      
import {                                                                                        
  CardExpiryElement,                                                                
} from 'react-stripe-elements'                                 
const handleChange = change => {                                                   
  console.log('[change]', change);                                   
};                                                                                 
const ConfirmationPaymentForm = ({ handleSubmit }) => (   
  <form                                                                            
    onSubmit={handleSubmit}                                                        
    className="confirmation__payment-form"                                         
  >                                                                                                                                  
    <FormGroup>                                                                    
      <Label>Expiration</Label>                                                    
      <CardExpiryElement                                                           
        onChange={handleChange}                                        
        className="form-control"                                                   
      />                                                                                                                         
    <Button type="submit">Submit</Button>                                          
  </form>                                                                          
)
```
but the input stops accepting new input and the entire form is no longer usable.
