### ISSUE TITLE
Add TypeScript declarations

### ISSUE THREAD

**Issue by jaredpalmer** [stripe/react-stripe-elements#7]

**Comment by stephen** [comment]
I'll taking a shot a these today 🌟

**Comment by mattes3** [comment]
Today, I tried to do a
`npm install --save @types/react-stripe-elements`
but it failed! Has the type definition not yet been uploaded to DefinitelyTyped?

**Comment by jenan-stripe** [comment]
Hi @mattes3! Please see my comment in #10 ([here](https://github.com/stripe/react-stripe-elements/pull/10#issuecomment-316851527)). We're not currently maintaining TypeScript declarations as part of this repo but would be 👍 to the community doing so elsewhere.

I'm going to close this out for now.
