### ISSUE TITLE
Focus hijacking of a <input> in <Elements> when nested in a <label>

### ISSUE THREAD

**Issue by matthewarkin** [stripe/react-stripe-elements#81]
I've got a funky thing happening where if I have a non-Elements input (for the customer's name), when a user clicks on it the focus is being stolen and set to the CVC element.

I was able to reproduce it at https://jsfiddle.net/69z2wepo/86025/ and it looks like Stripe.js is attaching a click handler to the parent <label> that is wrapping everything and stealing the focus.

**Comment by michelle** [comment]
Hey @matthewarkin! Thanks for the Fiddle :). This is intentional -- generally, there should be one `label` element per input. The native browser behavior is also that the wrapping label focuses the associated input. Is there a reason you need your label to wrap multiple input elements?

**Comment by matthewarkin** [comment]
Hmm yeah, I just inherited the code and was adding Elements, my assumption is that its just for styling. I also noticed in my fiddle that it just captures the focus of the first parent label, so if I have
```
<label>
    <label>
       <CardNumberElement/>
    </label>
    <label>
       <Input/>
    </label>
    <label>
       <CardExpiryElement/>
    </label>
</label
```
This doesn't do weird hijacking (ignoring that this is against html5 spec).

I'll close this out since it looks like just weird DOM structure on my part (which is always fun to debug at 11pm)
