### ISSUE TITLE
How to load https://js.stripe.com/v3/ only on pages that require it?

### ISSUE THREAD

**Issue by parrker** [stripe/react-stripe-elements#94]
What is the best practice of loading the Stripe.js script only on those React routes (components) that actually need it? For example, I don't want to load it on the login screen of my application.

**Comment by jez** [comment]
In fact, the best practice **is** to load stripe.js on every page:

From <https://stripe.com/docs/stripe.js#including-stripejs>:

> To best leverage Stripe’s advanced fraud functionality, include this script on every page on your site, not just the checkout page. This allows Stripe to detect anomalous behavior that may be indicative of fraud as users browse your website.

Stripe.js is architected to make this workflow as lightweight as possible. On page load, only a small outer shim script is loaded. Eventually (i.e., when you try to create an element and mount it), the outer shim will take care of loading the rest of the script. For reference, the outer shim is currently only ~20 KB (and we monitor that this size stays relatively constant).

Hope this helps!

**Comment by gregbrunk** [comment]
Late to the party, but though Jez is correct, if you still want to conditionally load the script, you can use this @parrker: https://github.com/nfl/react-helmet.

**Comment by ozluy** [comment]
How about this?
https://medium.com/@ozluy/loading-stripe-script-if-necessary-189f228e0f34

**Comment by yasir-lateef** [comment]
@ozluy That was a real life-saver! I spent almost 3-4 hours trying to get it work on my own. Your module just made it work out of the box. Thanks!

**Comment by KhaledMohamedP** [comment]
In case you missed it, stripe released an alternative way to loading the js library
more details in here -> https://stripe.com/docs/stripe-js/react

**Comment by cloud-walker** [comment]
The problem with async script loading technique, is that is not really testable (without brutally mocking the whole script loader module).

**Comment by utkarshdalal** [comment]
> In case you missed it, stripe released an alternative way to loading the js library
> more details in here -> https://stripe.com/docs/stripe-js/react

Just wanted to say that this is the correct way to do it for anyone looking now. You no longer need to include the script, and can simply do something like:

```
import {loadStripe} from '@stripe/stripe-js';
const stripePromise = loadStripe('pk_test_JJ1eMdKN0Hp4UFJ6kWXWO4ix00jtXzq5XG');

const App = () => {
  return (
      <MyCheckoutForm />
  );
};
```
