### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by pbreah** [stripe/react-stripe-elements#96]
Guys, I really appreciate the work and effort made to make react-stripe-elements available.

But making a separate set of form components is forcing us to break away from the react components we are already using on our setup, and then comes the work to make these components fit with the rest of the UI, making it harder to work with it.

I know some people would appreciate having all the logic baked inside these components to build a card & payment form quick, but it is like re-inventing the wheel when there are great react form libraries that stripe could integrate into, making it easier for us developers that want to keep their UI consistent - and not be forced to fit yet another type of component in the mix.

**Suggestion one**: [react-redux-form](https://github.com/davidkpiano/react-redux-form) and [redux-form](https://github.com/erikras/redux-form) are good form libraries that stripe can integrate into, making it easier to work with stripe for most of us.

**Suggestion two**: There are plenty of use cases in which we may want to create our own form component and want to create a token without being forced to integrate a specific set of components. If I want to pass the payment info as parameters to the stripe API and get back the token - clean and simple, without having to setup a form with another set of components (don't understand why v3 is going in this direction - giving more integration option is better than reducing them)

**Comment by jenan-stripe** [comment]
Hi @pbreah,

Thanks very much for the feedback!

We built elements to make it as simple as possible keep your UI consistent while still making SAQ A compatibility easy. For better or worse, the latest PCI guidelines say that to be eligible for SAQ A, sensitive card information must be collected within an iframe. We know it's different than directly controlling inputs, but you get a lot of power for that tradeoff (masking, formatting, localization, responsiveness, dynamic zip, etc). If you're running into specific use cases that don't fit into your forms or are hard to customize, please do contact support! (support@stripe.com).

Regarding redux: we don't want force all users of react-stripe-elements to use redux. If there are specific improvements to react-stripe-elements that would make redux tools easier to use, we'd love to hear them!
