### ISSUE TITLE
TypeScript with JS extension?

### ISSUE THREAD

**Issue by janiukjf** [stripe/react-stripe-elements#97]
I'm just curious why the choice was made to use .js instead of .ts file extensions. VSCode throws all sorts of `[js] 'types' can only be used in a .ts file.` errors when opening this project.

**Comment by jenan-stripe** [comment]
Hi @janiukjf -- this project uses Flow, not Typescript!

**Comment by janiukjf** [comment]
*facepalm on my part* Sorry for the confusion
